// Vaste data voor de publieke "Predicted Lineups"-tab (zie src/tabs/PredictedLineupsTab.jsx) — zelfde
// conventie als TEAMS/FIXTURES in constants.js: gewoon een statische constante, geen fetch, geen
// bewerkbare state.
//
// Elke entry heeft grotendeels dezelfde vorm als een record uit de privé Predicted XI Builder's
// opgeslagen lineups (zie loadStoredDrafts()/sanitizeDraft() in src/predicted-xi/storage.js): clubCode,
// opponentCode, formationKey, formationLabelOverride, slots (met per slot playerName/playerTeamCode/
// playerPosition/playerPrice/safety/positionId/xPercent/yPercent), notes.
//
// Volledig vervangen (niet aangevuld) telkens een nieuwe export van de privé-tool binnenkomt — zie
// PREDICTED_LINEUPS_GW in constants.js voor de speeldag waarvoor DEZE data geldt. Bewust een volledige
// vervanging i.p.v. een aanvulling: een eerdere aanvul-aanpak liet oude en nieuwe entries voor dezelfde
// club naast elkaar in de array staan, wat zowel een kapotte JSON-naad als een stille "oude opstelling
// getoond als actueel"-bug opleverde (zie de commit-geschiedenis). Alle 18 clubs aangeleverd 11
// september 2026 (GW6).
export const PREDICTED_LINEUPS = [
  {
    "id": "70557fad-4070-4254-92e1-713f2fffcee8",
    "clubCode": "AND",
    "opponentCode": "KVM",
    "formationKey": "4-3-3",
    "slots": [
      {
        "positionId": "GK",
        "role": "GK",
        "broadPosition": "GK",
        "xPercent": 50,
        "yPercent": 85,
        "playerName": "Coosemans",
        "playerTeamCode": "AND",
        "playerPosition": "GK",
        "playerPrice": 6.5,
        "safety": "darkgreen"
      },
      {
        "positionId": "LWB",
        "role": "LWB",
        "broadPosition": "DEF",
        "xPercent": 16,
        "yPercent": 61,
        "playerName": "Augustinsson",
        "playerTeamCode": "AND",
        "playerPosition": "DEF",
        "playerPrice": 6,
        "safety": "green"
      },
      {
        "positionId": "LCB",
        "role": "LCB",
        "broadPosition": "DEF",
        "xPercent": 33,
        "yPercent": 74,
        "playerName": "Petrot",
        "playerTeamCode": "AND",
        "playerPosition": "DEF",
        "playerPrice": 6,
        "safety": "darkgreen"
      },
      {
        "positionId": "RCB",
        "role": "RCB",
        "broadPosition": "DEF",
        "xPercent": 67,
        "yPercent": 74,
        "playerName": "Biancone",
        "playerTeamCode": "AND",
        "playerPosition": "DEF",
        "playerPrice": 6,
        "safety": "darkgreen"
      },
      {
        "positionId": "RWB",
        "role": "RWB",
        "broadPosition": "DEF",
        "xPercent": 84,
        "yPercent": 61,
        "playerName": "Maamar",
        "playerTeamCode": "AND",
        "playerPosition": "DEF",
        "playerPrice": 5,
        "safety": "darkgreen"
      },
      {
        "positionId": "LCM",
        "role": "LCM",
        "broadPosition": "MID",
        "xPercent": 33,
        "yPercent": 46,
        "playerName": "Kana",
        "playerTeamCode": "AND",
        "playerPosition": "MID",
        "playerPrice": 5.5,
        "safety": "orange"
      },
      {
        "positionId": "CAM",
        "role": "CAM",
        "broadPosition": "MID",
        "xPercent": 50,
        "yPercent": 30,
        "playerName": "Ambros",
        "playerTeamCode": "AND",
        "playerPosition": "MID",
        "playerPrice": 6,
        "safety": "green"
      },
      {
        "positionId": "RCM",
        "role": "RCM",
        "broadPosition": "MID",
        "xPercent": 67,
        "yPercent": 46,
        "playerName": "Koutsoupias",
        "playerTeamCode": "AND",
        "playerPosition": "MID",
        "playerPrice": 7,
        "safety": "red"
      },
      {
        "positionId": "LW",
        "role": "LW",
        "broadPosition": "FWD",
        "xPercent": 16,
        "yPercent": 21,
        "playerName": "Antman",
        "playerTeamCode": "AND",
        "playerPosition": "MID",
        "playerPrice": 6,
        "safety": "red"
      },
      {
        "positionId": "ST",
        "role": "ST",
        "broadPosition": "FWD",
        "xPercent": 50,
        "yPercent": 10,
        "playerName": "Sikan",
        "playerTeamCode": "AND",
        "playerPosition": "FWD",
        "playerPrice": 6.5,
        "safety": "green"
      },
      {
        "positionId": "RW",
        "role": "RW",
        "broadPosition": "FWD",
        "xPercent": 84,
        "yPercent": 21,
        "playerName": "Cvetkovic",
        "playerTeamCode": "AND",
        "playerPosition": "FWD",
        "playerPrice": 8.5,
        "safety": "orange"
      },
      {
        "positionId": "_unassigned",
        "role": "DEF",
        "broadPosition": "DEF",
        "xPercent": 0,
        "yPercent": 0,
        "playerName": "Drouhin",
        "playerTeamCode": "KOR",
        "playerPosition": "DEF",
        "playerPrice": 4.5,
        "safety": "darkgreen"
      },
      {
        "positionId": "_unassigned",
        "role": "MID",
        "broadPosition": "MID",
        "xPercent": 0,
        "yPercent": 0,
        "playerName": "Koutsoupias",
        "playerTeamCode": "AND",
        "playerPosition": "MID",
        "playerPrice": 7,
        "safety": "darkgreen"
      }
    ],
    "notes": "",
    "label": "",
    "createdAt": 1786097247576,
    "updatedAt": 1789140744459
  },
  {
    "id": "0b13b947-6c92-4adf-afa6-f9a12170e160",
    "clubCode": "GNT",
    "opponentCode": "GNK",
    "formationKey": "5-3-2",
    "slots": [
      {
        "positionId": "GK",
        "role": "GK",
        "broadPosition": "GK",
        "xPercent": 50,
        "yPercent": 85,
        "playerName": "Roef",
        "playerTeamCode": "GNT",
        "playerPosition": "GK",
        "playerPrice": 7,
        "safety": "darkgreen"
      },
      {
        "positionId": "LWB",
        "role": "LWB",
        "broadPosition": "DEF",
        "xPercent": 16,
        "yPercent": 61,
        "playerName": "Araujo",
        "playerTeamCode": "GNT",
        "playerPosition": "DEF",
        "playerPrice": 5.5,
        "safety": "darkgreen"
      },
      {
        "positionId": "LCB",
        "role": "LCB",
        "broadPosition": "DEF",
        "xPercent": 33,
        "yPercent": 74,
        "playerName": "Van der Heyden",
        "playerTeamCode": "GNT",
        "playerPosition": "DEF",
        "playerPrice": 5.5,
        "safety": "darkgreen"
      },
      {
        "positionId": "CCB",
        "role": "CCB",
        "broadPosition": "DEF",
        "xPercent": 50,
        "yPercent": 76,
        "playerName": "Burgess",
        "playerTeamCode": "GNT",
        "playerPosition": "DEF",
        "playerPrice": 7,
        "safety": "darkgreen"
      },
      {
        "positionId": "RCB",
        "role": "RCB",
        "broadPosition": "DEF",
        "xPercent": 67,
        "yPercent": 74,
        "playerName": "Ngom",
        "playerTeamCode": "GNT",
        "playerPosition": "DEF",
        "playerPrice": 5,
        "safety": "darkgreen"
      },
      {
        "positionId": "RWB",
        "role": "RWB",
        "broadPosition": "DEF",
        "xPercent": 84,
        "yPercent": 61,
        "playerName": "Volckaert",
        "playerTeamCode": "GNT",
        "playerPosition": "DEF",
        "playerPrice": 5,
        "safety": "orange"
      },
      {
        "positionId": "LCM",
        "role": "LCM",
        "broadPosition": "MID",
        "xPercent": 33,
        "yPercent": 46,
        "playerName": "Delorge",
        "playerTeamCode": "GNT",
        "playerPosition": "MID",
        "playerPrice": 7,
        "safety": "green"
      },
      {
        "positionId": "CAM",
        "role": "CAM",
        "broadPosition": "MID",
        "xPercent": 50,
        "yPercent": 30,
        "playerName": "Balikwisha",
        "playerTeamCode": "GNT",
        "playerPosition": "MID",
        "playerPrice": 6.5,
        "safety": "orange"
      },
      {
        "positionId": "RCM",
        "role": "RCM",
        "broadPosition": "MID",
        "xPercent": 67,
        "yPercent": 46,
        "playerName": "De Vlieger",
        "playerTeamCode": "GNT",
        "playerPosition": "MID",
        "playerPrice": 6,
        "safety": "green"
      },
      {
        "positionId": "LST",
        "role": "LST",
        "broadPosition": "FWD",
        "xPercent": 28,
        "yPercent": 15,
        "playerName": "Sonko",
        "playerTeamCode": "GNT",
        "playerPosition": "MID",
        "playerPrice": 6.5,
        "safety": "green"
      },
      {
        "positionId": "RST",
        "role": "RST",
        "broadPosition": "FWD",
        "xPercent": 72,
        "yPercent": 15,
        "playerName": "Vergara",
        "playerTeamCode": "GNT",
        "playerPosition": "FWD",
        "playerPrice": 5.5,
        "safety": "darkgreen"
      }
    ],
    "notes": "",
    "label": "",
    "createdAt": 1786097520119,
    "updatedAt": 1789140560338
  },
  {
    "id": "d9c1eea1-b894-4907-b0d3-08a62b48ac50",
    "clubCode": "ANT",
    "opponentCode": "CLU",
    "formationKey": "4-4-2",
    "slots": [
      {
        "positionId": "GK",
        "role": "GK",
        "broadPosition": "GK",
        "xPercent": 50,
        "yPercent": 85,
        "playerName": "Nozawa",
        "playerTeamCode": "ANT",
        "playerPosition": "GK",
        "playerPrice": 6,
        "safety": "darkgreen"
      },
      {
        "positionId": "LB",
        "role": "LB",
        "broadPosition": "DEF",
        "xPercent": 16,
        "yPercent": 71,
        "playerName": "Renders",
        "playerTeamCode": "ANT",
        "playerPosition": "DEF",
        "playerPrice": 5,
        "safety": "orange"
      },
      {
        "positionId": "LCB",
        "role": "LCB",
        "broadPosition": "DEF",
        "xPercent": 36,
        "yPercent": 74,
        "playerName": "Cortes",
        "playerTeamCode": "ANT",
        "playerPosition": "DEF",
        "playerPrice": 6,
        "safety": "darkgreen"
      },
      {
        "positionId": "RCB",
        "role": "RCB",
        "broadPosition": "DEF",
        "xPercent": 64,
        "yPercent": 74,
        "playerName": "Van Helden",
        "playerTeamCode": "ANT",
        "playerPosition": "DEF",
        "playerPrice": 6.5,
        "safety": "red"
      },
      {
        "positionId": "RB",
        "role": "RB",
        "broadPosition": "DEF",
        "xPercent": 84,
        "yPercent": 71,
        "playerName": "Somers",
        "playerTeamCode": "ANT",
        "playerPosition": "MID",
        "playerPrice": 8,
        "safety": "darkgreen"
      },
      {
        "positionId": "LM",
        "role": "LM",
        "broadPosition": "MID",
        "xPercent": 16,
        "yPercent": 46,
        "playerName": "Scott",
        "playerTeamCode": "ANT",
        "playerPosition": "MID",
        "playerPrice": 6.5,
        "safety": "red"
      },
      {
        "positionId": "LCM",
        "role": "LCM",
        "broadPosition": "MID",
        "xPercent": 33,
        "yPercent": 46,
        "playerName": "Dierckx",
        "playerTeamCode": "ANT",
        "playerPosition": "MID",
        "playerPrice": 5,
        "safety": "red"
      },
      {
        "positionId": "RCM",
        "role": "RCM",
        "broadPosition": "MID",
        "xPercent": 67,
        "yPercent": 46,
        "playerName": "Vermeeren",
        "playerTeamCode": "ANT",
        "playerPosition": "MID",
        "playerPrice": 8,
        "safety": "darkgreen"
      },
      {
        "positionId": "RM",
        "role": "RM",
        "broadPosition": "MID",
        "xPercent": 84,
        "yPercent": 46,
        "playerName": "Salah",
        "playerTeamCode": "ANT",
        "playerPosition": "MID",
        "playerPrice": 6,
        "safety": "darkgreen"
      },
      {
        "positionId": "LST",
        "role": "LST",
        "broadPosition": "FWD",
        "xPercent": 28,
        "yPercent": 15,
        "playerName": "Porozo",
        "playerTeamCode": "ANT",
        "playerPosition": "FWD",
        "playerPrice": 5,
        "safety": "red"
      },
      {
        "positionId": "RST",
        "role": "RST",
        "broadPosition": "FWD",
        "xPercent": 72,
        "yPercent": 15,
        "playerName": "Frey",
        "playerTeamCode": "ANT",
        "playerPosition": "FWD",
        "playerPrice": 6.5,
        "safety": "darkgreen"
      },
      {
        "positionId": "_unassigned",
        "role": "MID",
        "broadPosition": "FWD",
        "xPercent": 0,
        "yPercent": 0,
        "playerName": "Valencia",
        "playerTeamCode": "ANT",
        "playerPosition": "MID",
        "playerPrice": 5,
        "safety": "darkgreen"
      },
      {
        "positionId": "_unassigned",
        "role": "DEF",
        "broadPosition": "DEF",
        "xPercent": 0,
        "yPercent": 0,
        "playerName": "Renders",
        "playerTeamCode": "ANT",
        "playerPosition": "DEF",
        "playerPrice": 5,
        "safety": "darkgreen"
      }
    ],
    "notes": "",
    "label": "",
    "createdAt": 1787319716532,
    "updatedAt": 1789140598321
  },
  {
    "id": "277ccdb4-777e-422f-9022-db0b76dd5e00",
    "clubCode": "CHA",
    "opponentCode": "ZWA",
    "formationKey": "4-3-3",
    "slots": [
      {
        "positionId": "GK",
        "role": "GK",
        "broadPosition": "GK",
        "xPercent": 50,
        "yPercent": 85,
        "playerName": "Kone",
        "playerTeamCode": "CHA",
        "playerPosition": "GK",
        "playerPrice": 5.5,
        "safety": "darkgreen"
      },
      {
        "positionId": "LB",
        "role": "LB",
        "broadPosition": "DEF",
        "xPercent": 16,
        "yPercent": 71,
        "playerName": "Nzita",
        "playerTeamCode": "CHA",
        "playerPosition": "DEF",
        "playerPrice": 5.5,
        "safety": "darkgreen"
      },
      {
        "positionId": "LCB",
        "role": "LCB",
        "broadPosition": "DEF",
        "xPercent": 36,
        "yPercent": 74,
        "playerName": "Ousou",
        "playerTeamCode": "CHA",
        "playerPosition": "DEF",
        "playerPrice": 6.5,
        "safety": "darkgreen"
      },
      {
        "positionId": "RCB",
        "role": "RCB",
        "broadPosition": "DEF",
        "xPercent": 64,
        "yPercent": 74,
        "playerName": "Keita",
        "playerTeamCode": "CHA",
        "playerPosition": "DEF",
        "playerPrice": 6,
        "safety": "darkgreen"
      },
      {
        "positionId": "RB",
        "role": "RB",
        "broadPosition": "DEF",
        "xPercent": 84,
        "yPercent": 71,
        "playerName": "Van Den Kerkhof",
        "playerTeamCode": "CHA",
        "playerPosition": "DEF",
        "playerPrice": 5.5,
        "safety": "darkgreen"
      },
      {
        "positionId": "LCM",
        "role": "LCM",
        "broadPosition": "MID",
        "xPercent": 33,
        "yPercent": 46,
        "playerName": "Khalifi",
        "playerTeamCode": "CHA",
        "playerPosition": "MID",
        "playerPrice": 4.5,
        "safety": "darkgreen"
      },
      {
        "positionId": "CAM",
        "role": "CAM",
        "broadPosition": "MID",
        "xPercent": 50,
        "yPercent": 30,
        "playerName": "Romsaas",
        "playerTeamCode": "CHA",
        "playerPosition": "FWD",
        "playerPrice": 6.5,
        "safety": "darkgreen"
      },
      {
        "positionId": "RCM",
        "role": "RCM",
        "broadPosition": "MID",
        "xPercent": 67,
        "yPercent": 46,
        "playerName": "Boukamir A.",
        "playerTeamCode": "CHA",
        "playerPosition": "DEF",
        "playerPrice": 4.5,
        "safety": "darkgreen"
      },
      {
        "positionId": "LW",
        "role": "LW",
        "broadPosition": "FWD",
        "xPercent": 16,
        "yPercent": 21,
        "playerName": "Mbemba",
        "playerTeamCode": "CHA",
        "playerPosition": "FWD",
        "playerPrice": 5,
        "safety": "green"
      },
      {
        "positionId": "ST",
        "role": "ST",
        "broadPosition": "FWD",
        "xPercent": 50,
        "yPercent": 10,
        "playerName": "Scheidler",
        "playerTeamCode": "CHA",
        "playerPosition": "FWD",
        "playerPrice": 8.5,
        "safety": "darkgreen"
      },
      {
        "positionId": "RW",
        "role": "RW",
        "broadPosition": "FWD",
        "xPercent": 84,
        "yPercent": 21,
        "playerName": "Pflucke",
        "playerTeamCode": "CHA",
        "playerPosition": "MID",
        "playerPrice": 7,
        "safety": "darkgreen"
      }
    ],
    "notes": "",
    "label": "",
    "createdAt": 1788540300952,
    "updatedAt": 1789140528305
  },
  {
    "id": "b1d8b881-f7f0-4b6d-913d-079732265a2a",
    "clubCode": "WES",
    "opponentCode": "STA",
    "formationKey": "4-3-3",
    "slots": [
      {
        "positionId": "GK",
        "role": "GK",
        "broadPosition": "GK",
        "xPercent": 50,
        "yPercent": 85,
        "playerName": "Jungdal",
        "playerTeamCode": "WES",
        "playerPosition": "GK",
        "playerPrice": 6.5,
        "safety": "darkgreen"
      },
      {
        "positionId": "LB",
        "role": "LB",
        "broadPosition": "DEF",
        "xPercent": 16,
        "yPercent": 71,
        "playerName": "Ourega",
        "playerTeamCode": "WES",
        "playerPosition": "DEF",
        "playerPrice": 4.5,
        "safety": "green"
      },
      {
        "positionId": "LCB",
        "role": "LCB",
        "broadPosition": "DEF",
        "xPercent": 36,
        "yPercent": 74,
        "playerName": "Lapage",
        "playerTeamCode": "WES",
        "playerPosition": "DEF",
        "playerPrice": 5,
        "safety": "green"
      },
      {
        "positionId": "RCB",
        "role": "RCB",
        "broadPosition": "DEF",
        "xPercent": 64,
        "yPercent": 74,
        "playerName": "Kimura",
        "playerTeamCode": "WES",
        "playerPosition": "DEF",
        "playerPrice": 5,
        "safety": "green"
      },
      {
        "positionId": "RB",
        "role": "RB",
        "broadPosition": "DEF",
        "xPercent": 84,
        "yPercent": 71,
        "playerName": "Flo",
        "playerTeamCode": "WES",
        "playerPosition": "DEF",
        "playerPrice": 5,
        "safety": "darkgreen"
      },
      {
        "positionId": "LCM",
        "role": "LCM",
        "broadPosition": "MID",
        "xPercent": 33,
        "yPercent": 46,
        "playerName": "Sandra",
        "playerTeamCode": "WES",
        "playerPosition": "MID",
        "playerPrice": 6,
        "safety": "green"
      },
      {
        "positionId": "CAM",
        "role": "CAM",
        "broadPosition": "MID",
        "xPercent": 50,
        "yPercent": 30,
        "playerName": "Sakamoto",
        "playerTeamCode": "WES",
        "playerPosition": "FWD",
        "playerPrice": 7,
        "safety": "darkgreen"
      },
      {
        "positionId": "RCM",
        "role": "RCM",
        "broadPosition": "MID",
        "xPercent": 67,
        "yPercent": 46,
        "playerName": "Fofana",
        "playerTeamCode": "WES",
        "playerPosition": "MID",
        "playerPrice": 5.5,
        "safety": "darkgreen"
      },
      {
        "positionId": "LW",
        "role": "LW",
        "broadPosition": "FWD",
        "xPercent": 16,
        "yPercent": 21,
        "playerName": "Saito",
        "playerTeamCode": "WES",
        "playerPosition": "MID",
        "playerPrice": 5.5,
        "safety": "darkgreen"
      },
      {
        "positionId": "ST",
        "role": "ST",
        "broadPosition": "FWD",
        "xPercent": 50,
        "yPercent": 10,
        "playerName": "Bassette",
        "playerTeamCode": "WES",
        "playerPosition": "FWD",
        "playerPrice": 6.5,
        "safety": "darkgreen"
      },
      {
        "positionId": "RW",
        "role": "RW",
        "broadPosition": "FWD",
        "xPercent": 84,
        "yPercent": 21,
        "playerName": "Congreve",
        "playerTeamCode": "WES",
        "playerPosition": "MID",
        "playerPrice": 5.5,
        "safety": "darkgreen"
      }
    ],
    "notes": "",
    "label": "",
    "createdAt": 1788540441711,
    "updatedAt": 1789140721686
  },
  {
    "id": "bf83b865-8518-408d-95ec-0acfb25f8a26",
    "clubCode": "CER",
    "opponentCode": "OHL",
    "formationKey": "3-5-2",
    "slots": [
      {
        "positionId": "GK",
        "role": "GK",
        "broadPosition": "GK",
        "xPercent": 50,
        "yPercent": 85,
        "playerName": "Coucke",
        "playerTeamCode": "CER",
        "playerPosition": "GK",
        "playerPrice": 5.5,
        "safety": "darkgreen"
      },
      {
        "positionId": "LCB",
        "role": "LCB",
        "broadPosition": "DEF",
        "xPercent": 36,
        "yPercent": 74,
        "playerName": "Kondo",
        "playerTeamCode": "CER",
        "playerPosition": "DEF",
        "playerPrice": 5,
        "safety": "darkgreen"
      },
      {
        "positionId": "CCB",
        "role": "CCB",
        "broadPosition": "DEF",
        "xPercent": 50,
        "yPercent": 76,
        "playerName": "Kakou",
        "playerTeamCode": "CER",
        "playerPosition": "DEF",
        "playerPrice": 5.5,
        "safety": "orange"
      },
      {
        "positionId": "RCB",
        "role": "RCB",
        "broadPosition": "DEF",
        "xPercent": 64,
        "yPercent": 74,
        "playerName": "Diakite",
        "playerTeamCode": "CER",
        "playerPosition": "DEF",
        "playerPrice": 5,
        "safety": "darkgreen"
      },
      {
        "positionId": "LWB",
        "role": "LWB",
        "broadPosition": "DEF",
        "xPercent": 16,
        "yPercent": 61,
        "playerName": "Konate",
        "playerTeamCode": "CER",
        "playerPosition": "DEF",
        "playerPrice": 4.5,
        "safety": "darkgreen"
      },
      {
        "positionId": "LW",
        "role": "LW",
        "broadPosition": "FWD",
        "xPercent": 16,
        "yPercent": 21,
        "playerName": "Martens",
        "playerTeamCode": "CER",
        "playerPosition": "MID",
        "playerPrice": 4,
        "safety": "orange"
      },
      {
        "positionId": "LCM",
        "role": "LCM",
        "broadPosition": "MID",
        "xPercent": 33,
        "yPercent": 46,
        "playerName": "Amani",
        "playerTeamCode": "CER",
        "playerPosition": "MID",
        "playerPrice": 6.5,
        "safety": "darkgreen"
      },
      {
        "positionId": "RCM",
        "role": "RCM",
        "broadPosition": "MID",
        "xPercent": 67,
        "yPercent": 46,
        "playerName": "Mondele",
        "playerTeamCode": "CER",
        "playerPosition": "MID",
        "playerPrice": 4,
        "safety": "darkgreen"
      },
      {
        "positionId": "RWB",
        "role": "RWB",
        "broadPosition": "DEF",
        "xPercent": 84,
        "yPercent": 61,
        "playerName": "Magnee",
        "playerTeamCode": "CER",
        "playerPosition": "DEF",
        "playerPrice": 6.5,
        "safety": "darkgreen"
      },
      {
        "positionId": "ST",
        "role": "ST",
        "broadPosition": "FWD",
        "xPercent": 50,
        "yPercent": 10,
        "playerName": "Ngoura",
        "playerTeamCode": "CER",
        "playerPosition": "FWD",
        "playerPrice": 6.5,
        "safety": "green"
      },
      {
        "positionId": "RW",
        "role": "RW",
        "broadPosition": "FWD",
        "xPercent": 84,
        "yPercent": 21,
        "playerName": "Akinsola",
        "playerTeamCode": "CER",
        "playerPosition": "MID",
        "playerPrice": 5,
        "safety": "red"
      },
      {
        "positionId": "_unassigned",
        "role": "MID",
        "broadPosition": "MID",
        "xPercent": 0,
        "yPercent": 0,
        "playerName": "Akinsola",
        "playerTeamCode": "CER",
        "playerPosition": "MID",
        "playerPrice": 5,
        "safety": "darkgreen"
      }
    ],
    "notes": "",
    "label": "",
    "createdAt": 1788540711987,
    "updatedAt": 1789140678934
  },
  {
    "id": "573d5c1d-7c10-4c3a-9716-bf82c5a2d013",
    "clubCode": "LOM",
    "opponentCode": "USG",
    "formationKey": "4-3-3",
    "slots": [
      {
        "positionId": "GK",
        "role": "GK",
        "broadPosition": "GK",
        "xPercent": 50,
        "yPercent": 85,
        "playerName": "Pieklak",
        "playerTeamCode": "LOM",
        "playerPosition": "GK",
        "playerPrice": 5.5,
        "safety": "darkgreen"
      },
      {
        "positionId": "LB",
        "role": "LB",
        "broadPosition": "DEF",
        "xPercent": 16,
        "yPercent": 71,
        "playerName": "De Grand",
        "playerTeamCode": "LOM",
        "playerPosition": "DEF",
        "playerPrice": 5,
        "safety": "red"
      },
      {
        "positionId": "LCB",
        "role": "LCB",
        "broadPosition": "DEF",
        "xPercent": 36,
        "yPercent": 74,
        "playerName": "Wouters",
        "playerTeamCode": "LOM",
        "playerPosition": "DEF",
        "playerPrice": 5,
        "safety": "darkgreen"
      },
      {
        "positionId": "RCB",
        "role": "RCB",
        "broadPosition": "DEF",
        "xPercent": 64,
        "yPercent": 74,
        "playerName": "Adewoye",
        "playerTeamCode": "LOM",
        "playerPosition": "DEF",
        "playerPrice": 4.5,
        "safety": "red"
      },
      {
        "positionId": "RB",
        "role": "RB",
        "broadPosition": "DEF",
        "xPercent": 84,
        "yPercent": 71,
        "playerName": "Van Duiven",
        "playerTeamCode": "LOM",
        "playerPosition": "FWD",
        "playerPrice": 5,
        "safety": "green"
      },
      {
        "positionId": "LCM",
        "role": "LCM",
        "broadPosition": "MID",
        "xPercent": 33,
        "yPercent": 46,
        "playerName": "Schoofs",
        "playerTeamCode": "LOM",
        "playerPosition": "MID",
        "playerPrice": 6.5,
        "safety": "darkgreen"
      },
      {
        "positionId": "CAM",
        "role": "CAM",
        "broadPosition": "MID",
        "xPercent": 50,
        "yPercent": 30,
        "playerName": "Reyners",
        "playerTeamCode": "LOM",
        "playerPosition": "MID",
        "playerPrice": 5.5,
        "safety": "darkgreen"
      },
      {
        "positionId": "RCM",
        "role": "RCM",
        "broadPosition": "MID",
        "xPercent": 67,
        "yPercent": 46,
        "playerName": "Pelupessy",
        "playerTeamCode": "LOM",
        "playerPosition": "MID",
        "playerPrice": 5,
        "safety": "darkgreen"
      },
      {
        "positionId": "LW",
        "role": "LW",
        "broadPosition": "FWD",
        "xPercent": 16,
        "yPercent": 21,
        "playerName": "Appuah",
        "playerTeamCode": "LOM",
        "playerPosition": "MID",
        "playerPrice": 4,
        "safety": "green"
      },
      {
        "positionId": "ST",
        "role": "ST",
        "broadPosition": "FWD",
        "xPercent": 50,
        "yPercent": 10,
        "playerName": "Konadu",
        "playerTeamCode": "LLV",
        "playerPosition": "FWD",
        "playerPrice": 5,
        "safety": "darkgreen"
      },
      {
        "positionId": "RW",
        "role": "RW",
        "broadPosition": "FWD",
        "xPercent": 84,
        "yPercent": 21,
        "playerName": "Talvitie",
        "playerTeamCode": "LOM",
        "playerPosition": "MID",
        "playerPrice": 4,
        "safety": "green"
      },
      {
        "positionId": "_unassigned",
        "role": "MID",
        "broadPosition": "MID",
        "xPercent": 0,
        "yPercent": 0,
        "playerName": "Appuah",
        "playerTeamCode": "LOM",
        "playerPosition": "MID",
        "playerPrice": 4,
        "safety": "darkgreen"
      },
      {
        "positionId": "_unassigned",
        "role": "MID",
        "broadPosition": "MID",
        "xPercent": 0,
        "yPercent": 0,
        "playerName": "Talvitie",
        "playerTeamCode": "LOM",
        "playerPosition": "MID",
        "playerPrice": 4,
        "safety": "darkgreen"
      }
    ],
    "notes": "",
    "label": "",
    "createdAt": 1788540885124,
    "updatedAt": 1789140630081
  },
  {
    "id": "302b31df-ea9b-4d09-8c8f-fe6b219185d6",
    "clubCode": "STV",
    "opponentCode": "BEV",
    "formationKey": "4-3-3",
    "slots": [
      {
        "positionId": "GK",
        "role": "GK",
        "broadPosition": "GK",
        "xPercent": 50,
        "yPercent": 85,
        "playerName": "Kokubo",
        "playerTeamCode": "STV",
        "playerPosition": "GK",
        "playerPrice": 6.5,
        "safety": "darkgreen"
      },
      {
        "positionId": "LB",
        "role": "LB",
        "broadPosition": "DEF",
        "xPercent": 16,
        "yPercent": 71,
        "playerName": "Hata",
        "playerTeamCode": "STV",
        "playerPosition": "DEF",
        "playerPrice": 5.5,
        "safety": "red"
      },
      {
        "positionId": "LCB",
        "role": "LCB",
        "broadPosition": "DEF",
        "xPercent": 36,
        "yPercent": 74,
        "playerName": "Musliu",
        "playerTeamCode": "STV",
        "playerPosition": "DEF",
        "playerPrice": 6,
        "safety": "darkgreen"
      },
      {
        "positionId": "RCB",
        "role": "RCB",
        "broadPosition": "DEF",
        "xPercent": 64,
        "yPercent": 74,
        "playerName": "Janssens",
        "playerTeamCode": "STV",
        "playerPosition": "DEF",
        "playerPrice": 4.5,
        "safety": "red"
      },
      {
        "positionId": "RB",
        "role": "RB",
        "broadPosition": "DEF",
        "xPercent": 84,
        "yPercent": 71,
        "playerName": "Vanwesemael",
        "playerTeamCode": "STV",
        "playerPosition": "DEF",
        "playerPrice": 5.5,
        "safety": "darkgreen"
      },
      {
        "positionId": "LCM",
        "role": "LCM",
        "broadPosition": "MID",
        "xPercent": 33,
        "yPercent": 46,
        "playerName": "Merlen",
        "playerTeamCode": "STV",
        "playerPosition": "MID",
        "playerPrice": 5.5,
        "safety": "darkgreen"
      },
      {
        "positionId": "CAM",
        "role": "CAM",
        "broadPosition": "MID",
        "xPercent": 50,
        "yPercent": 30,
        "playerName": "Araki",
        "playerTeamCode": "STV",
        "playerPosition": "MID",
        "playerPrice": 5.5,
        "safety": "green"
      },
      {
        "positionId": "RCM",
        "role": "RCM",
        "broadPosition": "MID",
        "xPercent": 67,
        "yPercent": 46,
        "playerName": "Sissako",
        "playerTeamCode": "STV",
        "playerPosition": "MID",
        "playerPrice": 6.5,
        "safety": "darkgreen"
      },
      {
        "positionId": "LW",
        "role": "LW",
        "broadPosition": "FWD",
        "xPercent": 16,
        "yPercent": 21,
        "playerName": "Sebaoui",
        "playerTeamCode": "STV",
        "playerPosition": "MID",
        "playerPrice": 8,
        "safety": "darkgreen"
      },
      {
        "positionId": "ST",
        "role": "ST",
        "broadPosition": "FWD",
        "xPercent": 50,
        "yPercent": 10,
        "playerName": "Bazdar",
        "playerTeamCode": "STV",
        "playerPosition": "FWD",
        "playerPrice": 5.5,
        "safety": "green"
      },
      {
        "positionId": "RW",
        "role": "RW",
        "broadPosition": "FWD",
        "xPercent": 84,
        "yPercent": 21,
        "playerName": "Matsuzawa",
        "playerTeamCode": "STV",
        "playerPosition": "MID",
        "playerPrice": 6,
        "safety": "darkgreen"
      },
      {
        "positionId": "_unassigned",
        "role": "MID",
        "broadPosition": "MID",
        "xPercent": 0,
        "yPercent": 0,
        "playerName": "Sebaoui",
        "playerTeamCode": "STV",
        "playerPosition": "MID",
        "playerPrice": 8,
        "safety": "darkgreen"
      },
      {
        "positionId": "_unassigned",
        "role": "MID",
        "broadPosition": "MID",
        "xPercent": 0,
        "yPercent": 0,
        "playerName": "Matsuzawa",
        "playerTeamCode": "STV",
        "playerPosition": "MID",
        "playerPrice": 6,
        "safety": "darkgreen"
      }
    ],
    "notes": "",
    "label": "",
    "createdAt": 1788540996034,
    "updatedAt": 1789140667630
  },
  {
    "id": "1206fd32-25df-4b10-8b4f-fd7f99afccd9",
    "clubCode": "OHL",
    "opponentCode": "CER",
    "formationKey": "3-5-2",
    "slots": [
      {
        "positionId": "GK",
        "role": "GK",
        "broadPosition": "GK",
        "xPercent": 50,
        "yPercent": 85,
        "playerName": "Van den Heuvel",
        "playerTeamCode": "OHL",
        "playerPosition": "GK",
        "playerPrice": 5,
        "safety": "darkgreen"
      },
      {
        "positionId": "LCB",
        "role": "LCB",
        "broadPosition": "DEF",
        "xPercent": 36,
        "yPercent": 74,
        "playerName": "Lawrence",
        "playerTeamCode": "OHL",
        "playerPosition": "DEF",
        "playerPrice": 5.5,
        "safety": "red"
      },
      {
        "positionId": "CCB",
        "role": "CCB",
        "broadPosition": "DEF",
        "xPercent": 50,
        "yPercent": 76,
        "playerName": "Dussenne",
        "playerTeamCode": "OHL",
        "playerPosition": "DEF",
        "playerPrice": 5,
        "safety": "red"
      },
      {
        "positionId": "RCB",
        "role": "RCB",
        "broadPosition": "DEF",
        "xPercent": 64,
        "yPercent": 74,
        "playerName": "Pletinckx",
        "playerTeamCode": "OHL",
        "playerPosition": "DEF",
        "playerPrice": 5.5,
        "safety": "darkgreen"
      },
      {
        "positionId": "LWB",
        "role": "LWB",
        "broadPosition": "DEF",
        "xPercent": 16,
        "yPercent": 61,
        "playerName": "Ogiwara",
        "playerTeamCode": "OHL",
        "playerPosition": "DEF",
        "playerPrice": 5,
        "safety": "red"
      },
      {
        "positionId": "LCM",
        "role": "LCM",
        "broadPosition": "MID",
        "xPercent": 33,
        "yPercent": 46,
        "playerName": "Schrijvers",
        "playerTeamCode": "OHL",
        "playerPosition": "MID",
        "playerPrice": 8,
        "safety": "darkgreen"
      },
      {
        "positionId": "CAM",
        "role": "CAM",
        "broadPosition": "MID",
        "xPercent": 50,
        "yPercent": 30,
        "playerName": "Balikwisha",
        "playerTeamCode": "OHL",
        "playerPosition": "MID",
        "playerPrice": 7,
        "safety": "red"
      },
      {
        "positionId": "RCM",
        "role": "RCM",
        "broadPosition": "MID",
        "xPercent": 67,
        "yPercent": 46,
        "playerName": "George",
        "playerTeamCode": "OHL",
        "playerPosition": "MID",
        "playerPrice": 4.5,
        "safety": "orange"
      },
      {
        "positionId": "RWB",
        "role": "RWB",
        "broadPosition": "DEF",
        "xPercent": 84,
        "yPercent": 61,
        "playerName": "Gil",
        "playerTeamCode": "OHL",
        "playerPosition": "DEF",
        "playerPrice": 5.5,
        "safety": "darkgreen"
      },
      {
        "positionId": "LST",
        "role": "LST",
        "broadPosition": "FWD",
        "xPercent": 28,
        "yPercent": 15,
        "playerName": "Ikwuemesi",
        "playerTeamCode": "OHL",
        "playerPosition": "FWD",
        "playerPrice": 6.5,
        "safety": "green"
      },
      {
        "positionId": "RST",
        "role": "RST",
        "broadPosition": "FWD",
        "xPercent": 72,
        "yPercent": 15,
        "playerName": "Mirisola",
        "playerTeamCode": "OHL",
        "playerPosition": "FWD",
        "playerPrice": 6,
        "safety": "red"
      }
    ],
    "notes": "",
    "label": "",
    "createdAt": 1788541125570,
    "updatedAt": 1789140698139
  },
  {
    "id": "6e2fceb1-314f-44a1-a527-e87267c0eaa2",
    "clubCode": "KOR",
    "opponentCode": "LLV",
    "formationKey": "5-3-2",
    "slots": [
      {
        "positionId": "GK",
        "role": "GK",
        "broadPosition": "GK",
        "xPercent": 50,
        "yPercent": 85,
        "playerName": "Ilic",
        "playerTeamCode": "KOR",
        "playerPosition": "GK",
        "playerPrice": 6,
        "safety": "darkgreen"
      },
      {
        "positionId": "LWB",
        "role": "LWB",
        "broadPosition": "DEF",
        "xPercent": 16,
        "yPercent": 61,
        "playerName": "Podgoreanu",
        "playerTeamCode": "KOR",
        "playerPosition": "MID",
        "playerPrice": 4.5,
        "safety": "green"
      },
      {
        "positionId": "LCB",
        "role": "LCB",
        "broadPosition": "DEF",
        "xPercent": 36,
        "yPercent": 74,
        "playerName": "Drouhin",
        "playerTeamCode": "KOR",
        "playerPosition": "DEF",
        "playerPrice": 4.5,
        "safety": "green"
      },
      {
        "positionId": "CCB",
        "role": "CCB",
        "broadPosition": "DEF",
        "xPercent": 50,
        "yPercent": 76,
        "playerName": "Ruyssen",
        "playerTeamCode": "KOR",
        "playerPosition": "DEF",
        "playerPrice": 5,
        "safety": "darkgreen"
      },
      {
        "positionId": "RCB",
        "role": "RCB",
        "broadPosition": "DEF",
        "xPercent": 64,
        "yPercent": 74,
        "playerName": "Murray-Campbell",
        "playerTeamCode": "KOR",
        "playerPosition": "DEF",
        "playerPrice": 5.5,
        "safety": "green"
      },
      {
        "positionId": "RWB",
        "role": "RWB",
        "broadPosition": "DEF",
        "xPercent": 84,
        "yPercent": 61,
        "playerName": "Vroninks",
        "playerTeamCode": "KOR",
        "playerPosition": "DEF",
        "playerPrice": 4,
        "safety": "orange"
      },
      {
        "positionId": "LCM",
        "role": "LCM",
        "broadPosition": "MID",
        "xPercent": 33,
        "yPercent": 46,
        "playerName": "Roche",
        "playerTeamCode": "KOR",
        "playerPosition": "MID",
        "playerPrice": 5,
        "safety": "green"
      },
      {
        "positionId": "RW",
        "role": "RW",
        "broadPosition": "FWD",
        "xPercent": 84,
        "yPercent": 21,
        "playerName": "Storman",
        "playerTeamCode": "KOR",
        "playerPosition": "MID",
        "playerPrice": 5,
        "safety": "red"
      },
      {
        "positionId": "RCM",
        "role": "RCM",
        "broadPosition": "MID",
        "xPercent": 67,
        "yPercent": 46,
        "playerName": "Dejaegere",
        "playerTeamCode": "KOR",
        "playerPosition": "MID",
        "playerPrice": 5,
        "safety": "green"
      },
      {
        "positionId": "LW",
        "role": "LW",
        "broadPosition": "FWD",
        "xPercent": 16,
        "yPercent": 21,
        "playerName": "Ambrose",
        "playerTeamCode": "KOR",
        "playerPosition": "FWD",
        "playerPrice": 7,
        "safety": "darkgreen"
      },
      {
        "positionId": "ST",
        "role": "ST",
        "broadPosition": "FWD",
        "xPercent": 50,
        "yPercent": 10,
        "playerName": "Koyalipou",
        "playerTeamCode": "KOR",
        "playerPosition": "FWD",
        "playerPrice": 5.5,
        "safety": "darkgreen"
      },
      {
        "positionId": "_unassigned",
        "role": "MID",
        "broadPosition": "FWD",
        "xPercent": 0,
        "yPercent": 0,
        "playerName": "Podgoreanu",
        "playerTeamCode": "KOR",
        "playerPosition": "MID",
        "playerPrice": 4.5,
        "safety": "red"
      },
      {
        "positionId": "_unassigned",
        "role": "MID",
        "broadPosition": "MID",
        "xPercent": 0,
        "yPercent": 0,
        "playerName": "Podgoreanu",
        "playerTeamCode": "KOR",
        "playerPosition": "MID",
        "playerPrice": 4.5,
        "safety": "darkgreen"
      },
      {
        "positionId": "_unassigned",
        "role": "MID",
        "broadPosition": "MID",
        "xPercent": 0,
        "yPercent": 0,
        "playerName": "Podgoreanu",
        "playerTeamCode": "KOR",
        "playerPosition": "MID",
        "playerPrice": 4.5,
        "safety": "darkgreen"
      }
    ],
    "notes": "",
    "label": "",
    "createdAt": 1788541336245,
    "updatedAt": 1789140489885
  },
  {
    "id": "7c6e2802-7559-418b-9dce-2b6ac02b91f4",
    "clubCode": "USG",
    "opponentCode": "LOM",
    "formationKey": "3-5-2",
    "slots": [
      {
        "positionId": "GK",
        "role": "GK",
        "broadPosition": "GK",
        "xPercent": 50,
        "yPercent": 85,
        "playerName": "Koffi",
        "playerTeamCode": "USG",
        "playerPosition": "GK",
        "playerPrice": 6.5,
        "safety": "darkgreen"
      },
      {
        "positionId": "LCB",
        "role": "LCB",
        "broadPosition": "DEF",
        "xPercent": 36,
        "yPercent": 74,
        "playerName": "Kricfalusi",
        "playerTeamCode": "USG",
        "playerPosition": "MID",
        "playerPrice": 5.5,
        "safety": "orange"
      },
      {
        "positionId": "CCB",
        "role": "CCB",
        "broadPosition": "DEF",
        "xPercent": 50,
        "yPercent": 76,
        "playerName": "Sylla",
        "playerTeamCode": "USG",
        "playerPosition": "DEF",
        "playerPrice": 5,
        "safety": "darkgreen"
      },
      {
        "positionId": "RCB",
        "role": "RCB",
        "broadPosition": "DEF",
        "xPercent": 64,
        "yPercent": 74,
        "playerName": "Mac Allister",
        "playerTeamCode": "USG",
        "playerPosition": "DEF",
        "playerPrice": 8,
        "safety": "darkgreen"
      },
      {
        "positionId": "LWB",
        "role": "LWB",
        "broadPosition": "DEF",
        "xPercent": 16,
        "yPercent": 61,
        "playerName": "Smith",
        "playerTeamCode": "USG",
        "playerPosition": "FWD",
        "playerPrice": 6.5,
        "safety": "darkgreen"
      },
      {
        "positionId": "LCM",
        "role": "LCM",
        "broadPosition": "MID",
        "xPercent": 33,
        "yPercent": 46,
        "playerName": "Van de Perre",
        "playerTeamCode": "USG",
        "playerPosition": "MID",
        "playerPrice": 7,
        "safety": "darkgreen"
      },
      {
        "positionId": "CAM",
        "role": "CAM",
        "broadPosition": "MID",
        "xPercent": 50,
        "yPercent": 30,
        "playerName": "Zeneli",
        "playerTeamCode": "USG",
        "playerPosition": "MID",
        "playerPrice": 6.5,
        "safety": "orange"
      },
      {
        "positionId": "RCM",
        "role": "RCM",
        "broadPosition": "MID",
        "xPercent": 67,
        "yPercent": 46,
        "playerName": "Zorgane",
        "playerTeamCode": "USG",
        "playerPosition": "MID",
        "playerPrice": 9.5,
        "safety": "darkgreen"
      },
      {
        "positionId": "RWB",
        "role": "RWB",
        "broadPosition": "DEF",
        "xPercent": 84,
        "yPercent": 61,
        "playerName": "Patris",
        "playerTeamCode": "USG",
        "playerPosition": "DEF",
        "playerPrice": 6,
        "safety": "orange"
      },
      {
        "positionId": "LST",
        "role": "LST",
        "broadPosition": "FWD",
        "xPercent": 28,
        "yPercent": 15,
        "playerName": "Biondic",
        "playerTeamCode": "USG",
        "playerPosition": "FWD",
        "playerPrice": 6,
        "safety": "red"
      },
      {
        "positionId": "RST",
        "role": "RST",
        "broadPosition": "FWD",
        "xPercent": 72,
        "yPercent": 15,
        "playerName": "Florucz",
        "playerTeamCode": "USG",
        "playerPosition": "MID",
        "playerPrice": 8.5,
        "safety": "orange"
      }
    ],
    "notes": "",
    "label": "",
    "createdAt": 1788541575739,
    "updatedAt": 1789140654373
  },
  {
    "id": "cfeb59e1-1135-4a69-a1b3-a7a9fabae416",
    "clubCode": "BEV",
    "opponentCode": "STV",
    "formationKey": "4-3-3",
    "slots": [
      {
        "positionId": "GK",
        "role": "GK",
        "broadPosition": "GK",
        "xPercent": 50,
        "yPercent": 85,
        "playerName": "Schenk",
        "playerTeamCode": "BEV",
        "playerPosition": "GK",
        "playerPrice": 5,
        "safety": "darkgreen"
      },
      {
        "positionId": "LB",
        "role": "LB",
        "broadPosition": "DEF",
        "xPercent": 16,
        "yPercent": 71,
        "playerName": "Janssens",
        "playerTeamCode": "BEV",
        "playerPosition": "DEF",
        "playerPrice": 5,
        "safety": "green"
      },
      {
        "positionId": "LCB",
        "role": "LCB",
        "broadPosition": "DEF",
        "xPercent": 36,
        "yPercent": 74,
        "playerName": "Godeau",
        "playerTeamCode": "BEV",
        "playerPosition": "DEF",
        "playerPrice": 5.5,
        "safety": "green"
      },
      {
        "positionId": "RCB",
        "role": "RCB",
        "broadPosition": "DEF",
        "xPercent": 64,
        "yPercent": 74,
        "playerName": "Gomis",
        "playerTeamCode": "BEV",
        "playerPosition": "DEF",
        "playerPrice": 4.5,
        "safety": "darkgreen"
      },
      {
        "positionId": "RB",
        "role": "RB",
        "broadPosition": "DEF",
        "xPercent": 84,
        "yPercent": 71,
        "playerName": "Jans",
        "playerTeamCode": "BEV",
        "playerPosition": "DEF",
        "playerPrice": 5,
        "safety": "green"
      },
      {
        "positionId": "LCM",
        "role": "LCM",
        "broadPosition": "MID",
        "xPercent": 33,
        "yPercent": 46,
        "playerName": "Dewaele",
        "playerTeamCode": "BEV",
        "playerPosition": "MID",
        "playerPrice": 5.5,
        "safety": "green"
      },
      {
        "positionId": "CAM",
        "role": "CAM",
        "broadPosition": "MID",
        "xPercent": 50,
        "yPercent": 30,
        "playerName": "Bruls",
        "playerTeamCode": "BEV",
        "playerPosition": "MID",
        "playerPrice": 6.5,
        "safety": "darkgreen"
      },
      {
        "positionId": "RCM",
        "role": "RCM",
        "broadPosition": "MID",
        "xPercent": 67,
        "yPercent": 46,
        "playerName": "Conde",
        "playerTeamCode": "BEV",
        "playerPosition": "MID",
        "playerPrice": 5,
        "safety": "green"
      },
      {
        "positionId": "LW",
        "role": "LW",
        "broadPosition": "FWD",
        "xPercent": 16,
        "yPercent": 21,
        "playerName": "Lokesa",
        "playerTeamCode": "BEV",
        "playerPosition": "MID",
        "playerPrice": 5,
        "safety": "darkgreen"
      },
      {
        "positionId": "ST",
        "role": "ST",
        "broadPosition": "FWD",
        "xPercent": 50,
        "yPercent": 10,
        "playerName": "Kabore",
        "playerTeamCode": "BEV",
        "playerPosition": "FWD",
        "playerPrice": 4.5,
        "safety": "red"
      },
      {
        "positionId": "RW",
        "role": "RW",
        "broadPosition": "FWD",
        "xPercent": 84,
        "yPercent": 21,
        "playerName": "Margaritha",
        "playerTeamCode": "BEV",
        "playerPosition": "MID",
        "playerPrice": 6.5,
        "safety": "darkgreen"
      }
    ],
    "notes": "",
    "label": "",
    "createdAt": 1788541665389,
    "updatedAt": 1789140732182
  },
  {
    "id": "54764440-05a4-46cc-b209-a89e5e06c2ec",
    "clubCode": "GNK",
    "opponentCode": "GNT",
    "formationKey": "4-3-3",
    "slots": [
      {
        "positionId": "GK",
        "role": "GK",
        "broadPosition": "GK",
        "xPercent": 50,
        "yPercent": 85,
        "playerName": "Brughmans",
        "playerTeamCode": "GNK",
        "playerPosition": "GK",
        "playerPrice": 6,
        "safety": "darkgreen"
      },
      {
        "positionId": "LB",
        "role": "LB",
        "broadPosition": "DEF",
        "xPercent": 16,
        "yPercent": 71,
        "playerName": "Kayembe",
        "playerTeamCode": "GNK",
        "playerPosition": "DEF",
        "playerPrice": 7,
        "safety": "darkgreen"
      },
      {
        "positionId": "LCB",
        "role": "LCB",
        "broadPosition": "DEF",
        "xPercent": 36,
        "yPercent": 74,
        "playerName": "Kongolo",
        "playerTeamCode": "GNK",
        "playerPosition": "DEF",
        "playerPrice": 5,
        "safety": "darkgreen"
      },
      {
        "positionId": "RCB",
        "role": "RCB",
        "broadPosition": "DEF",
        "xPercent": 64,
        "yPercent": 74,
        "playerName": "Smets",
        "playerTeamCode": "GNK",
        "playerPosition": "DEF",
        "playerPrice": 7.5,
        "safety": "darkgreen"
      },
      {
        "positionId": "RB",
        "role": "RB",
        "broadPosition": "DEF",
        "xPercent": 84,
        "yPercent": 71,
        "playerName": "Amaro",
        "playerTeamCode": "GNK",
        "playerPosition": "DEF",
        "playerPrice": 5.5,
        "safety": "green"
      },
      {
        "positionId": "LCM",
        "role": "LCM",
        "broadPosition": "MID",
        "xPercent": 33,
        "yPercent": 46,
        "playerName": "Bangoura",
        "playerTeamCode": "GNK",
        "playerPosition": "MID",
        "playerPrice": 6,
        "safety": "green"
      },
      {
        "positionId": "CAM",
        "role": "CAM",
        "broadPosition": "MID",
        "xPercent": 50,
        "yPercent": 30,
        "playerName": "Erenbjerg",
        "playerTeamCode": "GNK",
        "playerPosition": "MID",
        "playerPrice": 8,
        "safety": "green"
      },
      {
        "positionId": "RCM",
        "role": "RCM",
        "broadPosition": "MID",
        "xPercent": 67,
        "yPercent": 46,
        "playerName": "Heynen",
        "playerTeamCode": "GNK",
        "playerPosition": "MID",
        "playerPrice": 8.5,
        "safety": "darkgreen"
      },
      {
        "positionId": "LW",
        "role": "LW",
        "broadPosition": "FWD",
        "xPercent": 16,
        "yPercent": 21,
        "playerName": "Yokoyama",
        "playerTeamCode": "GNK",
        "playerPosition": "MID",
        "playerPrice": 4.5,
        "safety": "red"
      },
      {
        "positionId": "ST",
        "role": "ST",
        "broadPosition": "FWD",
        "xPercent": 50,
        "yPercent": 10,
        "playerName": "Durosinmi",
        "playerTeamCode": "GNK",
        "playerPosition": "FWD",
        "playerPrice": 6.5,
        "safety": "darkgreen"
      },
      {
        "positionId": "RW",
        "role": "RW",
        "broadPosition": "FWD",
        "xPercent": 84,
        "yPercent": 21,
        "playerName": "Ito",
        "playerTeamCode": "GNK",
        "playerPosition": "MID",
        "playerPrice": 7.5,
        "safety": "darkgreen"
      },
      {
        "positionId": "_unassigned",
        "role": "MID",
        "broadPosition": "MID",
        "xPercent": 0,
        "yPercent": 0,
        "playerName": "Ito",
        "playerTeamCode": "GNK",
        "playerPosition": "MID",
        "playerPrice": 7.5,
        "safety": "darkgreen"
      },
      {
        "positionId": "_unassigned",
        "role": "DEF",
        "broadPosition": "DEF",
        "xPercent": 0,
        "yPercent": 0,
        "playerName": "Amaro",
        "playerTeamCode": "GNK",
        "playerPosition": "DEF",
        "playerPrice": 5.5,
        "safety": "darkgreen"
      }
    ],
    "notes": "",
    "label": "",
    "createdAt": 1788541755807,
    "updatedAt": 1789140587064
  },
  {
    "id": "3406b30c-a68b-4110-957e-d28b32ba6273",
    "clubCode": "ZWA",
    "opponentCode": "CHA",
    "formationKey": "4-4-2",
    "slots": [
      {
        "positionId": "GK",
        "role": "GK",
        "broadPosition": "GK",
        "xPercent": 50,
        "yPercent": 85,
        "playerName": "Bostyn",
        "playerTeamCode": "ZWA",
        "playerPosition": "GK",
        "playerPrice": 4.5,
        "safety": "darkgreen"
      },
      {
        "positionId": "LB",
        "role": "LB",
        "broadPosition": "DEF",
        "xPercent": 16,
        "yPercent": 71,
        "playerName": "Cappelle",
        "playerTeamCode": "ZWA",
        "playerPosition": "DEF",
        "playerPrice": 5,
        "safety": "darkgreen"
      },
      {
        "positionId": "LCB",
        "role": "LCB",
        "broadPosition": "DEF",
        "xPercent": 36,
        "yPercent": 74,
        "playerName": "Kiilerich",
        "playerTeamCode": "ZWA",
        "playerPosition": "DEF",
        "playerPrice": 5,
        "safety": "darkgreen"
      },
      {
        "positionId": "RCB",
        "role": "RCB",
        "broadPosition": "DEF",
        "xPercent": 64,
        "yPercent": 74,
        "playerName": "Lemoine",
        "playerTeamCode": "ZWA",
        "playerPosition": "DEF",
        "playerPrice": 5,
        "safety": "darkgreen"
      },
      {
        "positionId": "RB",
        "role": "RB",
        "broadPosition": "DEF",
        "xPercent": 84,
        "yPercent": 71,
        "playerName": "Tangala",
        "playerTeamCode": "ZWA",
        "playerPosition": "MID",
        "playerPrice": 4,
        "safety": "orange"
      },
      {
        "positionId": "LM",
        "role": "LM",
        "broadPosition": "MID",
        "xPercent": 16,
        "yPercent": 46,
        "playerName": "Atrok",
        "playerTeamCode": "ZWA",
        "playerPosition": "MID",
        "playerPrice": 4.5,
        "safety": "red"
      },
      {
        "positionId": "LCM",
        "role": "LCM",
        "broadPosition": "MID",
        "xPercent": 33,
        "yPercent": 46,
        "playerName": "Lofolomo",
        "playerTeamCode": "ZWA",
        "playerPosition": "MID",
        "playerPrice": 5,
        "safety": "darkgreen"
      },
      {
        "positionId": "RCM",
        "role": "RCM",
        "broadPosition": "MID",
        "xPercent": 67,
        "yPercent": 46,
        "playerName": "Claes",
        "playerTeamCode": "ZWA",
        "playerPosition": "MID",
        "playerPrice": 5,
        "safety": "darkgreen"
      },
      {
        "positionId": "RM",
        "role": "RM",
        "broadPosition": "MID",
        "xPercent": 84,
        "yPercent": 46,
        "playerName": "Ake",
        "playerTeamCode": "ZWA",
        "playerPosition": "MID",
        "playerPrice": 5.5,
        "safety": "darkgreen"
      },
      {
        "positionId": "LST",
        "role": "LST",
        "broadPosition": "FWD",
        "xPercent": 28,
        "yPercent": 15,
        "playerName": "Ementa",
        "playerTeamCode": "ZWA",
        "playerPosition": "FWD",
        "playerPrice": 6.5,
        "safety": "darkgreen"
      },
      {
        "positionId": "RST",
        "role": "RST",
        "broadPosition": "FWD",
        "xPercent": 72,
        "yPercent": 15,
        "playerName": "Hedl",
        "playerTeamCode": "ZWA",
        "playerPosition": "FWD",
        "playerPrice": 6,
        "safety": "green"
      },
      {
        "positionId": "_unassigned",
        "role": "FWD",
        "broadPosition": "FWD",
        "xPercent": 0,
        "yPercent": 0,
        "playerName": "Hedl",
        "playerTeamCode": "ZWA",
        "playerPosition": "FWD",
        "playerPrice": 6,
        "safety": "darkgreen"
      }
    ],
    "notes": "",
    "label": "",
    "createdAt": 1788541842926,
    "updatedAt": 1789140541244
  },
  {
    "id": "5a9cfa0d-d913-453c-861a-4ae7c90e6a7a",
    "clubCode": "STA",
    "opponentCode": "WES",
    "formationKey": "4-3-3",
    "slots": [
      {
        "positionId": "GK",
        "role": "GK",
        "broadPosition": "GK",
        "xPercent": 50,
        "yPercent": 85,
        "playerName": "Epolo",
        "playerTeamCode": "STA",
        "playerPosition": "GK",
        "playerPrice": 6,
        "safety": "darkgreen"
      },
      {
        "positionId": "LB",
        "role": "LB",
        "broadPosition": "DEF",
        "xPercent": 16,
        "yPercent": 71,
        "playerName": "Mohr",
        "playerTeamCode": "STA",
        "playerPosition": "MID",
        "playerPrice": 8,
        "safety": "red"
      },
      {
        "positionId": "LCB",
        "role": "LCB",
        "broadPosition": "DEF",
        "xPercent": 36,
        "yPercent": 74,
        "playerName": "Karamoko",
        "playerTeamCode": "STA",
        "playerPosition": "MID",
        "playerPrice": 6.5,
        "safety": "darkgreen"
      },
      {
        "positionId": "RCB",
        "role": "RCB",
        "broadPosition": "DEF",
        "xPercent": 64,
        "yPercent": 74,
        "playerName": "Hautekiet",
        "playerTeamCode": "STA",
        "playerPosition": "DEF",
        "playerPrice": 6,
        "safety": "darkgreen"
      },
      {
        "positionId": "RB",
        "role": "RB",
        "broadPosition": "DEF",
        "xPercent": 84,
        "yPercent": 71,
        "playerName": "Fossey",
        "playerTeamCode": "STA",
        "playerPosition": "DEF",
        "playerPrice": 6.5,
        "safety": "darkgreen"
      },
      {
        "positionId": "LCM",
        "role": "LCM",
        "broadPosition": "MID",
        "xPercent": 33,
        "yPercent": 46,
        "playerName": "Trouillet",
        "playerTeamCode": "STA",
        "playerPosition": "MID",
        "playerPrice": 4.5,
        "safety": "green"
      },
      {
        "positionId": "CM",
        "role": "CM",
        "broadPosition": "MID",
        "xPercent": 50,
        "yPercent": 46,
        "playerName": "Nielsen",
        "playerTeamCode": "STA",
        "playerPosition": "MID",
        "playerPrice": 6,
        "safety": "darkgreen"
      },
      {
        "positionId": "RCM",
        "role": "RCM",
        "broadPosition": "MID",
        "xPercent": 67,
        "yPercent": 46,
        "playerName": "Touzghar",
        "playerTeamCode": "STA",
        "playerPosition": "MID",
        "playerPrice": 5.5,
        "safety": "green"
      },
      {
        "positionId": "LW",
        "role": "LW",
        "broadPosition": "FWD",
        "xPercent": 16,
        "yPercent": 21,
        "playerName": "Abid",
        "playerTeamCode": "STA",
        "playerPosition": "MID",
        "playerPrice": 7,
        "safety": "darkgreen"
      },
      {
        "positionId": "ST",
        "role": "ST",
        "broadPosition": "FWD",
        "xPercent": 50,
        "yPercent": 10,
        "playerName": "Eckert",
        "playerTeamCode": "STA",
        "playerPosition": "FWD",
        "playerPrice": 7.5,
        "safety": "green"
      },
      {
        "positionId": "RW",
        "role": "RW",
        "broadPosition": "FWD",
        "xPercent": 84,
        "yPercent": 21,
        "playerName": "Nguene",
        "playerTeamCode": "STA",
        "playerPosition": "FWD",
        "playerPrice": 5.5,
        "safety": "orange"
      }
    ],
    "notes": "",
    "label": "",
    "createdAt": 1788541960177,
    "updatedAt": 1789140475673
  },
  {
    "id": "48b80a38-6ed3-4860-975b-cfb81e60006f",
    "clubCode": "LLV",
    "opponentCode": "KOR",
    "formationKey": "5-3-2",
    "slots": [
      {
        "positionId": "GK",
        "role": "GK",
        "broadPosition": "GK",
        "xPercent": 50,
        "yPercent": 85,
        "playerName": "Peano",
        "playerTeamCode": "LLV",
        "playerPosition": "GK",
        "playerPrice": 6.5,
        "safety": "darkgreen"
      },
      {
        "positionId": "LWB",
        "role": "LWB",
        "broadPosition": "DEF",
        "xPercent": 16,
        "yPercent": 61,
        "playerName": "Gillot",
        "playerTeamCode": "LLV",
        "playerPosition": "DEF",
        "playerPrice": 4.5,
        "safety": "red"
      },
      {
        "positionId": "LCB",
        "role": "LCB",
        "broadPosition": "DEF",
        "xPercent": 36,
        "yPercent": 74,
        "playerName": "Okou",
        "playerTeamCode": "LLV",
        "playerPosition": "DEF",
        "playerPrice": 5,
        "safety": "green"
      },
      {
        "positionId": "CCB",
        "role": "CCB",
        "broadPosition": "DEF",
        "xPercent": 50,
        "yPercent": 76,
        "playerName": "Nkoa",
        "playerTeamCode": "LLV",
        "playerPosition": "DEF",
        "playerPrice": 4.5,
        "safety": "green"
      },
      {
        "positionId": "RCB",
        "role": "RCB",
        "broadPosition": "DEF",
        "xPercent": 64,
        "yPercent": 74,
        "playerName": "Faye",
        "playerTeamCode": "LLV",
        "playerPosition": "DEF",
        "playerPrice": 5.5,
        "safety": "red"
      },
      {
        "positionId": "RWB",
        "role": "RWB",
        "broadPosition": "DEF",
        "xPercent": 84,
        "yPercent": 61,
        "playerName": "Delos",
        "playerTeamCode": "LLV",
        "playerPosition": "DEF",
        "playerPrice": 5,
        "safety": "orange"
      },
      {
        "positionId": "LCM",
        "role": "LCM",
        "broadPosition": "MID",
        "xPercent": 33,
        "yPercent": 46,
        "playerName": "Coulibaly",
        "playerTeamCode": "LLV",
        "playerPosition": "MID",
        "playerPrice": 5,
        "safety": "green"
      },
      {
        "positionId": "CAM",
        "role": "CAM",
        "broadPosition": "MID",
        "xPercent": 50,
        "yPercent": 30,
        "playerName": "Gruber",
        "playerTeamCode": "LLV",
        "playerPosition": "AAN",
        "playerPrice": 4,
        "safety": "orange"
      },
      {
        "positionId": "RCM",
        "role": "RCM",
        "broadPosition": "MID",
        "xPercent": 67,
        "yPercent": 46,
        "playerName": "Courcoul",
        "playerTeamCode": "LLV",
        "playerPosition": "MID",
        "playerPrice": 4.5,
        "safety": "orange"
      },
      {
        "positionId": "LST",
        "role": "LST",
        "broadPosition": "FWD",
        "xPercent": 28,
        "yPercent": 15,
        "playerName": "Filet",
        "playerTeamCode": "LLV",
        "playerPosition": "FWD",
        "playerPrice": 5.5,
        "safety": "red"
      },
      {
        "positionId": "RST",
        "role": "RST",
        "broadPosition": "FWD",
        "xPercent": 72,
        "yPercent": 15,
        "playerName": "Isah",
        "playerTeamCode": "LLV",
        "playerPosition": "FWD",
        "playerPrice": 4.5,
        "safety": "darkgreen"
      }
    ],
    "notes": "",
    "label": "",
    "createdAt": 1788542048715,
    "updatedAt": 1789140510821
  },
  {
    "id": "53d555d6-20c7-4bc0-9d5f-6f2c66a9ad1c",
    "clubCode": "KVM",
    "opponentCode": "AND",
    "formationKey": "5-3-2",
    "slots": [
      {
        "positionId": "GK",
        "role": "GK",
        "broadPosition": "GK",
        "xPercent": 50,
        "yPercent": 85,
        "playerName": "Miras",
        "playerTeamCode": "KVM",
        "playerPosition": "GK",
        "playerPrice": 6.5,
        "safety": "darkgreen"
      },
      {
        "positionId": "LWB",
        "role": "LWB",
        "broadPosition": "DEF",
        "xPercent": 16,
        "yPercent": 61,
        "playerName": "Van Meirvenne",
        "playerTeamCode": "KVM",
        "playerPosition": "MID",
        "playerPrice": 5,
        "safety": "red"
      },
      {
        "positionId": "LCB",
        "role": "LCB",
        "broadPosition": "DEF",
        "xPercent": 36,
        "yPercent": 74,
        "playerName": "Marsa",
        "playerTeamCode": "KVM",
        "playerPosition": "DEF",
        "playerPrice": 5.5,
        "safety": "darkgreen"
      },
      {
        "positionId": "CCB",
        "role": "CCB",
        "broadPosition": "DEF",
        "xPercent": 50,
        "yPercent": 76,
        "playerName": "Eerdhuijzen",
        "playerTeamCode": "KVM",
        "playerPosition": "DEF",
        "playerPrice": 5,
        "safety": "darkgreen"
      },
      {
        "positionId": "RCB",
        "role": "RCB",
        "broadPosition": "DEF",
        "xPercent": 64,
        "yPercent": 74,
        "playerName": "Marijnissen",
        "playerTeamCode": "KVM",
        "playerPosition": "DEF",
        "playerPrice": 5,
        "safety": "darkgreen"
      },
      {
        "positionId": "RWB",
        "role": "RWB",
        "broadPosition": "DEF",
        "xPercent": 84,
        "yPercent": 61,
        "playerName": "Koudou",
        "playerTeamCode": "KVM",
        "playerPosition": "DEF",
        "playerPrice": 6,
        "safety": "darkgreen"
      },
      {
        "positionId": "LCM",
        "role": "LCM",
        "broadPosition": "MID",
        "xPercent": 33,
        "yPercent": 46,
        "playerName": "Hammar",
        "playerTeamCode": "KVM",
        "playerPosition": "MID",
        "playerPrice": 7,
        "safety": "green"
      },
      {
        "positionId": "CAM",
        "role": "CAM",
        "broadPosition": "MID",
        "xPercent": 50,
        "yPercent": 30,
        "playerName": "Van Brederode",
        "playerTeamCode": "KVM",
        "playerPosition": "FWD",
        "playerPrice": 7,
        "safety": "darkgreen"
      },
      {
        "positionId": "RCM",
        "role": "RCM",
        "broadPosition": "MID",
        "xPercent": 67,
        "yPercent": 46,
        "playerName": "Praet",
        "playerTeamCode": "KVM",
        "playerPosition": "MID",
        "playerPrice": 7,
        "safety": "darkgreen"
      },
      {
        "positionId": "LST",
        "role": "LST",
        "broadPosition": "FWD",
        "xPercent": 28,
        "yPercent": 15,
        "playerName": "Mbasi",
        "playerTeamCode": "KVM",
        "playerPosition": "FWD",
        "playerPrice": 4,
        "safety": "red"
      },
      {
        "positionId": "RST",
        "role": "RST",
        "broadPosition": "FWD",
        "xPercent": 72,
        "yPercent": 15,
        "playerName": "Boersma",
        "playerTeamCode": "KVM",
        "playerPosition": "FWD",
        "playerPrice": 6.5,
        "safety": "green"
      },
      {
        "positionId": "_unassigned",
        "role": "MID",
        "broadPosition": "MID",
        "xPercent": 0,
        "yPercent": 0,
        "playerName": "Vanrafelghem",
        "playerTeamCode": "KVM",
        "playerPosition": "MID",
        "playerPrice": 6,
        "safety": "darkgreen"
      }
    ],
    "notes": "",
    "label": "",
    "createdAt": 1788542140161,
    "updatedAt": 1789140447791
  },
  {
    "id": "1b24ca8c-01a0-457c-a777-5e9c80ccdb78",
    "clubCode": "CLU",
    "opponentCode": "ANT",
    "formationKey": "4-3-3",
    "slots": [
      {
        "positionId": "GK",
        "role": "GK",
        "broadPosition": "GK",
        "xPercent": 50,
        "yPercent": 85,
        "playerName": "Sommer",
        "playerTeamCode": "CLU",
        "playerPosition": "GK",
        "playerPrice": 8,
        "safety": "darkgreen"
      },
      {
        "positionId": "LB",
        "role": "LB",
        "broadPosition": "DEF",
        "xPercent": 16,
        "yPercent": 71,
        "playerName": "Seys",
        "playerTeamCode": "CLU",
        "playerPosition": "DEF",
        "playerPrice": 7,
        "safety": "darkgreen"
      },
      {
        "positionId": "LCB",
        "role": "LCB",
        "broadPosition": "DEF",
        "xPercent": 36,
        "yPercent": 74,
        "playerName": "Mechele",
        "playerTeamCode": "CLU",
        "playerPosition": "DEF",
        "playerPrice": 8,
        "safety": "darkgreen"
      },
      {
        "positionId": "RCB",
        "role": "RCB",
        "broadPosition": "DEF",
        "xPercent": 64,
        "yPercent": 74,
        "playerName": "Lee",
        "playerTeamCode": "CLU",
        "playerPosition": "DEF",
        "playerPrice": 6.5,
        "safety": "darkgreen"
      },
      {
        "positionId": "RB",
        "role": "RB",
        "broadPosition": "DEF",
        "xPercent": 84,
        "yPercent": 71,
        "playerName": "Siquet",
        "playerTeamCode": "CLU",
        "playerPosition": "DEF",
        "playerPrice": 6,
        "safety": "darkgreen"
      },
      {
        "positionId": "LCM",
        "role": "LCM",
        "broadPosition": "MID",
        "xPercent": 33,
        "yPercent": 46,
        "playerName": "Vetlesen",
        "playerTeamCode": "CLU",
        "playerPosition": "MID",
        "playerPrice": 7,
        "safety": "darkgreen"
      },
      {
        "positionId": "CAM",
        "role": "CAM",
        "broadPosition": "MID",
        "xPercent": 50,
        "yPercent": 30,
        "playerName": "Lemarechal",
        "playerTeamCode": "CLU",
        "playerPosition": "MID",
        "playerPrice": 6.5,
        "safety": "red"
      },
      {
        "positionId": "RCM",
        "role": "RCM",
        "broadPosition": "MID",
        "xPercent": 67,
        "yPercent": 46,
        "playerName": "Potts",
        "playerTeamCode": "CLU",
        "playerPosition": "MID",
        "playerPrice": 7,
        "safety": "green"
      },
      {
        "positionId": "LW",
        "role": "LW",
        "broadPosition": "FWD",
        "xPercent": 16,
        "yPercent": 21,
        "playerName": "Virgili",
        "playerTeamCode": "CLU",
        "playerPosition": "MID",
        "playerPrice": 5.5,
        "safety": "orange"
      },
      {
        "positionId": "ST",
        "role": "ST",
        "broadPosition": "FWD",
        "xPercent": 50,
        "yPercent": 10,
        "playerName": "Tresoldi",
        "playerTeamCode": "CLU",
        "playerPosition": "FWD",
        "playerPrice": 10.5,
        "safety": "darkgreen"
      },
      {
        "positionId": "RW",
        "role": "RW",
        "broadPosition": "FWD",
        "xPercent": 84,
        "yPercent": 21,
        "playerName": "Forbs",
        "playerTeamCode": "CLU",
        "playerPosition": "MID",
        "playerPrice": 8,
        "safety": "darkgreen"
      },
      {
        "positionId": "_unassigned",
        "role": "DEF",
        "broadPosition": "DEF",
        "xPercent": 0,
        "yPercent": 0,
        "playerName": "Sabbe",
        "playerTeamCode": "CLU",
        "playerPosition": "DEF",
        "playerPrice": 6.5,
        "safety": "darkgreen"
      }
    ],
    "notes": "",
    "label": "",
    "createdAt": 1788542226817,
    "updatedAt": 1789140612678
  }
];
