// Vaste data voor de publieke "Predicted Lineups"-tab (zie src/tabs/PredictedLineupsTab.jsx) — zelfde
// conventie als TEAMS/FIXTURES in constants.js: gewoon een statische constante, geen fetch, geen
// bewerkbare state.
//
// Elke entry heeft grotendeels dezelfde vorm als een record uit de privé Predicted XI Builder's
// opgeslagen lineups (zie loadStoredDrafts()/sanitizeDraft() in src/predicted-xi/storage.js): clubCode,
// opponentCode, formationKey, slots (met per slot playerName/playerTeamCode/playerPosition/
// playerPrice/safety/positionId/xPercent/yPercent), notes.
//
// Volledig vervangen (niet aangevuld) telkens een nieuwe export van de privé-tool binnenkomt — zie
// PREDICTED_LINEUPS_GW in constants.js voor de speeldag waarvoor DEZE data geldt. Bewust een volledige
// vervanging i.p.v. een aanvulling: een eerdere aanvul-aanpak liet oude en nieuwe entries voor dezelfde
// club naast elkaar in de array staan, wat zowel een kapotte JSON-naad als een stille "oude opstelling
// getoond als actueel"-bug opleverde (zie de commit-geschiedenis). Alle 18 clubs aangeleverd 9
// oktober 2026 (GW8).
export const PREDICTED_LINEUPS = [
  {
    "id": "61120f80-0439-4dc9-b409-6627ed6dfc59",
    "clubCode": "CER",
    "opponentCode": "AND",
    "formationKey": "3-4-3",
    "slots": [
      {
        "positionId": "GK",
        "role": "GK",
        "broadPosition": "GK",
        "xPercent": 50,
        "yPercent": 85,
        "playerName": "Coucke",
        "playerTeamCode": "CER",
        "playerPosition": "GK",
        "playerPrice": 5.5,
        "safety": "darkgreen"
      },
      {
        "positionId": "LCB",
        "role": "LCB",
        "broadPosition": "DEF",
        "xPercent": 36,
        "yPercent": 74,
        "playerName": "Kondo",
        "playerTeamCode": "CER",
        "playerPosition": "DEF",
        "playerPrice": 5,
        "safety": "darkgreen"
      },
      {
        "positionId": "CCB",
        "role": "CCB",
        "broadPosition": "DEF",
        "xPercent": 50,
        "yPercent": 76,
        "playerName": "Lincoln",
        "playerTeamCode": "CER",
        "playerPosition": "DEF",
        "playerPrice": 4.5,
        "safety": "red"
      },
      {
        "positionId": "RCB",
        "role": "RCB",
        "broadPosition": "DEF",
        "xPercent": 64,
        "yPercent": 74,
        "playerName": "Diakite",
        "playerTeamCode": "CER",
        "playerPosition": "DEF",
        "playerPrice": 5,
        "safety": "red"
      },
      {
        "positionId": "LM",
        "role": "LM",
        "broadPosition": "MID",
        "xPercent": 16,
        "yPercent": 46,
        "playerName": "Konate",
        "playerTeamCode": "CER",
        "playerPosition": "DEF",
        "playerPrice": 4.5,
        "safety": "darkgreen"
      },
      {
        "positionId": "LCM",
        "role": "LCM",
        "broadPosition": "MID",
        "xPercent": 33,
        "yPercent": 46,
        "playerName": "Mondele",
        "playerTeamCode": "CER",
        "playerPosition": "MID",
        "playerPrice": 4,
        "safety": "orange"
      },
      {
        "positionId": "RCM",
        "role": "RCM",
        "broadPosition": "MID",
        "xPercent": 67,
        "yPercent": 46,
        "playerName": "Van der Bruggen",
        "playerTeamCode": "CER",
        "playerPosition": "MID",
        "playerPrice": 7,
        "safety": "orange"
      },
      {
        "positionId": "RM",
        "role": "RM",
        "broadPosition": "MID",
        "xPercent": 84,
        "yPercent": 46,
        "playerName": "Magnee",
        "playerTeamCode": "CER",
        "playerPosition": "DEF",
        "playerPrice": 6.5,
        "safety": "darkgreen"
      },
      {
        "positionId": "LW",
        "role": "LW",
        "broadPosition": "FWD",
        "xPercent": 16,
        "yPercent": 21,
        "playerName": "Martens",
        "playerTeamCode": "CER",
        "playerPosition": "MID",
        "playerPrice": 4,
        "safety": "red"
      },
      {
        "positionId": "ST",
        "role": "ST",
        "broadPosition": "FWD",
        "xPercent": 50,
        "yPercent": 10,
        "playerName": "Ngoura",
        "playerTeamCode": "CER",
        "playerPosition": "FWD",
        "playerPrice": 6.5,
        "safety": "darkgreen"
      },
      {
        "positionId": "RW",
        "role": "RW",
        "broadPosition": "FWD",
        "xPercent": 84,
        "yPercent": 21,
        "playerName": "Vanzeir",
        "playerTeamCode": "CER",
        "playerPosition": "FWD",
        "playerPrice": 7,
        "safety": "red"
      }
    ],
    "notes": "",
    "label": "",
    "createdAt": 1791548070909,
    "updatedAt": 1791557548148
  },
  {
    "id": "04de0be9-6e1c-406e-9d83-b9aabbeb6a6d",
    "clubCode": "AND",
    "opponentCode": "CER",
    "formationKey": "4-4-2",
    "slots": [
      {
        "positionId": "GK",
        "role": "GK",
        "broadPosition": "GK",
        "xPercent": 50,
        "yPercent": 85,
        "playerName": "Coosemans",
        "playerTeamCode": "AND",
        "playerPosition": "GK",
        "playerPrice": 6.5,
        "safety": "darkgreen"
      },
      {
        "positionId": "LB",
        "role": "LB",
        "broadPosition": "DEF",
        "xPercent": 16,
        "yPercent": 71,
        "playerName": "Augustinsson",
        "playerTeamCode": "AND",
        "playerPosition": "DEF",
        "playerPrice": 6,
        "safety": "darkgreen"
      },
      {
        "positionId": "LCB",
        "role": "LCB",
        "broadPosition": "DEF",
        "xPercent": 36,
        "yPercent": 74,
        "playerName": "Petrot",
        "playerTeamCode": "AND",
        "playerPosition": "DEF",
        "playerPrice": 6,
        "safety": "darkgreen"
      },
      {
        "positionId": "RCB",
        "role": "RCB",
        "broadPosition": "DEF",
        "xPercent": 64,
        "yPercent": 74,
        "playerName": "Omobamidele",
        "playerTeamCode": "AND",
        "playerPosition": "DEF",
        "playerPrice": 5.5,
        "safety": "red"
      },
      {
        "positionId": "RB",
        "role": "RB",
        "broadPosition": "DEF",
        "xPercent": 84,
        "yPercent": 71,
        "playerName": "Maamar",
        "playerTeamCode": "AND",
        "playerPosition": "DEF",
        "playerPrice": 5,
        "safety": "red"
      },
      {
        "positionId": "LM",
        "role": "LM",
        "broadPosition": "MID",
        "xPercent": 16,
        "yPercent": 46,
        "playerName": "Winkler",
        "playerTeamCode": "AND",
        "playerPosition": "MID",
        "playerPrice": 6.5,
        "safety": "green"
      },
      {
        "positionId": "LCM",
        "role": "LCM",
        "broadPosition": "MID",
        "xPercent": 33,
        "yPercent": 46,
        "playerName": "Koutsoupias",
        "playerTeamCode": "AND",
        "playerPosition": "MID",
        "playerPrice": 7,
        "safety": "green"
      },
      {
        "positionId": "RCM",
        "role": "RCM",
        "broadPosition": "MID",
        "xPercent": 67,
        "yPercent": 46,
        "playerName": "Kana",
        "playerTeamCode": "AND",
        "playerPosition": "MID",
        "playerPrice": 5.5,
        "safety": "green"
      },
      {
        "positionId": "RM",
        "role": "RM",
        "broadPosition": "MID",
        "xPercent": 84,
        "yPercent": 46,
        "playerName": "Ambros",
        "playerTeamCode": "AND",
        "playerPosition": "MID",
        "playerPrice": 6,
        "safety": "orange"
      },
      {
        "positionId": "LST",
        "role": "LST",
        "broadPosition": "FWD",
        "xPercent": 28,
        "yPercent": 15,
        "playerName": "Sikan",
        "playerTeamCode": "AND",
        "playerPosition": "FWD",
        "playerPrice": 6.5,
        "safety": "green"
      },
      {
        "positionId": "RST",
        "role": "RST",
        "broadPosition": "FWD",
        "xPercent": 72,
        "yPercent": 15,
        "playerName": "Bentayeb",
        "playerTeamCode": "AND",
        "playerPosition": "FWD",
        "playerPrice": 6,
        "safety": "red"
      }
    ],
    "notes": "",
    "label": "",
    "createdAt": 1791548070909,
    "updatedAt": 1791557557249
  },
  {
    "id": "da47530c-8968-4a7e-9fb8-07f7d53c803a",
    "clubCode": "LLV",
    "opponentCode": "CLU",
    "formationKey": "3-5-2",
    "slots": [
      {
        "positionId": "GK",
        "role": "GK",
        "broadPosition": "GK",
        "xPercent": 50,
        "yPercent": 85,
        "playerName": "Peano",
        "playerTeamCode": "LLV",
        "playerPosition": "GK",
        "playerPrice": 6.5,
        "safety": "darkgreen"
      },
      {
        "positionId": "LCB",
        "role": "LCB",
        "broadPosition": "DEF",
        "xPercent": 36,
        "yPercent": 74,
        "playerName": "Okou",
        "playerTeamCode": "LLV",
        "playerPosition": "DEF",
        "playerPrice": 5,
        "safety": "darkgreen"
      },
      {
        "positionId": "CCB",
        "role": "CCB",
        "broadPosition": "DEF",
        "xPercent": 50,
        "yPercent": 76,
        "playerName": "Faye",
        "playerTeamCode": "LLV",
        "playerPosition": "DEF",
        "playerPrice": 5.5,
        "safety": "green"
      },
      {
        "positionId": "RCB",
        "role": "RCB",
        "broadPosition": "DEF",
        "xPercent": 64,
        "yPercent": 74,
        "playerName": "Nkoa",
        "playerTeamCode": "LLV",
        "playerPosition": "DEF",
        "playerPrice": 4.5,
        "safety": "green"
      },
      {
        "positionId": "LWB",
        "role": "LWB",
        "broadPosition": "DEF",
        "xPercent": 16,
        "yPercent": 61,
        "playerName": "Lutonda",
        "playerTeamCode": "LLV",
        "playerPosition": "DEF",
        "playerPrice": 5,
        "safety": "red"
      },
      {
        "positionId": "LCM",
        "role": "LCM",
        "broadPosition": "MID",
        "xPercent": 33,
        "yPercent": 46,
        "playerName": "Coulibaly",
        "playerTeamCode": "LLV",
        "playerPosition": "MID",
        "playerPrice": 5,
        "safety": "darkgreen"
      },
      {
        "positionId": "CM",
        "role": "CM",
        "broadPosition": "MID",
        "xPercent": 50,
        "yPercent": 46,
        "playerName": "Courcoul",
        "playerTeamCode": "LLV",
        "playerPosition": "MID",
        "playerPrice": 4.5,
        "safety": "orange"
      },
      {
        "positionId": "RCM",
        "role": "RCM",
        "broadPosition": "MID",
        "xPercent": 67,
        "yPercent": 46,
        "playerName": "Tajaouart",
        "playerTeamCode": "LLV",
        "playerPosition": "MID",
        "playerPrice": 5,
        "safety": "orange"
      },
      {
        "positionId": "RWB",
        "role": "RWB",
        "broadPosition": "DEF",
        "xPercent": 84,
        "yPercent": 61,
        "playerName": "Delos",
        "playerTeamCode": "LLV",
        "playerPosition": "DEF",
        "playerPrice": 5,
        "safety": "darkgreen"
      },
      {
        "positionId": "LST",
        "role": "LST",
        "broadPosition": "FWD",
        "xPercent": 28,
        "yPercent": 15,
        "playerName": "Isah",
        "playerTeamCode": "LLV",
        "playerPosition": "FWD",
        "playerPrice": 4.5,
        "safety": "darkgreen"
      },
      {
        "positionId": "RST",
        "role": "RST",
        "broadPosition": "FWD",
        "xPercent": 72,
        "yPercent": 15,
        "playerName": "Gruber",
        "playerTeamCode": "LLV",
        "playerPosition": "FWD",
        "playerPrice": 4,
        "safety": "red"
      }
    ],
    "notes": "",
    "label": "",
    "createdAt": 1791548070909,
    "updatedAt": 1791557483490
  },
  {
    "id": "d0562f4d-c224-42cc-9481-9885ed7c6db9",
    "clubCode": "CLU",
    "opponentCode": "LLV",
    "formationKey": "4-3-3",
    "slots": [
      {
        "positionId": "GK",
        "role": "GK",
        "broadPosition": "GK",
        "xPercent": 50,
        "yPercent": 85,
        "playerName": "Sommer",
        "playerTeamCode": "CLU",
        "playerPosition": "GK",
        "playerPrice": 8,
        "safety": "darkgreen"
      },
      {
        "positionId": "LB",
        "role": "LB",
        "broadPosition": "DEF",
        "xPercent": 16,
        "yPercent": 71,
        "playerName": "Seys",
        "playerTeamCode": "CLU",
        "playerPosition": "DEF",
        "playerPrice": 7,
        "safety": "darkgreen"
      },
      {
        "positionId": "LCB",
        "role": "LCB",
        "broadPosition": "DEF",
        "xPercent": 36,
        "yPercent": 74,
        "playerName": "Mechele",
        "playerTeamCode": "CLU",
        "playerPosition": "DEF",
        "playerPrice": 8,
        "safety": "darkgreen"
      },
      {
        "positionId": "RCB",
        "role": "RCB",
        "broadPosition": "DEF",
        "xPercent": 64,
        "yPercent": 74,
        "playerName": "Lee",
        "playerTeamCode": "CLU",
        "playerPosition": "DEF",
        "playerPrice": 6.5,
        "safety": "darkgreen"
      },
      {
        "positionId": "RB",
        "role": "RB",
        "broadPosition": "DEF",
        "xPercent": 84,
        "yPercent": 71,
        "playerName": "Sabbe",
        "playerTeamCode": "CLU",
        "playerPosition": "DEF",
        "playerPrice": 6.5,
        "safety": "darkgreen"
      },
      {
        "positionId": "LCM",
        "role": "LCM",
        "broadPosition": "MID",
        "xPercent": 33,
        "yPercent": 46,
        "playerName": "Vanaken",
        "playerTeamCode": "CLU",
        "playerPosition": "MID",
        "playerPrice": 11.5,
        "safety": "darkgreen"
      },
      {
        "positionId": "CAM",
        "role": "CAM",
        "broadPosition": "MID",
        "xPercent": 50,
        "yPercent": 30,
        "playerName": "Vetlesen",
        "playerTeamCode": "CLU",
        "playerPosition": "MID",
        "playerPrice": 7,
        "safety": "green"
      },
      {
        "positionId": "RCM",
        "role": "RCM",
        "broadPosition": "MID",
        "xPercent": 67,
        "yPercent": 46,
        "playerName": "Potts",
        "playerTeamCode": "CLU",
        "playerPosition": "MID",
        "playerPrice": 7,
        "safety": "darkgreen"
      },
      {
        "positionId": "LW",
        "role": "LW",
        "broadPosition": "FWD",
        "xPercent": 16,
        "yPercent": 21,
        "playerName": "Virgili",
        "playerTeamCode": "CLU",
        "playerPosition": "MID",
        "playerPrice": 5.5,
        "safety": "green"
      },
      {
        "positionId": "ST",
        "role": "ST",
        "broadPosition": "FWD",
        "xPercent": 50,
        "yPercent": 10,
        "playerName": "Tresoldi",
        "playerTeamCode": "CLU",
        "playerPosition": "FWD",
        "playerPrice": 10.5,
        "safety": "darkgreen"
      },
      {
        "positionId": "RW",
        "role": "RW",
        "broadPosition": "FWD",
        "xPercent": 84,
        "yPercent": 21,
        "playerName": "Forbs",
        "playerTeamCode": "CLU",
        "playerPosition": "MID",
        "playerPrice": 8,
        "safety": "darkgreen"
      }
    ],
    "notes": "",
    "label": "",
    "createdAt": 1791548070910,
    "updatedAt": 1791557539519
  },
  {
    "id": "01d54b00-e4a4-47d4-84c4-6ad525313cbb",
    "clubCode": "GNK",
    "opponentCode": "KOR",
    "formationKey": "4-3-3",
    "slots": [
      {
        "positionId": "GK",
        "role": "GK",
        "broadPosition": "GK",
        "xPercent": 50,
        "yPercent": 85,
        "playerName": "Brughmans",
        "playerTeamCode": "GNK",
        "playerPosition": "GK",
        "playerPrice": 6,
        "safety": "darkgreen"
      },
      {
        "positionId": "LB",
        "role": "LB",
        "broadPosition": "DEF",
        "xPercent": 16,
        "yPercent": 71,
        "playerName": "Kayembe",
        "playerTeamCode": "GNK",
        "playerPosition": "DEF",
        "playerPrice": 7,
        "safety": "darkgreen"
      },
      {
        "positionId": "LCB",
        "role": "LCB",
        "broadPosition": "DEF",
        "xPercent": 36,
        "yPercent": 74,
        "playerName": "Kongolo",
        "playerTeamCode": "GNK",
        "playerPosition": "DEF",
        "playerPrice": 5,
        "safety": "darkgreen"
      },
      {
        "positionId": "RCB",
        "role": "RCB",
        "broadPosition": "DEF",
        "xPercent": 64,
        "yPercent": 74,
        "playerName": "Smets",
        "playerTeamCode": "GNK",
        "playerPosition": "DEF",
        "playerPrice": 7.5,
        "safety": "darkgreen"
      },
      {
        "positionId": "RB",
        "role": "RB",
        "broadPosition": "DEF",
        "xPercent": 84,
        "yPercent": 71,
        "playerName": "Amaro",
        "playerTeamCode": "GNK",
        "playerPosition": "DEF",
        "playerPrice": 5.5,
        "safety": "darkgreen"
      },
      {
        "positionId": "LCM",
        "role": "LCM",
        "broadPosition": "MID",
        "xPercent": 33,
        "yPercent": 46,
        "playerName": "Tahirovic",
        "playerTeamCode": "GNK",
        "playerPosition": "MID",
        "playerPrice": 6,
        "safety": "red"
      },
      {
        "positionId": "CAM",
        "role": "CAM",
        "broadPosition": "MID",
        "xPercent": 50,
        "yPercent": 30,
        "playerName": "Erenbjerg",
        "playerTeamCode": "GNK",
        "playerPosition": "MID",
        "playerPrice": 8,
        "safety": "green"
      },
      {
        "positionId": "RCM",
        "role": "RCM",
        "broadPosition": "MID",
        "xPercent": 67,
        "yPercent": 46,
        "playerName": "Heynen",
        "playerTeamCode": "GNK",
        "playerPosition": "MID",
        "playerPrice": 8.5,
        "safety": "darkgreen"
      },
      {
        "positionId": "LW",
        "role": "LW",
        "broadPosition": "FWD",
        "xPercent": 16,
        "yPercent": 21,
        "playerName": "Ito",
        "playerTeamCode": "GNK",
        "playerPosition": "MID",
        "playerPrice": 7.5,
        "safety": "darkgreen"
      },
      {
        "positionId": "ST",
        "role": "ST",
        "broadPosition": "FWD",
        "xPercent": 50,
        "yPercent": 10,
        "playerName": "Durosinmi",
        "playerTeamCode": "GNK",
        "playerPosition": "FWD",
        "playerPrice": 6.5,
        "safety": "darkgreen"
      },
      {
        "positionId": "RW",
        "role": "RW",
        "broadPosition": "FWD",
        "xPercent": 84,
        "yPercent": 21,
        "playerName": "Adedeji-Sternberg",
        "playerTeamCode": "GNK",
        "playerPosition": "MID",
        "playerPrice": 7.5,
        "safety": "red"
      }
    ],
    "notes": "",
    "label": "",
    "createdAt": 1791548070910,
    "updatedAt": 1791557524048
  },
  {
    "id": "11926438-9e15-4c5b-9dd2-33d1b0623a5c",
    "clubCode": "KOR",
    "opponentCode": "GNK",
    "formationKey": "4-4-2",
    "slots": [
      {
        "positionId": "GK",
        "role": "GK",
        "broadPosition": "GK",
        "xPercent": 50,
        "yPercent": 85,
        "playerName": "Ilic",
        "playerTeamCode": "KOR",
        "playerPosition": "GK",
        "playerPrice": 6,
        "safety": "darkgreen"
      },
      {
        "positionId": "LB",
        "role": "LB",
        "broadPosition": "DEF",
        "xPercent": 16,
        "yPercent": 71,
        "playerName": "Andersson",
        "playerTeamCode": "KOR",
        "playerPosition": "DEF",
        "playerPrice": 5,
        "safety": "red"
      },
      {
        "positionId": "LCB",
        "role": "LCB",
        "broadPosition": "DEF",
        "xPercent": 36,
        "yPercent": 74,
        "playerName": "Drouhin",
        "playerTeamCode": "KOR",
        "playerPosition": "DEF",
        "playerPrice": 4.5,
        "safety": "orange"
      },
      {
        "positionId": "RCB",
        "role": "RCB",
        "broadPosition": "DEF",
        "xPercent": 64,
        "yPercent": 74,
        "playerName": "Ruyssen",
        "playerTeamCode": "KOR",
        "playerPosition": "DEF",
        "playerPrice": 5,
        "safety": "orange"
      },
      {
        "positionId": "RB",
        "role": "RB",
        "broadPosition": "DEF",
        "xPercent": 84,
        "yPercent": 71,
        "playerName": "Kohon",
        "playerTeamCode": "KOR",
        "playerPosition": "DEF",
        "playerPrice": 4.5,
        "safety": "darkgreen"
      },
      {
        "positionId": "LM",
        "role": "LM",
        "broadPosition": "MID",
        "xPercent": 16,
        "yPercent": 46,
        "playerName": "Van Landschoot",
        "playerTeamCode": "KOR",
        "playerPosition": "MID",
        "playerPrice": 5.5,
        "safety": "orange"
      },
      {
        "positionId": "LCM",
        "role": "LCM",
        "broadPosition": "MID",
        "xPercent": 33,
        "yPercent": 46,
        "playerName": "Storman",
        "playerTeamCode": "KOR",
        "playerPosition": "MID",
        "playerPrice": 5,
        "safety": "green"
      },
      {
        "positionId": "RCM",
        "role": "RCM",
        "broadPosition": "MID",
        "xPercent": 67,
        "yPercent": 46,
        "playerName": "Dejaegere",
        "playerTeamCode": "KOR",
        "playerPosition": "MID",
        "playerPrice": 5,
        "safety": "darkgreen"
      },
      {
        "positionId": "RM",
        "role": "RM",
        "broadPosition": "MID",
        "xPercent": 84,
        "yPercent": 46,
        "playerName": "Campbell",
        "playerTeamCode": "KOR",
        "playerPosition": "MID",
        "playerPrice": 6,
        "safety": "red"
      },
      {
        "positionId": "LST",
        "role": "LST",
        "broadPosition": "FWD",
        "xPercent": 28,
        "yPercent": 15,
        "playerName": "Ambrose",
        "playerTeamCode": "KOR",
        "playerPosition": "FWD",
        "playerPrice": 7,
        "safety": "darkgreen"
      },
      {
        "positionId": "RST",
        "role": "RST",
        "broadPosition": "FWD",
        "xPercent": 72,
        "yPercent": 15,
        "playerName": "Koyalipou",
        "playerTeamCode": "KOR",
        "playerPosition": "FWD",
        "playerPrice": 5.5,
        "safety": "red"
      }
    ],
    "notes": "",
    "label": "",
    "createdAt": 1791548070910,
    "updatedAt": 1791557526125
  },
  {
    "id": "aad8ef70-2a6b-469d-af45-30e7e709e3c7",
    "clubCode": "ZWA",
    "opponentCode": "GNT",
    "formationKey": "4-4-2",
    "slots": [
      {
        "positionId": "GK",
        "role": "GK",
        "broadPosition": "GK",
        "xPercent": 50,
        "yPercent": 85,
        "playerName": "Gabriel",
        "playerTeamCode": "ZWA",
        "playerPosition": "GK",
        "playerPrice": 5.5,
        "safety": "red"
      },
      {
        "positionId": "LB",
        "role": "LB",
        "broadPosition": "DEF",
        "xPercent": 16,
        "yPercent": 71,
        "playerName": "Cappelle",
        "playerTeamCode": "ZWA",
        "playerPosition": "DEF",
        "playerPrice": 5,
        "safety": "darkgreen"
      },
      {
        "positionId": "LCB",
        "role": "LCB",
        "broadPosition": "DEF",
        "xPercent": 36,
        "yPercent": 74,
        "playerName": "Kiilerich",
        "playerTeamCode": "ZWA",
        "playerPosition": "DEF",
        "playerPrice": 5,
        "safety": "darkgreen"
      },
      {
        "positionId": "RCB",
        "role": "RCB",
        "broadPosition": "DEF",
        "xPercent": 64,
        "yPercent": 74,
        "playerName": "Lemoine",
        "playerTeamCode": "ZWA",
        "playerPosition": "DEF",
        "playerPrice": 5,
        "safety": "darkgreen"
      },
      {
        "positionId": "RB",
        "role": "RB",
        "broadPosition": "DEF",
        "xPercent": 84,
        "yPercent": 71,
        "playerName": "Diakite",
        "playerTeamCode": "ZWA",
        "playerPosition": "DEF",
        "playerPrice": 5,
        "safety": "red"
      },
      {
        "positionId": "LM",
        "role": "LM",
        "broadPosition": "MID",
        "xPercent": 16,
        "yPercent": 46,
        "playerName": "Atrok",
        "playerTeamCode": "ZWA",
        "playerPosition": "MID",
        "playerPrice": 4.5,
        "safety": "orange"
      },
      {
        "positionId": "LCM",
        "role": "LCM",
        "broadPosition": "MID",
        "xPercent": 33,
        "yPercent": 46,
        "playerName": "Claes",
        "playerTeamCode": "ZWA",
        "playerPosition": "MID",
        "playerPrice": 5,
        "safety": "darkgreen"
      },
      {
        "positionId": "RCM",
        "role": "RCM",
        "broadPosition": "MID",
        "xPercent": 67,
        "yPercent": 46,
        "playerName": "Lofolomo",
        "playerTeamCode": "ZWA",
        "playerPosition": "MID",
        "playerPrice": 5,
        "safety": "darkgreen"
      },
      {
        "positionId": "RM",
        "role": "RM",
        "broadPosition": "MID",
        "xPercent": 84,
        "yPercent": 46,
        "playerName": "Ake",
        "playerTeamCode": "ZWA",
        "playerPosition": "MID",
        "playerPrice": 5.5,
        "safety": "green"
      },
      {
        "positionId": "LST",
        "role": "LST",
        "broadPosition": "FWD",
        "xPercent": 28,
        "yPercent": 15,
        "playerName": "Ementa",
        "playerTeamCode": "ZWA",
        "playerPosition": "FWD",
        "playerPrice": 6.5,
        "safety": "darkgreen"
      },
      {
        "positionId": "RST",
        "role": "RST",
        "broadPosition": "FWD",
        "xPercent": 72,
        "yPercent": 15,
        "playerName": "Hedl",
        "playerTeamCode": "ZWA",
        "playerPosition": "FWD",
        "playerPrice": 6,
        "safety": "red"
      }
    ],
    "notes": "",
    "label": "",
    "createdAt": 1791548070910,
    "updatedAt": 1791557513901
  },
  {
    "id": "012d9de5-76fb-4181-8d8e-1afe6755e60f",
    "clubCode": "GNT",
    "opponentCode": "ZWA",
    "formationKey": "3-5-2",
    "slots": [
      {
        "positionId": "GK",
        "role": "GK",
        "broadPosition": "GK",
        "xPercent": 50,
        "yPercent": 85,
        "playerName": "Roef",
        "playerTeamCode": "GNT",
        "playerPosition": "GK",
        "playerPrice": 7,
        "safety": "darkgreen"
      },
      {
        "positionId": "LCB",
        "role": "LCB",
        "broadPosition": "DEF",
        "xPercent": 36,
        "yPercent": 74,
        "playerName": "Van der Heyden",
        "playerTeamCode": "GNT",
        "playerPosition": "DEF",
        "playerPrice": 5.5,
        "safety": "darkgreen"
      },
      {
        "positionId": "CCB",
        "role": "CCB",
        "broadPosition": "DEF",
        "xPercent": 50,
        "yPercent": 76,
        "playerName": "Burgess",
        "playerTeamCode": "GNT",
        "playerPosition": "DEF",
        "playerPrice": 7,
        "safety": "darkgreen"
      },
      {
        "positionId": "RCB",
        "role": "RCB",
        "broadPosition": "DEF",
        "xPercent": 64,
        "yPercent": 74,
        "playerName": "Paskotsi",
        "playerTeamCode": "GNT",
        "playerPosition": "DEF",
        "playerPrice": 5.5,
        "safety": "green"
      },
      {
        "positionId": "LWB",
        "role": "LWB",
        "broadPosition": "DEF",
        "xPercent": 16,
        "yPercent": 61,
        "playerName": "Araujo",
        "playerTeamCode": "GNT",
        "playerPosition": "DEF",
        "playerPrice": 5.5,
        "safety": "darkgreen"
      },
      {
        "positionId": "LCM",
        "role": "LCM",
        "broadPosition": "MID",
        "xPercent": 33,
        "yPercent": 46,
        "playerName": "Delorge",
        "playerTeamCode": "GNT",
        "playerPosition": "MID",
        "playerPrice": 7,
        "safety": "darkgreen"
      },
      {
        "positionId": "CAM",
        "role": "CAM",
        "broadPosition": "MID",
        "xPercent": 50,
        "yPercent": 30,
        "playerName": "Balikwisha",
        "playerTeamCode": "GNT",
        "playerPosition": "MID",
        "playerPrice": 6.5,
        "safety": "green"
      },
      {
        "positionId": "RCM",
        "role": "RCM",
        "broadPosition": "MID",
        "xPercent": 67,
        "yPercent": 46,
        "playerName": "De Vlieger",
        "playerTeamCode": "GNT",
        "playerPosition": "MID",
        "playerPrice": 6,
        "safety": "darkgreen"
      },
      {
        "positionId": "RWB",
        "role": "RWB",
        "broadPosition": "DEF",
        "xPercent": 84,
        "yPercent": 61,
        "playerName": "Volckaert",
        "playerTeamCode": "GNT",
        "playerPosition": "DEF",
        "playerPrice": 5,
        "safety": "green"
      },
      {
        "positionId": "LST",
        "role": "LST",
        "broadPosition": "FWD",
        "xPercent": 28,
        "yPercent": 15,
        "playerName": "Cisse",
        "playerTeamCode": "GNT",
        "playerPosition": "FWD",
        "playerPrice": 5.5,
        "safety": "orange"
      },
      {
        "positionId": "RST",
        "role": "RST",
        "broadPosition": "FWD",
        "xPercent": 72,
        "yPercent": 15,
        "playerName": "Goore",
        "playerTeamCode": "GNT",
        "playerPosition": "FWD",
        "playerPrice": 6.5,
        "safety": "red"
      }
    ],
    "notes": "",
    "label": "",
    "createdAt": 1791548070910,
    "updatedAt": 1791557529843
  },
  {
    "id": "f4935ff2-a3c0-45a1-b338-ad04b051a84f",
    "clubCode": "STA",
    "opponentCode": "CHA",
    "formationKey": "4-3-3",
    "slots": [
      {
        "positionId": "GK",
        "role": "GK",
        "broadPosition": "GK",
        "xPercent": 50,
        "yPercent": 85,
        "playerName": "Epolo",
        "playerTeamCode": "STA",
        "playerPosition": "GK",
        "playerPrice": 6,
        "safety": "darkgreen"
      },
      {
        "positionId": "LB",
        "role": "LB",
        "broadPosition": "DEF",
        "xPercent": 16,
        "yPercent": 71,
        "playerName": "Mortensen",
        "playerTeamCode": "STA",
        "playerPosition": "DEF",
        "playerPrice": 5,
        "safety": "red"
      },
      {
        "positionId": "LCB",
        "role": "LCB",
        "broadPosition": "DEF",
        "xPercent": 36,
        "yPercent": 74,
        "playerName": "Hautekiet",
        "playerTeamCode": "STA",
        "playerPosition": "DEF",
        "playerPrice": 6,
        "safety": "darkgreen"
      },
      {
        "positionId": "RCB",
        "role": "RCB",
        "broadPosition": "DEF",
        "xPercent": 64,
        "yPercent": 74,
        "playerName": "Karamoko",
        "playerTeamCode": "STA",
        "playerPosition": "MID",
        "playerPrice": 6.5,
        "safety": "darkgreen"
      },
      {
        "positionId": "RB",
        "role": "RB",
        "broadPosition": "DEF",
        "xPercent": 84,
        "yPercent": 71,
        "playerName": "Fossey",
        "playerTeamCode": "STA",
        "playerPosition": "DEF",
        "playerPrice": 6.5,
        "safety": "darkgreen"
      },
      {
        "positionId": "LCM",
        "role": "LCM",
        "broadPosition": "MID",
        "xPercent": 33,
        "yPercent": 46,
        "playerName": "Trouillet",
        "playerTeamCode": "STA",
        "playerPosition": "MID",
        "playerPrice": 4.5,
        "safety": "darkgreen"
      },
      {
        "positionId": "CM",
        "role": "CM",
        "broadPosition": "MID",
        "xPercent": 50,
        "yPercent": 46,
        "playerName": "Nielsen",
        "playerTeamCode": "STA",
        "playerPosition": "MID",
        "playerPrice": 6,
        "safety": "darkgreen"
      },
      {
        "positionId": "RCM",
        "role": "RCM",
        "broadPosition": "MID",
        "xPercent": 67,
        "yPercent": 46,
        "playerName": "Touzghar",
        "playerTeamCode": "STA",
        "playerPosition": "MID",
        "playerPrice": 5.5,
        "safety": "green"
      },
      {
        "positionId": "LW",
        "role": "LW",
        "broadPosition": "FWD",
        "xPercent": 16,
        "yPercent": 21,
        "playerName": "Abid",
        "playerTeamCode": "STA",
        "playerPosition": "MID",
        "playerPrice": 7,
        "safety": "darkgreen"
      },
      {
        "positionId": "ST",
        "role": "ST",
        "broadPosition": "FWD",
        "xPercent": 50,
        "yPercent": 10,
        "playerName": "Ayensa",
        "playerTeamCode": "STA",
        "playerPosition": "FWD",
        "playerPrice": null,
        "safety": "darkgreen"
      },
      {
        "positionId": "RW",
        "role": "RW",
        "broadPosition": "FWD",
        "xPercent": 84,
        "yPercent": 21,
        "playerName": "Nguene",
        "playerTeamCode": "STA",
        "playerPosition": "FWD",
        "playerPrice": 5.5,
        "safety": "red"
      }
    ],
    "notes": "",
    "label": "",
    "createdAt": 1791548070910,
    "updatedAt": 1791557613893
  },
  {
    "id": "adfa1832-345f-4635-9f8a-cfea58629fca",
    "clubCode": "CHA",
    "opponentCode": "STA",
    "formationKey": "4-3-3",
    "slots": [
      {
        "positionId": "GK",
        "role": "GK",
        "broadPosition": "GK",
        "xPercent": 50,
        "yPercent": 85,
        "playerName": "Kone",
        "playerTeamCode": "CHA",
        "playerPosition": "GK",
        "playerPrice": 5.5,
        "safety": "darkgreen"
      },
      {
        "positionId": "LB",
        "role": "LB",
        "broadPosition": "DEF",
        "xPercent": 16,
        "yPercent": 71,
        "playerName": "Nzita",
        "playerTeamCode": "CHA",
        "playerPosition": "DEF",
        "playerPrice": 5.5,
        "safety": "darkgreen"
      },
      {
        "positionId": "LCB",
        "role": "LCB",
        "broadPosition": "DEF",
        "xPercent": 36,
        "yPercent": 74,
        "playerName": "Ousou",
        "playerTeamCode": "CHA",
        "playerPosition": "DEF",
        "playerPrice": 6.5,
        "safety": "darkgreen"
      },
      {
        "positionId": "RCB",
        "role": "RCB",
        "broadPosition": "DEF",
        "xPercent": 64,
        "yPercent": 74,
        "playerName": "Keita",
        "playerTeamCode": "CHA",
        "playerPosition": "DEF",
        "playerPrice": 6,
        "safety": "darkgreen"
      },
      {
        "positionId": "RB",
        "role": "RB",
        "broadPosition": "DEF",
        "xPercent": 84,
        "yPercent": 71,
        "playerName": "Van den Kerkhof",
        "playerTeamCode": "CHA",
        "playerPosition": "DEF",
        "playerPrice": 5.5,
        "safety": "darkgreen"
      },
      {
        "positionId": "LCM",
        "role": "LCM",
        "broadPosition": "MID",
        "xPercent": 33,
        "yPercent": 46,
        "playerName": "Khalifi",
        "playerTeamCode": "CHA",
        "playerPosition": "MID",
        "playerPrice": 4.5,
        "safety": "darkgreen"
      },
      {
        "positionId": "CAM",
        "role": "CAM",
        "broadPosition": "MID",
        "xPercent": 50,
        "yPercent": 30,
        "playerName": "Romsaas",
        "playerTeamCode": "CHA",
        "playerPosition": "FWD",
        "playerPrice": 6.5,
        "safety": "darkgreen"
      },
      {
        "positionId": "RCM",
        "role": "RCM",
        "broadPosition": "MID",
        "xPercent": 67,
        "yPercent": 46,
        "playerName": "Boukamir",
        "playerTeamCode": "CHA",
        "playerPosition": "DEF",
        "playerPrice": 4.5,
        "safety": "darkgreen"
      },
      {
        "positionId": "LW",
        "role": "LW",
        "broadPosition": "FWD",
        "xPercent": 16,
        "yPercent": 21,
        "playerName": "Mbemba",
        "playerTeamCode": "CHA",
        "playerPosition": "FWD",
        "playerPrice": 5,
        "safety": "darkgreen"
      },
      {
        "positionId": "ST",
        "role": "ST",
        "broadPosition": "FWD",
        "xPercent": 50,
        "yPercent": 10,
        "playerName": "Scheidler",
        "playerTeamCode": "CHA",
        "playerPosition": "FWD",
        "playerPrice": 8.5,
        "safety": "darkgreen"
      },
      {
        "positionId": "RW",
        "role": "RW",
        "broadPosition": "FWD",
        "xPercent": 84,
        "yPercent": 21,
        "playerName": "Pflucke",
        "playerTeamCode": "CHA",
        "playerPosition": "MID",
        "playerPrice": 7,
        "safety": "darkgreen"
      }
    ],
    "notes": "",
    "label": "",
    "createdAt": 1791548070910,
    "updatedAt": 1791557545199
  },
  {
    "id": "d6d9fd39-3bb3-4a8b-a403-3184f1c9315a",
    "clubCode": "OHL",
    "opponentCode": "USG",
    "formationKey": "3-5-2",
    "slots": [
      {
        "positionId": "GK",
        "role": "GK",
        "broadPosition": "GK",
        "xPercent": 50,
        "yPercent": 85,
        "playerName": "Van den Heuvel",
        "playerTeamCode": "OHL",
        "playerPosition": "GK",
        "playerPrice": 5,
        "safety": "darkgreen"
      },
      {
        "positionId": "LCB",
        "role": "LCB",
        "broadPosition": "DEF",
        "xPercent": 36,
        "yPercent": 74,
        "playerName": "Lawrence",
        "playerTeamCode": "OHL",
        "playerPosition": "DEF",
        "playerPrice": 5.5,
        "safety": "green"
      },
      {
        "positionId": "CCB",
        "role": "CCB",
        "broadPosition": "DEF",
        "xPercent": 50,
        "yPercent": 76,
        "playerName": "Dussenne",
        "playerTeamCode": "OHL",
        "playerPosition": "DEF",
        "playerPrice": 5,
        "safety": "darkgreen"
      },
      {
        "positionId": "RCB",
        "role": "RCB",
        "broadPosition": "DEF",
        "xPercent": 64,
        "yPercent": 74,
        "playerName": "Pletinckx",
        "playerTeamCode": "OHL",
        "playerPosition": "DEF",
        "playerPrice": 5.5,
        "safety": "red"
      },
      {
        "positionId": "LWB",
        "role": "LWB",
        "broadPosition": "DEF",
        "xPercent": 16,
        "yPercent": 61,
        "playerName": "Opoku",
        "playerTeamCode": "OHL",
        "playerPosition": "DEF",
        "playerPrice": 4.5,
        "safety": "orange"
      },
      {
        "positionId": "LCM",
        "role": "LCM",
        "broadPosition": "MID",
        "xPercent": 33,
        "yPercent": 46,
        "playerName": "Verstraete",
        "playerTeamCode": "OHL",
        "playerPosition": "MID",
        "playerPrice": 6.5,
        "safety": "orange"
      },
      {
        "positionId": "CM",
        "role": "CM",
        "broadPosition": "MID",
        "xPercent": 50,
        "yPercent": 46,
        "playerName": "Schrijvers",
        "playerTeamCode": "OHL",
        "playerPosition": "MID",
        "playerPrice": 8,
        "safety": "darkgreen"
      },
      {
        "positionId": "RCM",
        "role": "RCM",
        "broadPosition": "MID",
        "xPercent": 67,
        "yPercent": 46,
        "playerName": "George",
        "playerTeamCode": "OHL",
        "playerPosition": "MID",
        "playerPrice": 4.5,
        "safety": "darkgreen"
      },
      {
        "positionId": "RWB",
        "role": "RWB",
        "broadPosition": "DEF",
        "xPercent": 84,
        "yPercent": 61,
        "playerName": "Gil",
        "playerTeamCode": "OHL",
        "playerPosition": "DEF",
        "playerPrice": 5.5,
        "safety": "darkgreen"
      },
      {
        "positionId": "LST",
        "role": "LST",
        "broadPosition": "FWD",
        "xPercent": 28,
        "yPercent": 15,
        "playerName": "Mirisola",
        "playerTeamCode": "OHL",
        "playerPosition": "FWD",
        "playerPrice": 6,
        "safety": "red"
      },
      {
        "positionId": "RST",
        "role": "RST",
        "broadPosition": "FWD",
        "xPercent": 72,
        "yPercent": 15,
        "playerName": "Traore",
        "playerTeamCode": "OHL",
        "playerPosition": "FWD",
        "playerPrice": 6,
        "safety": "red"
      }
    ],
    "notes": "",
    "label": "",
    "createdAt": 1791548070910,
    "updatedAt": 1791557488824
  },
  {
    "id": "6db368d7-9d9c-409f-a2ba-9a1fce8c8b76",
    "clubCode": "USG",
    "opponentCode": "OHL",
    "formationKey": "3-5-2",
    "slots": [
      {
        "positionId": "GK",
        "role": "GK",
        "broadPosition": "GK",
        "xPercent": 50,
        "yPercent": 85,
        "playerName": "Koffi",
        "playerTeamCode": "USG",
        "playerPosition": "GK",
        "playerPrice": 6.5,
        "safety": "orange"
      },
      {
        "positionId": "LCB",
        "role": "LCB",
        "broadPosition": "DEF",
        "xPercent": 36,
        "yPercent": 74,
        "playerName": "Kricfalusi",
        "playerTeamCode": "USG",
        "playerPosition": "MID",
        "playerPrice": 5.5,
        "safety": "darkgreen"
      },
      {
        "positionId": "CCB",
        "role": "CCB",
        "broadPosition": "DEF",
        "xPercent": 50,
        "yPercent": 76,
        "playerName": "Sylla",
        "playerTeamCode": "USG",
        "playerPosition": "DEF",
        "playerPrice": 5,
        "safety": "darkgreen"
      },
      {
        "positionId": "RCB",
        "role": "RCB",
        "broadPosition": "DEF",
        "xPercent": 64,
        "yPercent": 74,
        "playerName": "Havenaar",
        "playerTeamCode": "USG",
        "playerPosition": "DEF",
        "playerPrice": 5.5,
        "safety": "darkgreen"
      },
      {
        "positionId": "LWB",
        "role": "LWB",
        "broadPosition": "DEF",
        "xPercent": 16,
        "yPercent": 61,
        "playerName": "Smith",
        "playerTeamCode": "USG",
        "playerPosition": "FWD",
        "playerPrice": 6.5,
        "safety": "darkgreen"
      },
      {
        "positionId": "LCM",
        "role": "LCM",
        "broadPosition": "MID",
        "xPercent": 33,
        "yPercent": 46,
        "playerName": "Schoofs",
        "playerTeamCode": "USG",
        "playerPosition": "MID",
        "playerPrice": 9,
        "safety": "red"
      },
      {
        "positionId": "CAM",
        "role": "CAM",
        "broadPosition": "MID",
        "xPercent": 50,
        "yPercent": 30,
        "playerName": "Zeneli",
        "playerTeamCode": "USG",
        "playerPosition": "MID",
        "playerPrice": 6.5,
        "safety": "green"
      },
      {
        "positionId": "RCM",
        "role": "RCM",
        "broadPosition": "MID",
        "xPercent": 67,
        "yPercent": 46,
        "playerName": "Van de Perre",
        "playerTeamCode": "USG",
        "playerPosition": "MID",
        "playerPrice": 7,
        "safety": "darkgreen"
      },
      {
        "positionId": "RWB",
        "role": "RWB",
        "broadPosition": "DEF",
        "xPercent": 84,
        "yPercent": 61,
        "playerName": "Patris",
        "playerTeamCode": "USG",
        "playerPosition": "DEF",
        "playerPrice": 6,
        "safety": "green"
      },
      {
        "positionId": "LST",
        "role": "LST",
        "broadPosition": "FWD",
        "xPercent": 28,
        "yPercent": 15,
        "playerName": "Mofokeng",
        "playerTeamCode": "USG",
        "playerPosition": "MID",
        "playerPrice": 7.5,
        "safety": "orange"
      },
      {
        "positionId": "RST",
        "role": "RST",
        "broadPosition": "FWD",
        "xPercent": 72,
        "yPercent": 15,
        "playerName": "Biondic",
        "playerTeamCode": "USG",
        "playerPosition": "FWD",
        "playerPrice": 6,
        "safety": "green"
      }
    ],
    "notes": "",
    "label": "",
    "createdAt": 1791548070910,
    "updatedAt": 1791557506159
  },
  {
    "id": "412fc901-cac0-438d-bbd7-48fd353200e4",
    "clubCode": "WES",
    "opponentCode": "ANT",
    "formationKey": "4-3-3",
    "slots": [
      {
        "positionId": "GK",
        "role": "GK",
        "broadPosition": "GK",
        "xPercent": 50,
        "yPercent": 85,
        "playerName": "Jungdal",
        "playerTeamCode": "WES",
        "playerPosition": "GK",
        "playerPrice": 6.5,
        "safety": "darkgreen"
      },
      {
        "positionId": "LB",
        "role": "LB",
        "broadPosition": "DEF",
        "xPercent": 16,
        "yPercent": 71,
        "playerName": "Ourega",
        "playerTeamCode": "WES",
        "playerPosition": "DEF",
        "playerPrice": 4.5,
        "safety": "green"
      },
      {
        "positionId": "LCB",
        "role": "LCB",
        "broadPosition": "DEF",
        "xPercent": 36,
        "yPercent": 74,
        "playerName": "Lapage",
        "playerTeamCode": "WES",
        "playerPosition": "DEF",
        "playerPrice": 5,
        "safety": "darkgreen"
      },
      {
        "positionId": "RCB",
        "role": "RCB",
        "broadPosition": "DEF",
        "xPercent": 64,
        "yPercent": 74,
        "playerName": "Kimura",
        "playerTeamCode": "WES",
        "playerPosition": "DEF",
        "playerPrice": 5,
        "safety": "darkgreen"
      },
      {
        "positionId": "RB",
        "role": "RB",
        "broadPosition": "DEF",
        "xPercent": 84,
        "yPercent": 71,
        "playerName": "Flo",
        "playerTeamCode": "WES",
        "playerPosition": "DEF",
        "playerPrice": 5,
        "safety": "darkgreen"
      },
      {
        "positionId": "LCM",
        "role": "LCM",
        "broadPosition": "MID",
        "xPercent": 33,
        "yPercent": 46,
        "playerName": "Fofana",
        "playerTeamCode": "WES",
        "playerPosition": "MID",
        "playerPrice": 5.5,
        "safety": "darkgreen"
      },
      {
        "positionId": "CAM",
        "role": "CAM",
        "broadPosition": "MID",
        "xPercent": 50,
        "yPercent": 30,
        "playerName": "Sakamoto",
        "playerTeamCode": "WES",
        "playerPosition": "FWD",
        "playerPrice": 7,
        "safety": "darkgreen"
      },
      {
        "positionId": "RCM",
        "role": "RCM",
        "broadPosition": "MID",
        "xPercent": 67,
        "yPercent": 46,
        "playerName": "Sandra",
        "playerTeamCode": "WES",
        "playerPosition": "MID",
        "playerPrice": 6,
        "safety": "darkgreen"
      },
      {
        "positionId": "LW",
        "role": "LW",
        "broadPosition": "FWD",
        "xPercent": 16,
        "yPercent": 21,
        "playerName": "Saito",
        "playerTeamCode": "WES",
        "playerPosition": "MID",
        "playerPrice": 5.5,
        "safety": "green"
      },
      {
        "positionId": "ST",
        "role": "ST",
        "broadPosition": "FWD",
        "xPercent": 50,
        "yPercent": 10,
        "playerName": "Bassette",
        "playerTeamCode": "WES",
        "playerPosition": "FWD",
        "playerPrice": 6.5,
        "safety": "darkgreen"
      },
      {
        "positionId": "RW",
        "role": "RW",
        "broadPosition": "FWD",
        "xPercent": 84,
        "yPercent": 21,
        "playerName": "Congreve",
        "playerTeamCode": "WES",
        "playerPosition": "MID",
        "playerPrice": 5.5,
        "safety": "green"
      }
    ],
    "notes": "",
    "label": "",
    "createdAt": 1791548070910,
    "updatedAt": 1791557510672
  },
  {
    "id": "fd3206c5-d4e2-4cd0-8a1d-81dedc0376f9",
    "clubCode": "ANT",
    "opponentCode": "WES",
    "formationKey": "4-4-2",
    "slots": [
      {
        "positionId": "GK",
        "role": "GK",
        "broadPosition": "GK",
        "xPercent": 50,
        "yPercent": 85,
        "playerName": "Nozawa",
        "playerTeamCode": "ANT",
        "playerPosition": "GK",
        "playerPrice": 6,
        "safety": "darkgreen"
      },
      {
        "positionId": "LB",
        "role": "LB",
        "broadPosition": "DEF",
        "xPercent": 16,
        "yPercent": 71,
        "playerName": "Foulon",
        "playerTeamCode": "ANT",
        "playerPosition": "DEF",
        "playerPrice": 6.5,
        "safety": "red"
      },
      {
        "positionId": "LCB",
        "role": "LCB",
        "broadPosition": "DEF",
        "xPercent": 36,
        "yPercent": 74,
        "playerName": "Cortes",
        "playerTeamCode": "ANT",
        "playerPosition": "DEF",
        "playerPrice": 6,
        "safety": "darkgreen"
      },
      {
        "positionId": "RCB",
        "role": "RCB",
        "broadPosition": "DEF",
        "xPercent": 64,
        "yPercent": 74,
        "playerName": "Van Helden",
        "playerTeamCode": "ANT",
        "playerPosition": "DEF",
        "playerPrice": 6.5,
        "safety": "red"
      },
      {
        "positionId": "RB",
        "role": "RB",
        "broadPosition": "DEF",
        "xPercent": 84,
        "yPercent": 71,
        "playerName": "Busi",
        "playerTeamCode": "ANT",
        "playerPosition": "DEF",
        "playerPrice": 5.5,
        "safety": "darkgreen"
      },
      {
        "positionId": "LM",
        "role": "LM",
        "broadPosition": "MID",
        "xPercent": 16,
        "yPercent": 46,
        "playerName": "Salah",
        "playerTeamCode": "ANT",
        "playerPosition": "MID",
        "playerPrice": 6,
        "safety": "red"
      },
      {
        "positionId": "LCM",
        "role": "LCM",
        "broadPosition": "MID",
        "xPercent": 33,
        "yPercent": 46,
        "playerName": "Vermeeren",
        "playerTeamCode": "ANT",
        "playerPosition": "MID",
        "playerPrice": 8,
        "safety": "darkgreen"
      },
      {
        "positionId": "RCM",
        "role": "RCM",
        "broadPosition": "MID",
        "xPercent": 67,
        "yPercent": 46,
        "playerName": "Dierckx",
        "playerTeamCode": "ANT",
        "playerPosition": "MID",
        "playerPrice": 5,
        "safety": "red"
      },
      {
        "positionId": "RM",
        "role": "RM",
        "broadPosition": "MID",
        "xPercent": 84,
        "yPercent": 46,
        "playerName": "Somers",
        "playerTeamCode": "ANT",
        "playerPosition": "MID",
        "playerPrice": 8,
        "safety": "green"
      },
      {
        "positionId": "LST",
        "role": "LST",
        "broadPosition": "FWD",
        "xPercent": 28,
        "yPercent": 15,
        "playerName": "Frey",
        "playerTeamCode": "ANT",
        "playerPosition": "FWD",
        "playerPrice": 6.5,
        "safety": "darkgreen"
      },
      {
        "positionId": "RST",
        "role": "RST",
        "broadPosition": "FWD",
        "xPercent": 72,
        "yPercent": 15,
        "playerName": "Fofana",
        "playerTeamCode": "ANT",
        "playerPosition": "MID",
        "playerPrice": 4.5,
        "safety": "red"
      }
    ],
    "notes": "",
    "label": "",
    "createdAt": 1791548070911,
    "updatedAt": 1791557559056
  },
  {
    "id": "4f140eb1-2828-4c73-9ff6-0a8f916dbb7a",
    "clubCode": "KVM",
    "opponentCode": "STV",
    "formationKey": "3-4-3",
    "slots": [
      {
        "positionId": "GK",
        "role": "GK",
        "broadPosition": "GK",
        "xPercent": 50,
        "yPercent": 85,
        "playerName": "Miras",
        "playerTeamCode": "KVM",
        "playerPosition": "GK",
        "playerPrice": 6.5,
        "safety": "darkgreen"
      },
      {
        "positionId": "LCB",
        "role": "LCB",
        "broadPosition": "DEF",
        "xPercent": 36,
        "yPercent": 74,
        "playerName": "Marsa",
        "playerTeamCode": "KVM",
        "playerPosition": "DEF",
        "playerPrice": 5.5,
        "safety": "darkgreen"
      },
      {
        "positionId": "CCB",
        "role": "CCB",
        "broadPosition": "DEF",
        "xPercent": 50,
        "yPercent": 76,
        "playerName": "Eerdhuijzen",
        "playerTeamCode": "KVM",
        "playerPosition": "DEF",
        "playerPrice": 5,
        "safety": "darkgreen"
      },
      {
        "positionId": "RCB",
        "role": "RCB",
        "broadPosition": "DEF",
        "xPercent": 64,
        "yPercent": 74,
        "playerName": "Marijnissen",
        "playerTeamCode": "KVM",
        "playerPosition": "DEF",
        "playerPrice": 5,
        "safety": "darkgreen"
      },
      {
        "positionId": "LM",
        "role": "LM",
        "broadPosition": "MID",
        "xPercent": 16,
        "yPercent": 46,
        "playerName": "Koudou",
        "playerTeamCode": "KVM",
        "playerPosition": "DEF",
        "playerPrice": 6,
        "safety": "darkgreen"
      },
      {
        "positionId": "LCM",
        "role": "LCM",
        "broadPosition": "MID",
        "xPercent": 33,
        "yPercent": 46,
        "playerName": "Hammar",
        "playerTeamCode": "KVM",
        "playerPosition": "MID",
        "playerPrice": 7,
        "safety": "darkgreen"
      },
      {
        "positionId": "RCM",
        "role": "RCM",
        "broadPosition": "MID",
        "xPercent": 67,
        "yPercent": 46,
        "playerName": "Praet",
        "playerTeamCode": "KVM",
        "playerPosition": "MID",
        "playerPrice": 7,
        "safety": "darkgreen"
      },
      {
        "positionId": "RM",
        "role": "RM",
        "broadPosition": "MID",
        "xPercent": 84,
        "yPercent": 46,
        "playerName": "Michez",
        "playerTeamCode": "KVM",
        "playerPosition": "MID",
        "playerPrice": 5,
        "safety": "red"
      },
      {
        "positionId": "LW",
        "role": "LW",
        "broadPosition": "FWD",
        "xPercent": 16,
        "yPercent": 21,
        "playerName": "Van Brederode",
        "playerTeamCode": "KVM",
        "playerPosition": "FWD",
        "playerPrice": 7,
        "safety": "darkgreen"
      },
      {
        "positionId": "ST",
        "role": "ST",
        "broadPosition": "FWD",
        "xPercent": 50,
        "yPercent": 10,
        "playerName": "Boersma",
        "playerTeamCode": "KVM",
        "playerPosition": "FWD",
        "playerPrice": 6.5,
        "safety": "darkgreen"
      },
      {
        "positionId": "RW",
        "role": "RW",
        "broadPosition": "FWD",
        "xPercent": 84,
        "yPercent": 21,
        "playerName": "Raman",
        "playerTeamCode": "KVM",
        "playerPosition": "FWD",
        "playerPrice": 7.5,
        "safety": "red"
      }
    ],
    "notes": "",
    "label": "",
    "createdAt": 1791548070911,
    "updatedAt": 1791557519020
  },
  {
    "id": "82a427c3-8c89-444f-a1d2-5067ae661667",
    "clubCode": "STV",
    "opponentCode": "KVM",
    "formationKey": "4-3-3",
    "slots": [
      {
        "positionId": "GK",
        "role": "GK",
        "broadPosition": "GK",
        "xPercent": 50,
        "yPercent": 85,
        "playerName": "Kokubo",
        "playerTeamCode": "STV",
        "playerPosition": "GK",
        "playerPrice": 6.5,
        "safety": "darkgreen"
      },
      {
        "positionId": "LB",
        "role": "LB",
        "broadPosition": "DEF",
        "xPercent": 16,
        "yPercent": 71,
        "playerName": "Hata",
        "playerTeamCode": "STV",
        "playerPosition": "DEF",
        "playerPrice": 5.5,
        "safety": "red"
      },
      {
        "positionId": "LCB",
        "role": "LCB",
        "broadPosition": "DEF",
        "xPercent": 36,
        "yPercent": 74,
        "playerName": "Musliu",
        "playerTeamCode": "STV",
        "playerPosition": "DEF",
        "playerPrice": 6,
        "safety": "darkgreen"
      },
      {
        "positionId": "RCB",
        "role": "RCB",
        "broadPosition": "DEF",
        "xPercent": 64,
        "yPercent": 74,
        "playerName": "Taniguchi",
        "playerTeamCode": "STV",
        "playerPosition": "DEF",
        "playerPrice": 6,
        "safety": "darkgreen"
      },
      {
        "positionId": "RB",
        "role": "RB",
        "broadPosition": "DEF",
        "xPercent": 84,
        "yPercent": 71,
        "playerName": "Vanwesemael",
        "playerTeamCode": "STV",
        "playerPosition": "DEF",
        "playerPrice": 5.5,
        "safety": "darkgreen"
      },
      {
        "positionId": "LCM",
        "role": "LCM",
        "broadPosition": "MID",
        "xPercent": 33,
        "yPercent": 46,
        "playerName": "Sissako",
        "playerTeamCode": "STV",
        "playerPosition": "MID",
        "playerPrice": 6.5,
        "safety": "darkgreen"
      },
      {
        "positionId": "CAM",
        "role": "CAM",
        "broadPosition": "MID",
        "xPercent": 50,
        "yPercent": 30,
        "playerName": "Araki",
        "playerTeamCode": "STV",
        "playerPosition": "MID",
        "playerPrice": 5.5,
        "safety": "green"
      },
      {
        "positionId": "RCM",
        "role": "RCM",
        "broadPosition": "MID",
        "xPercent": 67,
        "yPercent": 46,
        "playerName": "Merlen",
        "playerTeamCode": "STV",
        "playerPosition": "MID",
        "playerPrice": 5.5,
        "safety": "darkgreen"
      },
      {
        "positionId": "LW",
        "role": "LW",
        "broadPosition": "FWD",
        "xPercent": 16,
        "yPercent": 21,
        "playerName": "Sebaoui",
        "playerTeamCode": "STV",
        "playerPosition": "MID",
        "playerPrice": 8,
        "safety": "darkgreen"
      },
      {
        "positionId": "ST",
        "role": "ST",
        "broadPosition": "FWD",
        "xPercent": 50,
        "yPercent": 10,
        "playerName": "Bazdar",
        "playerTeamCode": "STV",
        "playerPosition": "FWD",
        "playerPrice": 5.5,
        "safety": "orange"
      },
      {
        "positionId": "RW",
        "role": "RW",
        "broadPosition": "FWD",
        "xPercent": 84,
        "yPercent": 21,
        "playerName": "Matsuzawa",
        "playerTeamCode": "STV",
        "playerPosition": "MID",
        "playerPrice": 6,
        "safety": "red"
      }
    ],
    "notes": "",
    "label": "",
    "createdAt": 1791548070911,
    "updatedAt": 1791557502724
  },
  {
    "id": "2bb14bbb-9280-4025-9e3a-865b7ec21091",
    "clubCode": "BEV",
    "opponentCode": "LOM",
    "formationKey": "4-3-3",
    "slots": [
      {
        "positionId": "GK",
        "role": "GK",
        "broadPosition": "GK",
        "xPercent": 50,
        "yPercent": 85,
        "playerName": "Schenk",
        "playerTeamCode": "BEV",
        "playerPosition": "GK",
        "playerPrice": 5,
        "safety": "green"
      },
      {
        "positionId": "LB",
        "role": "LB",
        "broadPosition": "DEF",
        "xPercent": 16,
        "yPercent": 71,
        "playerName": "Janssens",
        "playerTeamCode": "BEV",
        "playerPosition": "DEF",
        "playerPrice": 5,
        "safety": "darkgreen"
      },
      {
        "positionId": "LCB",
        "role": "LCB",
        "broadPosition": "DEF",
        "xPercent": 36,
        "yPercent": 74,
        "playerName": "Godeau",
        "playerTeamCode": "BEV",
        "playerPosition": "DEF",
        "playerPrice": 5.5,
        "safety": "darkgreen"
      },
      {
        "positionId": "RCB",
        "role": "RCB",
        "broadPosition": "DEF",
        "xPercent": 64,
        "yPercent": 74,
        "playerName": "Gomis",
        "playerTeamCode": "BEV",
        "playerPosition": "DEF",
        "playerPrice": 4.5,
        "safety": "green"
      },
      {
        "positionId": "RB",
        "role": "RB",
        "broadPosition": "DEF",
        "xPercent": 84,
        "yPercent": 71,
        "playerName": "Konate",
        "playerTeamCode": "BEV",
        "playerPosition": "DEF",
        "playerPrice": 4.5,
        "safety": "darkgreen"
      },
      {
        "positionId": "LCM",
        "role": "LCM",
        "broadPosition": "MID",
        "xPercent": 33,
        "yPercent": 46,
        "playerName": "Conde",
        "playerTeamCode": "BEV",
        "playerPosition": "MID",
        "playerPrice": 5,
        "safety": "green"
      },
      {
        "positionId": "CAM",
        "role": "CAM",
        "broadPosition": "MID",
        "xPercent": 50,
        "yPercent": 30,
        "playerName": "Bruls",
        "playerTeamCode": "BEV",
        "playerPosition": "MID",
        "playerPrice": 6.5,
        "safety": "darkgreen"
      },
      {
        "positionId": "RCM",
        "role": "RCM",
        "broadPosition": "MID",
        "xPercent": 67,
        "yPercent": 46,
        "playerName": "Dewaele",
        "playerTeamCode": "BEV",
        "playerPosition": "MID",
        "playerPrice": 5.5,
        "safety": "green"
      },
      {
        "positionId": "LW",
        "role": "LW",
        "broadPosition": "FWD",
        "xPercent": 16,
        "yPercent": 21,
        "playerName": "Margaritha",
        "playerTeamCode": "BEV",
        "playerPosition": "MID",
        "playerPrice": 6.5,
        "safety": "darkgreen"
      },
      {
        "positionId": "ST",
        "role": "ST",
        "broadPosition": "FWD",
        "xPercent": 50,
        "yPercent": 10,
        "playerName": "Mertens",
        "playerTeamCode": "BEV",
        "playerPosition": "FWD",
        "playerPrice": 7.5,
        "safety": "red"
      },
      {
        "positionId": "RW",
        "role": "RW",
        "broadPosition": "FWD",
        "xPercent": 84,
        "yPercent": 21,
        "playerName": "Lokesa",
        "playerTeamCode": "BEV",
        "playerPosition": "MID",
        "playerPrice": 5,
        "safety": "darkgreen"
      }
    ],
    "notes": "",
    "label": "",
    "createdAt": 1791548070911,
    "updatedAt": 1791557553187
  },
  {
    "id": "36da7406-a582-45f3-b257-b9458e0a236c",
    "clubCode": "LOM",
    "opponentCode": "BEV",
    "formationKey": "4-3-3",
    "slots": [
      {
        "positionId": "GK",
        "role": "GK",
        "broadPosition": "GK",
        "xPercent": 50,
        "yPercent": 85,
        "playerName": "Pieklak",
        "playerTeamCode": "LOM",
        "playerPosition": "GK",
        "playerPrice": 5.5,
        "safety": "darkgreen"
      },
      {
        "positionId": "LB",
        "role": "LB",
        "broadPosition": "DEF",
        "xPercent": 16,
        "yPercent": 71,
        "playerName": "Adewoye",
        "playerTeamCode": "LOM",
        "playerPosition": "DEF",
        "playerPrice": 4.5,
        "safety": "darkgreen"
      },
      {
        "positionId": "LCB",
        "role": "LCB",
        "broadPosition": "DEF",
        "xPercent": 36,
        "yPercent": 74,
        "playerName": "Eyoma",
        "playerTeamCode": "LOM",
        "playerPosition": "DEF",
        "playerPrice": 4.5,
        "safety": "darkgreen"
      },
      {
        "positionId": "RCB",
        "role": "RCB",
        "broadPosition": "DEF",
        "xPercent": 64,
        "yPercent": 74,
        "playerName": "Rommens",
        "playerTeamCode": "LOM",
        "playerPosition": "MID",
        "playerPrice": 5.5,
        "safety": "darkgreen"
      },
      {
        "positionId": "RB",
        "role": "RB",
        "broadPosition": "DEF",
        "xPercent": 84,
        "yPercent": 71,
        "playerName": "Van Duiven",
        "playerTeamCode": "LOM",
        "playerPosition": "FWD",
        "playerPrice": 5,
        "safety": "green"
      },
      {
        "positionId": "LCM",
        "role": "LCM",
        "broadPosition": "MID",
        "xPercent": 33,
        "yPercent": 46,
        "playerName": "Schoofs",
        "playerTeamCode": "LOM",
        "playerPosition": "MID",
        "playerPrice": 6.5,
        "safety": "darkgreen"
      },
      {
        "positionId": "CM",
        "role": "CM",
        "broadPosition": "MID",
        "xPercent": 50,
        "yPercent": 46,
        "playerName": "Reyners",
        "playerTeamCode": "LOM",
        "playerPosition": "MID",
        "playerPrice": 5.5,
        "safety": "darkgreen"
      },
      {
        "positionId": "RCM",
        "role": "RCM",
        "broadPosition": "MID",
        "xPercent": 67,
        "yPercent": 46,
        "playerName": "Pelupessy",
        "playerTeamCode": "LOM",
        "playerPosition": "MID",
        "playerPrice": 5,
        "safety": "orange"
      },
      {
        "positionId": "LW",
        "role": "LW",
        "broadPosition": "FWD",
        "xPercent": 16,
        "yPercent": 21,
        "playerName": "Appuah",
        "playerTeamCode": "LOM",
        "playerPosition": "MID",
        "playerPrice": 4,
        "safety": "green"
      },
      {
        "positionId": "ST",
        "role": "ST",
        "broadPosition": "FWD",
        "xPercent": 50,
        "yPercent": 10,
        "playerName": "Konadu",
        "playerTeamCode": "LOM",
        "playerPosition": "FWD",
        "playerPrice": 5,
        "safety": "darkgreen"
      },
      {
        "positionId": "RW",
        "role": "RW",
        "broadPosition": "FWD",
        "xPercent": 84,
        "yPercent": 21,
        "playerName": "Talvitie",
        "playerTeamCode": "LOM",
        "playerPosition": "MID",
        "playerPrice": 4,
        "safety": "red"
      }
    ],
    "notes": "",
    "label": "",
    "createdAt": 1791548070911,
    "updatedAt": 1791557486417
  }
];
