// Vaste data voor de publieke "Predicted Lineups"-tab (zie src/tabs/PredictedLineupsTab.jsx) — zelfde
// conventie als TEAMS/FIXTURES in constants.js: gewoon een statische constante, geen fetch, geen
// bewerkbare state.
//
// Elke entry heeft grotendeels dezelfde vorm als een record uit de privé Predicted XI Builder's
// opgeslagen lineups (zie loadStoredDrafts()/sanitizeDraft() in src/predicted-xi/storage.js): clubCode,
// opponentCode, formationKey, formationLabelOverride, slots (met per slot playerName/playerTeamCode/
// playerPosition/playerPrice/safety/positionId/xPercent/yPercent), notes. Eén extra veld bestaat enkel
// hier: lastUpdatedLabel — een vrije, handmatig ingevulde tekst (bv. "donderdag 06 augustus 18:00"),
// getoond als subtiel "laatst geüpdatet"-tekstje op de publieke tab (zie PredictedLineupsTab.jsx). Geen
// automatisch berekende datum, want elke lineup wordt apart en onregelmatig bijgewerkt — pas dit veld
// per club gewoon rechtstreeks hier aan wanneer die lineup opnieuw nagekeken is.
//
// Alle 18 clubs (aangeleverd 6-7 augustus 2026, Anderlecht en Gent op 7 augustus aangevuld).
// Ontbrekende/nog niet-afgewerkte clubs tonen vanzelf geen kaart in de kiezer (PredictedLineupsTab.jsx
// filtert lineups zonder geplaatste spelers eruit), dus deze lijst kan gewoon aangevuld/bijgewerkt
// worden zonder verdere codewijzigingen.
export const PREDICTED_LINEUPS = [
  {
    "id": "d70878df-a617-47fd-bbe7-1ddccda6c5e4",
    "clubCode": "KOR",
    "opponentCode": "CLU",
    "formationKey": "5-3-2",
    "lastUpdatedLabel": "donderdag 06 augustus 18:00",
    "slots": [
      {
        "positionId": "GK",
        "role": "GK",
        "broadPosition": "GK",
        "xPercent": 50,
        "yPercent": 92,
        "playerName": "Ilic",
        "playerTeamCode": "KOR",
        "playerPosition": "GK",
        "playerPrice": 6,
        "safety": "red"
      },
      {
        "positionId": "LWB",
        "role": "LWB",
        "broadPosition": "DEF",
        "xPercent": 16,
        "yPercent": 61,
        "playerName": "Andersson",
        "playerTeamCode": "KOR",
        "playerPosition": "DEF",
        "playerPrice": 5,
        "safety": "darkgreen"
      },
      {
        "positionId": "LCB",
        "role": "LCB",
        "broadPosition": "DEF",
        "xPercent": 33,
        "yPercent": 74,
        "playerName": "Ndjeungoue",
        "playerTeamCode": "KOR",
        "playerPosition": "DEF",
        "playerPrice": 5,
        "safety": "darkgreen"
      },
      {
        "positionId": "CCB",
        "role": "CCB",
        "broadPosition": "DEF",
        "xPercent": 50,
        "yPercent": 76,
        "playerName": "Kohon",
        "playerTeamCode": "KOR",
        "playerPosition": "DEF",
        "playerPrice": 4.5,
        "safety": "darkgreen"
      },
      {
        "positionId": "RWB",
        "role": "RWB",
        "broadPosition": "DEF",
        "xPercent": 84,
        "yPercent": 61,
        "playerName": "Campbell",
        "playerTeamCode": "KOR",
        "playerPosition": "MID",
        "playerPrice": 6,
        "safety": "orange"
      },
      {
        "positionId": "RCB",
        "role": "RCB",
        "broadPosition": "DEF",
        "xPercent": 67,
        "yPercent": 74,
        "playerName": "Ruyssen",
        "playerTeamCode": "KOR",
        "playerPosition": "DEF",
        "playerPrice": 5,
        "safety": "darkgreen"
      },
      {
        "positionId": "LCM",
        "role": "LCM",
        "broadPosition": "MID",
        "xPercent": 33,
        "yPercent": 46,
        "playerName": "Dejaegere",
        "playerTeamCode": "KOR",
        "playerPosition": "MID",
        "playerPrice": 5,
        "safety": "green"
      },
      {
        "positionId": "RCM",
        "role": "RCM",
        "broadPosition": "MID",
        "xPercent": 67,
        "yPercent": 46,
        "playerName": "Lambert",
        "playerTeamCode": "KOR",
        "playerPosition": "DEF",
        "playerPrice": 5,
        "safety": "darkgreen"
      },
      {
        "positionId": "RW",
        "role": "RW",
        "broadPosition": "FWD",
        "xPercent": 84,
        "yPercent": 21,
        "playerName": "Ambrose",
        "playerTeamCode": "KOR",
        "playerPosition": "FWD",
        "playerPrice": 7,
        "safety": "darkgreen"
      },
      {
        "positionId": "LW",
        "role": "LW",
        "broadPosition": "FWD",
        "xPercent": 16,
        "yPercent": 21,
        "playerName": "Masui",
        "playerTeamCode": "KOR",
        "playerPosition": "MID",
        "playerPrice": 5,
        "safety": "green"
      },
      {
        "positionId": "ST",
        "role": "ST",
        "broadPosition": "FWD",
        "xPercent": 50,
        "yPercent": 10,
        "playerName": "Koyalipou",
        "playerTeamCode": "KOR",
        "playerPosition": "FWD",
        "playerPrice": 5.5,
        "safety": "green"
      },
      {
        "positionId": "_unassigned",
        "role": "FWD",
        "broadPosition": "FWD",
        "xPercent": 0,
        "yPercent": 0,
        "playerName": "Ambrose",
        "playerTeamCode": "KOR",
        "playerPosition": "FWD",
        "playerPrice": 7,
        "safety": "darkgreen"
      }
    ],
    "notes": "",
    "label": "",
    "createdAt": 1785947794534,
    "updatedAt": 1786020058904
  },
  {
    "id": "2d8dbd09-5930-449e-b107-8604a733c255",
    "clubCode": "STA",
    "opponentCode": "CER",
    "formationKey": "4-3-3",
    "lastUpdatedLabel": "donderdag 06 augustus 18:00",
    "slots": [
      {
        "positionId": "GK",
        "role": "GK",
        "broadPosition": "GK",
        "xPercent": 50,
        "yPercent": 92,
        "playerName": "Epolo",
        "playerTeamCode": "STA",
        "playerPosition": "GK",
        "playerPrice": 6,
        "safety": "darkgreen"
      },
      {
        "positionId": "LWB",
        "role": "LWB",
        "broadPosition": "DEF",
        "xPercent": 16,
        "yPercent": 64,
        "playerName": "Mortensen",
        "playerTeamCode": "STA",
        "playerPosition": "DEF",
        "playerPrice": 5,
        "safety": "darkgreen"
      },
      {
        "positionId": "LCB",
        "role": "LCB",
        "broadPosition": "DEF",
        "xPercent": 30,
        "yPercent": 79,
        "playerName": "Karamoko",
        "playerTeamCode": "STA",
        "playerPosition": "MID",
        "playerPrice": 6.5,
        "safety": "green"
      },
      {
        "positionId": "RCB",
        "role": "RCB",
        "broadPosition": "DEF",
        "xPercent": 70,
        "yPercent": 79,
        "playerName": "Hautekiet",
        "playerTeamCode": "STA",
        "playerPosition": "DEF",
        "playerPrice": 6,
        "safety": "darkgreen"
      },
      {
        "positionId": "RWB",
        "role": "RWB",
        "broadPosition": "DEF",
        "xPercent": 84,
        "yPercent": 64,
        "playerName": "Fossey",
        "playerTeamCode": "STA",
        "playerPosition": "DEF",
        "playerPrice": 6.5,
        "safety": "darkgreen"
      },
      {
        "positionId": "LCM",
        "role": "LCM",
        "broadPosition": "MID",
        "xPercent": 35,
        "yPercent": 47,
        "playerName": "Nielsen",
        "playerTeamCode": "STA",
        "playerPosition": "MID",
        "playerPrice": 6,
        "safety": "darkgreen"
      },
      {
        "positionId": "CAM",
        "role": "CAM",
        "broadPosition": "MID",
        "xPercent": 50,
        "yPercent": 28,
        "playerName": "Trouillet",
        "playerTeamCode": "STA",
        "playerPosition": "MID",
        "playerPrice": 4.5,
        "safety": "red"
      },
      {
        "positionId": "RCM",
        "role": "RCM",
        "broadPosition": "MID",
        "xPercent": 65,
        "yPercent": 47,
        "playerName": "Ilaimaharitra",
        "playerTeamCode": "STA",
        "playerPosition": "MID",
        "playerPrice": 6,
        "safety": "orange"
      },
      {
        "positionId": "LW",
        "role": "LW",
        "broadPosition": "FWD",
        "xPercent": 15,
        "yPercent": 16,
        "playerName": "Drammeh",
        "playerTeamCode": "STA",
        "playerPosition": "FWD",
        "playerPrice": 5.5,
        "safety": "orange"
      },
      {
        "positionId": "ST",
        "role": "ST",
        "broadPosition": "FWD",
        "xPercent": 50,
        "yPercent": 8,
        "playerName": "Nsimba",
        "playerTeamCode": "STA",
        "playerPosition": "FWD",
        "playerPrice": 8.5,
        "safety": "red"
      },
      {
        "positionId": "RW",
        "role": "RW",
        "broadPosition": "FWD",
        "xPercent": 85,
        "yPercent": 16,
        "playerName": "Abid",
        "playerTeamCode": "STA",
        "playerPosition": "MID",
        "playerPrice": 7,
        "safety": "green"
      }
    ],
    "notes": "",
    "label": "",
    "createdAt": 1785948686002,
    "updatedAt": 1786020224083
  },
  {
    "id": "6127756f-0bcf-42b1-900d-6dde71618e92",
    "clubCode": "CER",
    "opponentCode": "STA",
    "formationKey": "5-3-2",
    "lastUpdatedLabel": "vrijdag 07 augustus 14:15",
    "slots": [
      {
        "positionId": "GK",
        "role": "GK",
        "broadPosition": "GK",
        "xPercent": 50,
        "yPercent": 92,
        "playerName": "Coucke",
        "playerTeamCode": "CER",
        "playerPosition": "GK",
        "playerPrice": 5.5,
        "safety": "darkgreen"
      },
      {
        "positionId": "LWB",
        "role": "LWB",
        "broadPosition": "DEF",
        "xPercent": 16,
        "yPercent": 64,
        "playerName": "Konate",
        "playerTeamCode": "CER",
        "playerPosition": "DEF",
        "playerPrice": 4.5,
        "safety": "darkgreen"
      },
      {
        "positionId": "LCB",
        "role": "LCB",
        "broadPosition": "DEF",
        "xPercent": 30,
        "yPercent": 79,
        "playerName": "Kondo",
        "playerTeamCode": "CER",
        "playerPosition": "DEF",
        "playerPrice": 5,
        "safety": "darkgreen"
      },
      {
        "positionId": "CCB",
        "role": "CCB",
        "broadPosition": "DEF",
        "xPercent": 50,
        "yPercent": 81,
        "playerName": "Ravych",
        "playerTeamCode": "CER",
        "playerPosition": "DEF",
        "playerPrice": 6.5,
        "safety": "darkgreen"
      },
      {
        "positionId": "RCB",
        "role": "RCB",
        "broadPosition": "DEF",
        "xPercent": 70,
        "yPercent": 79,
        "playerName": "Kakou",
        "playerTeamCode": "CER",
        "playerPosition": "DEF",
        "playerPrice": 5.5,
        "safety": "darkgreen"
      },
      {
        "positionId": "RWB",
        "role": "RWB",
        "broadPosition": "DEF",
        "xPercent": 84,
        "yPercent": 64,
        "playerName": "Magnee",
        "playerTeamCode": "CER",
        "playerPosition": "DEF",
        "playerPrice": 6.5,
        "safety": "green"
      },
      {
        "positionId": "LCM",
        "role": "LCM",
        "broadPosition": "MID",
        "xPercent": 35,
        "yPercent": 47,
        "playerName": "Diaby",
        "playerTeamCode": "CER",
        "playerPosition": "MID",
        "playerPrice": 6,
        "safety": "darkgreen"
      },
      {
        "positionId": "CAM",
        "role": "CAM",
        "broadPosition": "MID",
        "xPercent": 50,
        "yPercent": 28,
        "playerName": "Amani",
        "playerTeamCode": "CER",
        "playerPosition": "MID",
        "playerPrice": 6.5,
        "safety": "red"
      },
      {
        "positionId": "RCM",
        "role": "RCM",
        "broadPosition": "MID",
        "xPercent": 65,
        "yPercent": 47,
        "playerName": "Mondele",
        "playerTeamCode": "CER",
        "playerPosition": "MID",
        "playerPrice": 4,
        "safety": "red"
      },
      {
        "positionId": "LST",
        "role": "LST",
        "broadPosition": "FWD",
        "xPercent": 35,
        "yPercent": 10,
        "playerName": "Vanzeir",
        "playerTeamCode": "CER",
        "playerPosition": "FWD",
        "playerPrice": 7,
        "safety": "darkgreen"
      },
      {
        "positionId": "RST",
        "role": "RST",
        "broadPosition": "FWD",
        "xPercent": 65,
        "yPercent": 10,
        "playerName": "Ngoura",
        "playerTeamCode": "CER",
        "playerPosition": "FWD",
        "playerPrice": 6.5,
        "safety": "darkgreen"
      },
      {
        "positionId": "_unassigned",
        "role": "FWD",
        "broadPosition": "FWD",
        "xPercent": 0,
        "yPercent": 0,
        "playerName": "Ngoura",
        "playerTeamCode": "CER",
        "playerPosition": "FWD",
        "playerPrice": 6.5,
        "safety": "green"
      },
      {
        "positionId": "_unassigned",
        "role": "FWD",
        "broadPosition": "FWD",
        "xPercent": 0,
        "yPercent": 0,
        "playerName": "Ngoura",
        "playerTeamCode": "CER",
        "playerPosition": "FWD",
        "playerPrice": 6.5,
        "safety": "green"
      }
    ],
    "notes": "",
    "label": "",
    "createdAt": 1785952247732,
    "updatedAt": 1786020274026
  },
  {
    "id": "10c4cefb-340f-48ec-98de-081dc4f39e0d",
    "clubCode": "CLU",
    "opponentCode": "KOR",
    "formationKey": "4-3-3",
    "lastUpdatedLabel": "vrijdag 07 augustus 14:10",
    "slots": [
      {
        "positionId": "GK",
        "role": "GK",
        "broadPosition": "GK",
        "xPercent": 50,
        "yPercent": 92,
        "playerName": "Sommer",
        "playerTeamCode": "CLU",
        "playerPosition": "GK",
        "playerPrice": 8,
        "safety": "darkgreen"
      },
      {
        "positionId": "LWB",
        "role": "LWB",
        "broadPosition": "DEF",
        "xPercent": 16,
        "yPercent": 64,
        "playerName": "Seys",
        "playerTeamCode": "CLU",
        "playerPosition": "DEF",
        "playerPrice": 7,
        "safety": "darkgreen"
      },
      {
        "positionId": "LCB",
        "role": "LCB",
        "broadPosition": "DEF",
        "xPercent": 30,
        "yPercent": 79,
        "playerName": "Mechele",
        "playerTeamCode": "CLU",
        "playerPosition": "DEF",
        "playerPrice": 8,
        "safety": "darkgreen"
      },
      {
        "positionId": "RCB",
        "role": "RCB",
        "broadPosition": "DEF",
        "xPercent": 70,
        "yPercent": 79,
        "playerName": "Lee",
        "playerTeamCode": "CLU",
        "playerPosition": "DEF",
        "playerPrice": 6.5,
        "safety": "red"
      },
      {
        "positionId": "RWB",
        "role": "RWB",
        "broadPosition": "DEF",
        "xPercent": 84,
        "yPercent": 64,
        "playerName": "Sabbe",
        "playerTeamCode": "CLU",
        "playerPosition": "DEF",
        "playerPrice": 6.5,
        "safety": "darkgreen"
      },
      {
        "positionId": "LCM",
        "role": "LCM",
        "broadPosition": "MID",
        "xPercent": 35,
        "yPercent": 47,
        "playerName": "Vetlesen",
        "playerTeamCode": "CLU",
        "playerPosition": "MID",
        "playerPrice": 7,
        "safety": "darkgreen"
      },
      {
        "positionId": "CAM",
        "role": "CAM",
        "broadPosition": "MID",
        "xPercent": 50,
        "yPercent": 28,
        "playerName": "Vanaken",
        "playerTeamCode": "CLU",
        "playerPosition": "MID",
        "playerPrice": 11.5,
        "safety": "darkgreen"
      },
      {
        "positionId": "RCM",
        "role": "RCM",
        "broadPosition": "MID",
        "xPercent": 65,
        "yPercent": 47,
        "playerName": "Potts",
        "playerTeamCode": "CLU",
        "playerPosition": "MID",
        "playerPrice": 7,
        "safety": "red"
      },
      {
        "positionId": "LW",
        "role": "LW",
        "broadPosition": "FWD",
        "xPercent": 12,
        "yPercent": 18,
        "playerName": "Diakhon",
        "playerTeamCode": "CLU",
        "playerPosition": "MID",
        "playerPrice": 7.5,
        "safety": "green"
      },
      {
        "positionId": "ST",
        "role": "ST",
        "broadPosition": "FWD",
        "xPercent": 50,
        "yPercent": 5,
        "playerName": "Tresoldi",
        "playerTeamCode": "CLU",
        "playerPosition": "FWD",
        "playerPrice": 10.5,
        "safety": "darkgreen"
      },
      {
        "positionId": "RW",
        "role": "RW",
        "broadPosition": "FWD",
        "xPercent": 88,
        "yPercent": 18,
        "playerName": "Forbs",
        "playerTeamCode": "CLU",
        "playerPosition": "MID",
        "playerPrice": 8,
        "safety": "darkgreen"
      },
      {
        "positionId": "_unassigned",
        "role": "DEF",
        "broadPosition": "DEF",
        "xPercent": 0,
        "yPercent": 0,
        "playerName": "Sabbe",
        "playerTeamCode": "CLU",
        "playerPosition": "DEF",
        "playerPrice": 6.5,
        "safety": "green"
      }
    ],
    "notes": "",
    "label": "",
    "createdAt": 1785973101792,
    "updatedAt": 1786019841955
  },
  {
    "id": "9a9f4406-37a5-4ad2-85a2-ede93b669df9",
    "clubCode": "KVM",
    "opponentCode": "GNT",
    "formationKey": "4-3-3",
    "lastUpdatedLabel": "donderdag 06 augustus 18:00",
    "slots": [
      {
        "positionId": "GK",
        "role": "GK",
        "broadPosition": "GK",
        "xPercent": 50,
        "yPercent": 92,
        "playerName": "Miras",
        "playerTeamCode": "KVM",
        "playerPosition": "GK",
        "playerPrice": 6.5,
        "safety": "darkgreen"
      },
      {
        "positionId": "LWB",
        "role": "LWB",
        "broadPosition": "DEF",
        "xPercent": 16,
        "yPercent": 64,
        "playerName": "Marsa",
        "playerTeamCode": "KVM",
        "playerPosition": "DEF",
        "playerPrice": 5.5,
        "safety": "red"
      },
      {
        "positionId": "LCB",
        "role": "LCB",
        "broadPosition": "DEF",
        "xPercent": 30,
        "yPercent": 79,
        "playerName": "Diouf",
        "playerTeamCode": "KVM",
        "playerPosition": "DEF",
        "playerPrice": 4.5,
        "safety": "darkgreen"
      },
      {
        "positionId": "RCB",
        "role": "RCB",
        "broadPosition": "DEF",
        "xPercent": 70,
        "yPercent": 79,
        "playerName": "Decoene",
        "playerTeamCode": "KVM",
        "playerPosition": "MID",
        "playerPrice": 4,
        "safety": "green"
      },
      {
        "positionId": "RWB",
        "role": "RWB",
        "broadPosition": "DEF",
        "xPercent": 84,
        "yPercent": 64,
        "playerName": "Corbanie",
        "playerTeamCode": "KVM",
        "playerPosition": "DEF",
        "playerPrice": 6,
        "safety": "darkgreen"
      },
      {
        "positionId": "LCM",
        "role": "LCM",
        "broadPosition": "MID",
        "xPercent": 35,
        "yPercent": 47,
        "playerName": "Salifou",
        "playerTeamCode": "KVM",
        "playerPosition": "MID",
        "playerPrice": 5,
        "safety": "darkgreen"
      },
      {
        "positionId": "RCM",
        "role": "RCM",
        "broadPosition": "MID",
        "xPercent": 65,
        "yPercent": 47,
        "playerName": "Hammar",
        "playerTeamCode": "KVM",
        "playerPosition": "MID",
        "playerPrice": 7,
        "safety": "darkgreen"
      },
      {
        "positionId": "CAM",
        "role": "CAM",
        "broadPosition": "MID",
        "xPercent": 50,
        "yPercent": 28,
        "playerName": "Praet",
        "playerTeamCode": "KVM",
        "playerPosition": "MID",
        "playerPrice": 7,
        "safety": "darkgreen"
      },
      {
        "positionId": "LW",
        "role": "LW",
        "broadPosition": "FWD",
        "xPercent": 16,
        "yPercent": 18,
        "playerName": "Van Brederode",
        "playerTeamCode": "KVM",
        "playerPosition": "FWD",
        "playerPrice": 7,
        "safety": "darkgreen"
      },
      {
        "positionId": "ST",
        "role": "ST",
        "broadPosition": "FWD",
        "xPercent": 50,
        "yPercent": 5,
        "playerName": "Raman",
        "playerTeamCode": "KVM",
        "playerPosition": "FWD",
        "playerPrice": 7.5,
        "safety": "darkgreen"
      },
      {
        "positionId": "RW",
        "role": "RW",
        "broadPosition": "FWD",
        "xPercent": 84,
        "yPercent": 18,
        "playerName": "Van Meirvenne",
        "playerTeamCode": "KVM",
        "playerPosition": "MID",
        "playerPrice": 5,
        "safety": "orange"
      },
      {
        "positionId": "_unassigned",
        "role": "FWD",
        "broadPosition": "FWD",
        "xPercent": 0,
        "yPercent": 0,
        "playerName": "Van Brederode",
        "playerTeamCode": "KVM",
        "playerPosition": "FWD",
        "playerPrice": 7,
        "safety": "green"
      },
      {
        "positionId": "_unassigned",
        "role": "MID",
        "broadPosition": "MID",
        "xPercent": 0,
        "yPercent": 0,
        "playerName": "Decoene",
        "playerTeamCode": "KVM",
        "playerPosition": "MID",
        "playerPrice": 4,
        "safety": "green"
      },
      {
        "positionId": "_unassigned",
        "role": "MID",
        "broadPosition": "MID",
        "xPercent": 0,
        "yPercent": 0,
        "playerName": "Decoene",
        "playerTeamCode": "KVM",
        "playerPosition": "MID",
        "playerPrice": 4,
        "safety": "green"
      }
    ],
    "notes": "",
    "label": "",
    "createdAt": 1785978472521,
    "updatedAt": 1786020806552
  },
  {
    "id": "0895f591-9fe9-467c-84b5-dc326edfcce1",
    "clubCode": "BEV",
    "opponentCode": "ANT",
    "formationKey": "4-3-3",
    "lastUpdatedLabel": "vrijdag 07 augustus 14:10",
    "slots": [
      {
        "positionId": "GK",
        "role": "GK",
        "broadPosition": "GK",
        "xPercent": 50,
        "yPercent": 92,
        "playerName": "Schenk",
        "playerTeamCode": "",
        "playerPosition": "GK",
        "playerPrice": null,
        "safety": "orange"
      },
      {
        "positionId": "LWB",
        "role": "LWB",
        "broadPosition": "DEF",
        "xPercent": 16,
        "yPercent": 64,
        "playerName": "Janssens",
        "playerTeamCode": "BEV",
        "playerPosition": "DEF",
        "playerPrice": 5,
        "safety": "red"
      },
      {
        "positionId": "LCB",
        "role": "LCB",
        "broadPosition": "DEF",
        "xPercent": 30,
        "yPercent": 79,
        "playerName": "Boone",
        "playerTeamCode": "BEV",
        "playerPosition": "DEF",
        "playerPrice": 4.5,
        "safety": "darkgreen"
      },
      {
        "positionId": "RCB",
        "role": "RCB",
        "broadPosition": "DEF",
        "xPercent": 70,
        "yPercent": 79,
        "playerName": "Godeau",
        "playerTeamCode": "BEV",
        "playerPosition": "DEF",
        "playerPrice": 5.5,
        "safety": "darkgreen"
      },
      {
        "positionId": "RWB",
        "role": "RWB",
        "broadPosition": "DEF",
        "xPercent": 84,
        "yPercent": 64,
        "playerName": "Jans",
        "playerTeamCode": "BEV",
        "playerPosition": "DEF",
        "playerPrice": 5,
        "safety": "darkgreen"
      },
      {
        "positionId": "LCM",
        "role": "LCM",
        "broadPosition": "MID",
        "xPercent": 35,
        "yPercent": 47,
        "playerName": "Slegers",
        "playerTeamCode": "BEV",
        "playerPosition": "MID",
        "playerPrice": 5.5,
        "safety": "orange"
      },
      {
        "positionId": "RCM",
        "role": "RCM",
        "broadPosition": "MID",
        "xPercent": 65,
        "yPercent": 47,
        "playerName": "Dewaele",
        "playerTeamCode": "BEV",
        "playerPosition": "MID",
        "playerPrice": 5.5,
        "safety": "darkgreen"
      },
      {
        "positionId": "CAM",
        "role": "CAM",
        "broadPosition": "MID",
        "xPercent": 50,
        "yPercent": 28,
        "playerName": "Bruls",
        "playerTeamCode": "BEV",
        "playerPosition": "MID",
        "playerPrice": 6.5,
        "safety": "darkgreen"
      },
      {
        "positionId": "LW",
        "role": "LW",
        "broadPosition": "FWD",
        "xPercent": 16,
        "yPercent": 18,
        "playerName": "Margaritha",
        "playerTeamCode": "BEV",
        "playerPosition": "MID",
        "playerPrice": 6.5,
        "safety": "red"
      },
      {
        "positionId": "ST",
        "role": "ST",
        "broadPosition": "FWD",
        "xPercent": 50,
        "yPercent": 5,
        "playerName": "Mertens",
        "playerTeamCode": "BEV",
        "playerPosition": "FWD",
        "playerPrice": 7.5,
        "safety": "darkgreen"
      },
      {
        "positionId": "RW",
        "role": "RW",
        "broadPosition": "FWD",
        "xPercent": 84,
        "yPercent": 18,
        "playerName": "Lokesa",
        "playerTeamCode": "BEV",
        "playerPosition": "MID",
        "playerPrice": 5,
        "safety": "red"
      },
      {
        "positionId": "_unassigned",
        "role": "MID",
        "broadPosition": "MID",
        "xPercent": 0,
        "yPercent": 0,
        "playerName": "Dewaele",
        "playerTeamCode": "BEV",
        "playerPosition": "MID",
        "playerPrice": 5.5,
        "safety": "green"
      }
    ],
    "notes": "",
    "label": "",
    "createdAt": 1785978640043,
    "updatedAt": 1786030237447
  },
  {
    "id": "1e5bdc31-a84f-4757-8b5e-5034e1680126",
    "clubCode": "ANT",
    "opponentCode": "BEV",
    "formationKey": "4-3-3",
    "lastUpdatedLabel": "vrijdag 07 augustus 15:00",
    "slots": [
      {
        "positionId": "GK",
        "role": "GK",
        "broadPosition": "GK",
        "xPercent": 50,
        "yPercent": 92,
        "playerName": "Nozawa",
        "playerTeamCode": "ANT",
        "playerPosition": "GK",
        "playerPrice": 6,
        "safety": "darkgreen"
      },
      {
        "positionId": "LWB",
        "role": "LWB",
        "broadPosition": "DEF",
        "xPercent": 16,
        "yPercent": 64,
        "playerName": "Tuypens",
        "playerTeamCode": "ANT",
        "playerPosition": "DEF",
        "playerPrice": 4,
        "safety": "orange"
      },
      {
        "positionId": "LCB",
        "role": "LCB",
        "broadPosition": "DEF",
        "xPercent": 30,
        "yPercent": 79,
        "playerName": "Tsunashima",
        "playerTeamCode": "ANT",
        "playerPosition": "MID",
        "playerPrice": 6,
        "safety": "red"
      },
      {
        "positionId": "RCB",
        "role": "RCB",
        "broadPosition": "DEF",
        "xPercent": 70,
        "yPercent": 79,
        "playerName": "Van Helden",
        "playerTeamCode": "ANT",
        "playerPosition": "DEF",
        "playerPrice": 6.5,
        "safety": "darkgreen"
      },
      {
        "positionId": "RWB",
        "role": "RWB",
        "broadPosition": "DEF",
        "xPercent": 84,
        "yPercent": 64,
        "playerName": "Renders",
        "playerTeamCode": "ANT",
        "playerPosition": "DEF",
        "playerPrice": 5,
        "safety": "green"
      },
      {
        "positionId": "LCM",
        "role": "LCM",
        "broadPosition": "MID",
        "xPercent": 35,
        "yPercent": 47,
        "playerName": "Fofana",
        "playerTeamCode": "ANT",
        "playerPosition": "MID",
        "playerPrice": 4.5,
        "safety": "red"
      },
      {
        "positionId": "CAM",
        "role": "CAM",
        "broadPosition": "MID",
        "xPercent": 50,
        "yPercent": 28,
        "playerName": "Scott",
        "playerTeamCode": "ANT",
        "playerPosition": "MID",
        "playerPrice": 6.5,
        "safety": "darkgreen"
      },
      {
        "positionId": "RCM",
        "role": "RCM",
        "broadPosition": "MID",
        "xPercent": 65,
        "yPercent": 47,
        "playerName": "Dierckx",
        "playerTeamCode": "ANT",
        "playerPosition": "MID",
        "playerPrice": 5,
        "safety": "darkgreen"
      },
      {
        "positionId": "LW",
        "role": "LW",
        "broadPosition": "FWD",
        "xPercent": 16,
        "yPercent": 18,
        "playerName": "Salah",
        "playerTeamCode": "ANT",
        "playerPosition": "MID",
        "playerPrice": 6,
        "safety": "red"
      },
      {
        "positionId": "ST",
        "role": "ST",
        "broadPosition": "FWD",
        "xPercent": 50,
        "yPercent": 5,
        "playerName": "Vandeplas",
        "playerTeamCode": "ANT",
        "playerPosition": "FWD",
        "playerPrice": 5.5,
        "safety": "red"
      },
      {
        "positionId": "RW",
        "role": "RW",
        "broadPosition": "FWD",
        "xPercent": 84,
        "yPercent": 18,
        "playerName": "Hairemans",
        "playerTeamCode": "ANT",
        "playerPosition": "MID",
        "playerPrice": 6.5,
        "safety": "red"
      },
      {
        "positionId": "_unassigned",
        "role": "MID",
        "broadPosition": "MID",
        "xPercent": 0,
        "yPercent": 0,
        "playerName": "Verstraeten",
        "playerTeamCode": "ANT",
        "playerPosition": "MID",
        "playerPrice": 5.5,
        "safety": "green"
      },
      {
        "positionId": "_unassigned",
        "role": "MID",
        "broadPosition": "MID",
        "xPercent": 0,
        "yPercent": 0,
        "playerName": "Verstraeten",
        "playerTeamCode": "ANT",
        "playerPosition": "MID",
        "playerPrice": 5.5,
        "safety": "green"
      }
    ],
    "notes": "",
    "label": "",
    "createdAt": 1785978877154,
    "updatedAt": 1786030265749
  },
  {
    "id": "d4b659e3-d05d-4927-8760-9c1962df7ab0",
    "clubCode": "LLV",
    "opponentCode": "AND",
    "formationKey": "5-3-2",
    "lastUpdatedLabel": "donderdag 06 augustus 18:00",
    "slots": [
      {
        "positionId": "GK",
        "role": "GK",
        "broadPosition": "GK",
        "xPercent": 50,
        "yPercent": 92,
        "playerName": "Pereira Cardoso",
        "playerTeamCode": "LLV",
        "playerPosition": "GK",
        "playerPrice": 5,
        "safety": "orange"
      },
      {
        "positionId": "LWB",
        "role": "LWB",
        "broadPosition": "DEF",
        "xPercent": 16,
        "yPercent": 64,
        "playerName": "Lutonda",
        "playerTeamCode": "LLV",
        "playerPosition": "DEF",
        "playerPrice": 5,
        "safety": "darkgreen"
      },
      {
        "positionId": "LCB",
        "role": "LCB",
        "broadPosition": "DEF",
        "xPercent": 30,
        "yPercent": 79,
        "playerName": "Okou",
        "playerTeamCode": "LLV",
        "playerPosition": "DEF",
        "playerPrice": 5,
        "safety": "green"
      },
      {
        "positionId": "CCB",
        "role": "CCB",
        "broadPosition": "DEF",
        "xPercent": 50,
        "yPercent": 81,
        "playerName": "Nkoa",
        "playerTeamCode": "LLV",
        "playerPosition": "DEF",
        "playerPrice": 4.5,
        "safety": "red"
      },
      {
        "positionId": "RCB",
        "role": "RCB",
        "broadPosition": "DEF",
        "xPercent": 70,
        "yPercent": 79,
        "playerName": "Faye",
        "playerTeamCode": "LLV",
        "playerPosition": "DEF",
        "playerPrice": 5.5,
        "safety": "darkgreen"
      },
      {
        "positionId": "RWB",
        "role": "RWB",
        "broadPosition": "DEF",
        "xPercent": 84,
        "yPercent": 64,
        "playerName": "Delos",
        "playerTeamCode": "LLV",
        "playerPosition": "DEF",
        "playerPrice": 5,
        "safety": "green"
      },
      {
        "positionId": "CAM",
        "role": "CAM",
        "broadPosition": "MID",
        "xPercent": 50,
        "yPercent": 28,
        "playerName": "Ito",
        "playerTeamCode": "LLV",
        "playerPosition": "MID",
        "playerPrice": 6.5,
        "safety": "green"
      },
      {
        "positionId": "LCM",
        "role": "LCM",
        "broadPosition": "MID",
        "xPercent": 35,
        "yPercent": 47,
        "playerName": "Wade",
        "playerTeamCode": "LLV",
        "playerPosition": "MID",
        "playerPrice": 6,
        "safety": "orange"
      },
      {
        "positionId": "RCM",
        "role": "RCM",
        "broadPosition": "MID",
        "xPercent": 65,
        "yPercent": 47,
        "playerName": "Coulibaly",
        "playerTeamCode": "LLV",
        "playerPosition": "MID",
        "playerPrice": 5,
        "safety": "green"
      },
      {
        "positionId": "LST",
        "role": "LST",
        "broadPosition": "FWD",
        "xPercent": 28,
        "yPercent": 11,
        "playerName": "Filet",
        "playerTeamCode": "LLV",
        "playerPosition": "FWD",
        "playerPrice": 5.5,
        "safety": "darkgreen"
      },
      {
        "positionId": "RST",
        "role": "RST",
        "broadPosition": "FWD",
        "xPercent": 72,
        "yPercent": 11,
        "playerName": "Isah",
        "playerTeamCode": "LLV",
        "playerPosition": "FWD",
        "playerPrice": 4.5,
        "safety": "red"
      }
    ],
    "notes": "",
    "label": "",
    "createdAt": 1785979157555,
    "updatedAt": 1786020673419
  },
  {
    "id": "5b43acd3-36ad-4bf9-aa76-59841e9b3eba",
    "clubCode": "GNK",
    "opponentCode": "ZWA",
    "formationKey": "4-3-3",
    "lastUpdatedLabel": "vrijdag 07 augustus 15:00",
    "slots": [
      {
        "positionId": "GK",
        "role": "GK",
        "broadPosition": "GK",
        "xPercent": 50,
        "yPercent": 92,
        "playerName": "Brughmans",
        "playerTeamCode": "GNK",
        "playerPosition": "GK",
        "playerPrice": 6,
        "safety": "darkgreen"
      },
      {
        "positionId": "LWB",
        "role": "LWB",
        "broadPosition": "DEF",
        "xPercent": 16,
        "yPercent": 64,
        "playerName": "Kayembe",
        "playerTeamCode": "GNK",
        "playerPosition": "DEF",
        "playerPrice": 7,
        "safety": "green"
      },
      {
        "positionId": "LCB",
        "role": "LCB",
        "broadPosition": "DEF",
        "xPercent": 30,
        "yPercent": 79,
        "playerName": "Kongolo",
        "playerTeamCode": "GNK",
        "playerPosition": "DEF",
        "playerPrice": 5,
        "safety": "darkgreen"
      },
      {
        "positionId": "RCB",
        "role": "RCB",
        "broadPosition": "DEF",
        "xPercent": 70,
        "yPercent": 79,
        "playerName": "Smets",
        "playerTeamCode": "GNK",
        "playerPosition": "MID",
        "playerPrice": 7.5,
        "safety": "red"
      },
      {
        "positionId": "RWB",
        "role": "RWB",
        "broadPosition": "DEF",
        "xPercent": 84,
        "yPercent": 64,
        "playerName": "El Ouahdi",
        "playerTeamCode": "",
        "playerPosition": "DEF",
        "playerPrice": 8,
        "safety": "red"
      },
      {
        "positionId": "LCM",
        "role": "LCM",
        "broadPosition": "MID",
        "xPercent": 35,
        "yPercent": 47,
        "playerName": "Bangoura",
        "playerTeamCode": "GNK",
        "playerPosition": "MID",
        "playerPrice": 6,
        "safety": "darkgreen"
      },
      {
        "positionId": "CAM",
        "role": "CAM",
        "broadPosition": "MID",
        "xPercent": 50,
        "yPercent": 28,
        "playerName": "Heymans",
        "playerTeamCode": "GNK",
        "playerPosition": "MID",
        "playerPrice": 8.5,
        "safety": "darkgreen"
      },
      {
        "positionId": "RCM",
        "role": "RCM",
        "broadPosition": "MID",
        "xPercent": 65,
        "yPercent": 47,
        "playerName": "Heynen",
        "playerTeamCode": "GNK",
        "playerPosition": "MID",
        "playerPrice": 8.5,
        "safety": "darkgreen"
      },
      {
        "positionId": "LW",
        "role": "LW",
        "broadPosition": "FWD",
        "xPercent": 16,
        "yPercent": 18,
        "playerName": "Ito",
        "playerTeamCode": "GNK",
        "playerPosition": "MID",
        "playerPrice": 7.5,
        "safety": "green"
      },
      {
        "positionId": "ST",
        "role": "ST",
        "broadPosition": "FWD",
        "xPercent": 50,
        "yPercent": 5,
        "playerName": "Durosinmi",
        "playerTeamCode": "GNK",
        "playerPosition": "FWD",
        "playerPrice": 6.5,
        "safety": "green"
      },
      {
        "positionId": "RW",
        "role": "RW",
        "broadPosition": "FWD",
        "xPercent": 84,
        "yPercent": 18,
        "playerName": "Erenbjerg",
        "playerTeamCode": "GNK",
        "playerPosition": "MID",
        "playerPrice": 8,
        "safety": "green"
      },
      {
        "positionId": "_unassigned",
        "role": "MID",
        "broadPosition": "MID",
        "xPercent": 0,
        "yPercent": 0,
        "playerName": "Sattlberger",
        "playerTeamCode": "GNK",
        "playerPosition": "MID",
        "playerPrice": 7,
        "safety": "green"
      },
      {
        "positionId": "_unassigned",
        "role": "MID",
        "broadPosition": "MID",
        "xPercent": 0,
        "yPercent": 0,
        "playerName": "El Ouahdi",
        "playerTeamCode": "",
        "playerPosition": "MID",
        "playerPrice": "8",
        "safety": "red"
      }
    ],
    "notes": "",
    "label": "",
    "createdAt": 1785979329638,
    "updatedAt": 1786020634607
  },
  {
    "id": "4664da55-4670-451c-bf82-622710f641d4",
    "clubCode": "ZWA",
    "opponentCode": "GNK",
    "formationKey": "4-4-2",
    "lastUpdatedLabel": "donderdag 06 augustus 18:00",
    "slots": [
      {
        "positionId": "GK",
        "role": "GK",
        "broadPosition": "GK",
        "xPercent": 50,
        "yPercent": 92,
        "playerName": "Bostyn",
        "playerTeamCode": "ZWA",
        "playerPosition": "GK",
        "playerPrice": 4.5,
        "safety": "red"
      },
      {
        "positionId": "LWB",
        "role": "LWB",
        "broadPosition": "DEF",
        "xPercent": 16,
        "yPercent": 64,
        "playerName": "Cappelle",
        "playerTeamCode": "ZWA",
        "playerPosition": "DEF",
        "playerPrice": 5,
        "safety": "darkgreen"
      },
      {
        "positionId": "LCB",
        "role": "LCB",
        "broadPosition": "DEF",
        "xPercent": 30,
        "yPercent": 79,
        "playerName": "Kiilerich",
        "playerTeamCode": "ZWA",
        "playerPosition": "DEF",
        "playerPrice": 5,
        "safety": "darkgreen"
      },
      {
        "positionId": "RCB",
        "role": "RCB",
        "broadPosition": "DEF",
        "xPercent": 70,
        "yPercent": 79,
        "playerName": "Lemoine",
        "playerTeamCode": "ZWA",
        "playerPosition": "DEF",
        "playerPrice": 5,
        "safety": "darkgreen"
      },
      {
        "positionId": "RWB",
        "role": "RWB",
        "broadPosition": "DEF",
        "xPercent": 84,
        "yPercent": 64,
        "playerName": "Paugain",
        "playerTeamCode": "ZWA",
        "playerPosition": "DEF",
        "playerPrice": 5,
        "safety": "darkgreen"
      },
      {
        "positionId": "LM",
        "role": "LM",
        "broadPosition": "MID",
        "xPercent": 16,
        "yPercent": 47,
        "playerName": "Ake",
        "playerTeamCode": "ZWA",
        "playerPosition": "MID",
        "playerPrice": 5.5,
        "safety": "darkgreen"
      },
      {
        "positionId": "LCM",
        "role": "LCM",
        "broadPosition": "MID",
        "xPercent": 35,
        "yPercent": 47,
        "playerName": "Lofolomo",
        "playerTeamCode": "ZWA",
        "playerPosition": "MID",
        "playerPrice": 5,
        "safety": "darkgreen"
      },
      {
        "positionId": "RCM",
        "role": "RCM",
        "broadPosition": "MID",
        "xPercent": 65,
        "yPercent": 47,
        "playerName": "Claes",
        "playerTeamCode": "ZWA",
        "playerPosition": "MID",
        "playerPrice": 5,
        "safety": "darkgreen"
      },
      {
        "positionId": "RM",
        "role": "RM",
        "broadPosition": "MID",
        "xPercent": 84,
        "yPercent": 47,
        "playerName": "Atrok",
        "playerTeamCode": "ZWA",
        "playerPosition": "MID",
        "playerPrice": 4.5,
        "safety": "green"
      },
      {
        "positionId": "LST",
        "role": "LST",
        "broadPosition": "FWD",
        "xPercent": 28,
        "yPercent": 11,
        "playerName": "Hedl",
        "playerTeamCode": "ZWA",
        "playerPosition": "FWD",
        "playerPrice": 6,
        "safety": "green"
      },
      {
        "positionId": "RST",
        "role": "RST",
        "broadPosition": "FWD",
        "xPercent": 72,
        "yPercent": 11,
        "playerName": "Ementa",
        "playerTeamCode": "ZWA",
        "playerPosition": "FWD",
        "playerPrice": 6.5,
        "safety": "darkgreen"
      }
    ],
    "notes": "",
    "label": "",
    "createdAt": 1785979497409,
    "updatedAt": 1786020583311
  },
  {
    "id": "d3195e23-e623-4756-a995-01095b61d134",
    "clubCode": "OHL",
    "opponentCode": "CHA",
    "formationKey": "5-3-2",
    "lastUpdatedLabel": "donderdag 06 augustus 18:00",
    "slots": [
      {
        "positionId": "GK",
        "role": "GK",
        "broadPosition": "GK",
        "xPercent": 50,
        "yPercent": 92,
        "playerName": "Van den Heuvel",
        "playerTeamCode": "OHL",
        "playerPosition": "GK",
        "playerPrice": 5,
        "safety": "green"
      },
      {
        "positionId": "LWB",
        "role": "LWB",
        "broadPosition": "DEF",
        "xPercent": 16,
        "yPercent": 64,
        "playerName": "Opoku",
        "playerTeamCode": "OHL",
        "playerPosition": "DEF",
        "playerPrice": 4.5,
        "safety": "red"
      },
      {
        "positionId": "LCB",
        "role": "LCB",
        "broadPosition": "DEF",
        "xPercent": 30,
        "yPercent": 79,
        "playerName": "Dussenne",
        "playerTeamCode": "OHL",
        "playerPosition": "DEF",
        "playerPrice": 5,
        "safety": "darkgreen"
      },
      {
        "positionId": "CCB",
        "role": "CCB",
        "broadPosition": "DEF",
        "xPercent": 50,
        "yPercent": 81,
        "playerName": "Kayo",
        "playerTeamCode": "OHL",
        "playerPosition": "MID",
        "playerPrice": 5.5,
        "safety": "red"
      },
      {
        "positionId": "RCB",
        "role": "RCB",
        "broadPosition": "DEF",
        "xPercent": 70,
        "yPercent": 79,
        "playerName": "Pletinckx",
        "playerTeamCode": "OHL",
        "playerPosition": "DEF",
        "playerPrice": 5.5,
        "safety": "darkgreen"
      },
      {
        "positionId": "RWB",
        "role": "RWB",
        "broadPosition": "DEF",
        "xPercent": 84,
        "yPercent": 64,
        "playerName": "Gil",
        "playerTeamCode": "OHL",
        "playerPosition": "DEF",
        "playerPrice": 5.5,
        "safety": "green"
      },
      {
        "positionId": "LCM",
        "role": "LCM",
        "broadPosition": "MID",
        "xPercent": 35,
        "yPercent": 47,
        "playerName": "Lakomy",
        "playerTeamCode": "OHL",
        "playerPosition": "MID",
        "playerPrice": 5,
        "safety": "green"
      },
      {
        "positionId": "CAM",
        "role": "CAM",
        "broadPosition": "MID",
        "xPercent": 50,
        "yPercent": 28,
        "playerName": "Balikwisha",
        "playerTeamCode": "OHL",
        "playerPosition": "MID",
        "playerPrice": 7,
        "safety": "green"
      },
      {
        "positionId": "RCM",
        "role": "RCM",
        "broadPosition": "MID",
        "xPercent": 65,
        "yPercent": 47,
        "playerName": "Schrijvers",
        "playerTeamCode": "OHL",
        "playerPosition": "MID",
        "playerPrice": 8,
        "safety": "red"
      },
      {
        "positionId": "LST",
        "role": "LST",
        "broadPosition": "FWD",
        "xPercent": 28,
        "yPercent": 11,
        "playerName": "Ikwuemesi",
        "playerTeamCode": "OHL",
        "playerPosition": "FWD",
        "playerPrice": 6.5,
        "safety": "green"
      },
      {
        "positionId": "RST",
        "role": "RST",
        "broadPosition": "FWD",
        "xPercent": 72,
        "yPercent": 11,
        "playerName": "Traore",
        "playerTeamCode": "OHL",
        "playerPosition": "FWD",
        "playerPrice": 6,
        "safety": "red"
      },
      {
        "positionId": "_unassigned",
        "role": "MID",
        "broadPosition": "MID",
        "xPercent": 0,
        "yPercent": 0,
        "playerName": "Kayo",
        "playerTeamCode": "OHL",
        "playerPosition": "MID",
        "playerPrice": 5.5,
        "safety": "green"
      }
    ],
    "notes": "",
    "label": "",
    "createdAt": 1785979710255,
    "updatedAt": 1786020527464
  },
  {
    "id": "ac2fbad9-d9b2-44b2-b843-c32832359f74",
    "clubCode": "CHA",
    "opponentCode": "OHL",
    "formationKey": "4-3-3",
    "lastUpdatedLabel": "vrijdag 07 augustus 14:15",
    "slots": [
      {
        "positionId": "GK",
        "role": "GK",
        "broadPosition": "GK",
        "xPercent": 50,
        "yPercent": 92,
        "playerName": "Kone",
        "playerTeamCode": "CHA",
        "playerPosition": "GK",
        "playerPrice": 5.5,
        "safety": "darkgreen"
      },
      {
        "positionId": "LWB",
        "role": "LWB",
        "broadPosition": "DEF",
        "xPercent": 16,
        "yPercent": 64,
        "playerName": "Nzita",
        "playerTeamCode": "CHA",
        "playerPosition": "DEF",
        "playerPrice": 5.5,
        "safety": "darkgreen"
      },
      {
        "positionId": "LCB",
        "role": "LCB",
        "broadPosition": "DEF",
        "xPercent": 30,
        "yPercent": 79,
        "playerName": "Ousou",
        "playerTeamCode": "CHA",
        "playerPosition": "DEF",
        "playerPrice": 6.5,
        "safety": "darkgreen"
      },
      {
        "positionId": "RCB",
        "role": "RCB",
        "broadPosition": "DEF",
        "xPercent": 70,
        "yPercent": 79,
        "playerName": "Keita",
        "playerTeamCode": "CHA",
        "playerPosition": "DEF",
        "playerPrice": 6,
        "safety": "green"
      },
      {
        "positionId": "RWB",
        "role": "RWB",
        "broadPosition": "DEF",
        "xPercent": 84,
        "yPercent": 64,
        "playerName": "Van Den Kerkhof",
        "playerTeamCode": "CHA",
        "playerPosition": "DEF",
        "playerPrice": 5.5,
        "safety": "darkgreen"
      },
      {
        "positionId": "LCM",
        "role": "LCM",
        "broadPosition": "MID",
        "xPercent": 35,
        "yPercent": 47,
        "playerName": "Boukamir A.",
        "playerTeamCode": "CHA",
        "playerPosition": "DEF",
        "playerPrice": 4.5,
        "safety": "darkgreen"
      },
      {
        "positionId": "CAM",
        "role": "CAM",
        "broadPosition": "MID",
        "xPercent": 50,
        "yPercent": 28,
        "playerName": "Pflucke",
        "playerTeamCode": "CHA",
        "playerPosition": "MID",
        "playerPrice": 7,
        "safety": "orange"
      },
      {
        "positionId": "RCM",
        "role": "RCM",
        "broadPosition": "MID",
        "xPercent": 65,
        "yPercent": 47,
        "playerName": "Khalifi",
        "playerTeamCode": "CHA",
        "playerPosition": "MID",
        "playerPrice": 4.5,
        "safety": "darkgreen"
      },
      {
        "positionId": "LW",
        "role": "LW",
        "broadPosition": "FWD",
        "xPercent": 16,
        "yPercent": 18,
        "playerName": "Guiagon",
        "playerTeamCode": "CHA",
        "playerPosition": "MID",
        "playerPrice": 8.5,
        "safety": "darkgreen"
      },
      {
        "positionId": "ST",
        "role": "ST",
        "broadPosition": "FWD",
        "xPercent": 50,
        "yPercent": 5,
        "playerName": "Scheidler",
        "playerTeamCode": "CHA",
        "playerPosition": "FWD",
        "playerPrice": 8.5,
        "safety": "green"
      },
      {
        "positionId": "RW",
        "role": "RW",
        "broadPosition": "FWD",
        "xPercent": 84,
        "yPercent": 18,
        "playerName": "Bernier",
        "playerTeamCode": "CHA",
        "playerPosition": "MID",
        "playerPrice": 7,
        "safety": "darkgreen"
      },
      {
        "positionId": "_unassigned",
        "role": "MID",
        "broadPosition": "MID",
        "xPercent": 0,
        "yPercent": 0,
        "playerName": "Mofokeng",
        "playerTeamCode": "USG",
        "playerPosition": "MID",
        "playerPrice": 7.5,
        "safety": "green"
      }
    ],
    "notes": "",
    "label": "",
    "createdAt": 1785979879326,
    "updatedAt": 1786020496455
  },
  {
    "id": "2cab6cab-847c-45b7-967c-657a69df6c86",
    "clubCode": "USG",
    "opponentCode": "WES",
    "formationKey": "3-5-2",
    "lastUpdatedLabel": "donderdag 06 augustus 18:00",
    "slots": [
      {
        "positionId": "GK",
        "role": "GK",
        "broadPosition": "GK",
        "xPercent": 50,
        "yPercent": 92,
        "playerName": "Koffi",
        "playerTeamCode": "USG",
        "playerPosition": "GK",
        "playerPrice": 6.5,
        "safety": "orange"
      },
      {
        "positionId": "LCB",
        "role": "LCB",
        "broadPosition": "DEF",
        "xPercent": 30,
        "yPercent": 79,
        "playerName": "Havenaar",
        "playerTeamCode": "USG",
        "playerPosition": "DEF",
        "playerPrice": 5.5,
        "safety": "green"
      },
      {
        "positionId": "CCB",
        "role": "CCB",
        "broadPosition": "DEF",
        "xPercent": 50,
        "yPercent": 81,
        "playerName": "Sylla",
        "playerTeamCode": "USG",
        "playerPosition": "DEF",
        "playerPrice": 5,
        "safety": "orange"
      },
      {
        "positionId": "RCB",
        "role": "RCB",
        "broadPosition": "DEF",
        "xPercent": 70,
        "yPercent": 79,
        "playerName": "Mac Allister",
        "playerTeamCode": "USG",
        "playerPosition": "DEF",
        "playerPrice": 8,
        "safety": "darkgreen"
      },
      {
        "positionId": "LWB",
        "role": "LWB",
        "broadPosition": "DEF",
        "xPercent": 16,
        "yPercent": 64,
        "playerName": "Smith",
        "playerTeamCode": "USG",
        "playerPosition": "FWD",
        "playerPrice": 6.5,
        "safety": "orange"
      },
      {
        "positionId": "LCM",
        "role": "LCM",
        "broadPosition": "MID",
        "xPercent": 35,
        "yPercent": 47,
        "playerName": "Van de Perre",
        "playerTeamCode": "USG",
        "playerPosition": "MID",
        "playerPrice": 7,
        "safety": "green"
      },
      {
        "positionId": "CAM",
        "role": "CAM",
        "broadPosition": "MID",
        "xPercent": 50,
        "yPercent": 28,
        "playerName": "Zeneli",
        "playerTeamCode": "USG",
        "playerPosition": "MID",
        "playerPrice": 6.5,
        "safety": "red"
      },
      {
        "positionId": "RCM",
        "role": "RCM",
        "broadPosition": "MID",
        "xPercent": 65,
        "yPercent": 47,
        "playerName": "Schoofs",
        "playerTeamCode": "USG",
        "playerPosition": "MID",
        "playerPrice": 9,
        "safety": "green"
      },
      {
        "positionId": "RWB",
        "role": "RWB",
        "broadPosition": "DEF",
        "xPercent": 84,
        "yPercent": 64,
        "playerName": "Khalaili",
        "playerTeamCode": "USG",
        "playerPosition": "MID",
        "playerPrice": 10,
        "safety": "red"
      },
      {
        "positionId": "LST",
        "role": "LST",
        "broadPosition": "FWD",
        "xPercent": 28,
        "yPercent": 11,
        "playerName": "David",
        "playerTeamCode": "USG",
        "playerPosition": "FWD",
        "playerPrice": 10,
        "safety": "red"
      },
      {
        "positionId": "RST",
        "role": "RST",
        "broadPosition": "FWD",
        "xPercent": 72,
        "yPercent": 11,
        "playerName": "Florucz",
        "playerTeamCode": "USG",
        "playerPosition": "MID",
        "playerPrice": 8.5,
        "safety": "darkgreen"
      },
      {
        "positionId": "_unassigned",
        "role": "FWD",
        "broadPosition": "FWD",
        "xPercent": 0,
        "yPercent": 0,
        "playerName": "Smith",
        "playerTeamCode": "USG",
        "playerPosition": "FWD",
        "playerPrice": 6.5,
        "safety": "green"
      },
      {
        "positionId": "_unassigned",
        "role": "MID",
        "broadPosition": "MID",
        "xPercent": 0,
        "yPercent": 0,
        "playerName": "Khalaili",
        "playerTeamCode": "USG",
        "playerPosition": "MID",
        "playerPrice": 10,
        "safety": "green"
      }
    ],
    "notes": "",
    "label": "",
    "createdAt": 1785980062709,
    "updatedAt": 1786020439257
  },
  {
    "id": "85893f0e-506c-4fa7-817f-d50f350fac93",
    "clubCode": "WES",
    "opponentCode": "USG",
    "formationKey": "4-3-3",
    "lastUpdatedLabel": "donderdag 06 augustus 18:00",
    "slots": [
      {
        "positionId": "GK",
        "role": "GK",
        "broadPosition": "GK",
        "xPercent": 50,
        "yPercent": 92,
        "playerName": "Jungdal",
        "playerTeamCode": "WES",
        "playerPosition": "GK",
        "playerPrice": 6.5,
        "safety": "darkgreen"
      },
      {
        "positionId": "LWB",
        "role": "LWB",
        "broadPosition": "DEF",
        "xPercent": 16,
        "yPercent": 64,
        "playerName": "Ferraro",
        "playerTeamCode": "WES",
        "playerPosition": "DEF",
        "playerPrice": 6.5,
        "safety": "red"
      },
      {
        "positionId": "LCB",
        "role": "LCB",
        "broadPosition": "DEF",
        "xPercent": 30,
        "yPercent": 79,
        "playerName": "Lapage",
        "playerTeamCode": "WES",
        "playerPosition": "DEF",
        "playerPrice": 5,
        "safety": "red"
      },
      {
        "positionId": "RCB",
        "role": "RCB",
        "broadPosition": "DEF",
        "xPercent": 70,
        "yPercent": 79,
        "playerName": "Kimura",
        "playerTeamCode": "WES",
        "playerPosition": "DEF",
        "playerPrice": 5,
        "safety": "darkgreen"
      },
      {
        "positionId": "RWB",
        "role": "RWB",
        "broadPosition": "DEF",
        "xPercent": 84,
        "yPercent": 64,
        "playerName": "Flo",
        "playerTeamCode": "WES",
        "playerPosition": "DEF",
        "playerPrice": 5,
        "safety": "orange"
      },
      {
        "positionId": "LCM",
        "role": "LCM",
        "broadPosition": "MID",
        "xPercent": 35,
        "yPercent": 47,
        "playerName": "Fofana",
        "playerTeamCode": "WES",
        "playerPosition": "MID",
        "playerPrice": 5.5,
        "safety": "green"
      },
      {
        "positionId": "CAM",
        "role": "CAM",
        "broadPosition": "MID",
        "xPercent": 50,
        "yPercent": 28,
        "playerName": "Sakamoto",
        "playerTeamCode": "WES",
        "playerPosition": "FWD",
        "playerPrice": 7,
        "safety": "green"
      },
      {
        "positionId": "RCM",
        "role": "RCM",
        "broadPosition": "MID",
        "xPercent": 65,
        "yPercent": 47,
        "playerName": "Haspolat",
        "playerTeamCode": "WES",
        "playerPosition": "MID",
        "playerPrice": 8,
        "safety": "darkgreen"
      },
      {
        "positionId": "LW",
        "role": "LW",
        "broadPosition": "FWD",
        "xPercent": 16,
        "yPercent": 18,
        "playerName": "Van den Keybus",
        "playerTeamCode": "WES",
        "playerPosition": "MID",
        "playerPrice": 6,
        "safety": "green"
      },
      {
        "positionId": "ST",
        "role": "ST",
        "broadPosition": "FWD",
        "xPercent": 50,
        "yPercent": 5,
        "playerName": "Bassette",
        "playerTeamCode": "WES",
        "playerPosition": "FWD",
        "playerPrice": 6.5,
        "safety": "darkgreen"
      },
      {
        "positionId": "RW",
        "role": "RW",
        "broadPosition": "FWD",
        "xPercent": 84,
        "yPercent": 18,
        "playerName": "Saito",
        "playerTeamCode": "WES",
        "playerPosition": "MID",
        "playerPrice": 5.5,
        "safety": "green"
      },
      {
        "positionId": "_unassigned",
        "role": "MID",
        "broadPosition": "MID",
        "xPercent": 0,
        "yPercent": 0,
        "playerName": "fe",
        "playerTeamCode": "",
        "playerPosition": "MID",
        "playerPrice": null,
        "safety": "green"
      }
    ],
    "notes": "",
    "label": "",
    "createdAt": 1785980256640,
    "updatedAt": 1786020410149
  },
  {
    "id": "4bc01b17-65ad-4a95-a2cb-7edf0c7ac758",
    "clubCode": "LOM",
    "opponentCode": "STV",
    "formationKey": "4-3-3",
    "lastUpdatedLabel": "donderdag 06 augustus 18:00",
    "slots": [
      {
        "positionId": "GK",
        "role": "GK",
        "broadPosition": "GK",
        "xPercent": 50,
        "yPercent": 92,
        "playerName": "Pieklak",
        "playerTeamCode": "LOM",
        "playerPosition": "GK",
        "playerPrice": 5.5,
        "safety": "darkgreen"
      },
      {
        "positionId": "LWB",
        "role": "LWB",
        "broadPosition": "DEF",
        "xPercent": 16,
        "yPercent": 64,
        "playerName": "Van Duiven",
        "playerTeamCode": "LOM",
        "playerPosition": "FWD",
        "playerPrice": 5,
        "safety": "red"
      },
      {
        "positionId": "LCB",
        "role": "LCB",
        "broadPosition": "DEF",
        "xPercent": 30,
        "yPercent": 79,
        "playerName": "Wouters",
        "playerTeamCode": "LOM",
        "playerPosition": "DEF",
        "playerPrice": 5,
        "safety": "darkgreen"
      },
      {
        "positionId": "RCB",
        "role": "RCB",
        "broadPosition": "DEF",
        "xPercent": 70,
        "yPercent": 79,
        "playerName": "Oware",
        "playerTeamCode": "LOM",
        "playerPosition": "DEF",
        "playerPrice": 4,
        "safety": "green"
      },
      {
        "positionId": "RWB",
        "role": "RWB",
        "broadPosition": "DEF",
        "xPercent": 84,
        "yPercent": 64,
        "playerName": "Eyoma",
        "playerTeamCode": "LOM",
        "playerPosition": "DEF",
        "playerPrice": 4.5,
        "safety": "darkgreen"
      },
      {
        "positionId": "LCM",
        "role": "LCM",
        "broadPosition": "MID",
        "xPercent": 35,
        "yPercent": 47,
        "playerName": "Nypan",
        "playerTeamCode": "LOM",
        "playerPosition": "MID",
        "playerPrice": 6.5,
        "safety": "darkgreen"
      },
      {
        "positionId": "CAM",
        "role": "CAM",
        "broadPosition": "MID",
        "xPercent": 50,
        "yPercent": 28,
        "playerName": "Schoofs",
        "playerTeamCode": "USG",
        "playerPosition": "MID",
        "playerPrice": 6.5,
        "safety": "darkgreen"
      },
      {
        "positionId": "RCM",
        "role": "RCM",
        "broadPosition": "MID",
        "xPercent": 65,
        "yPercent": 47,
        "playerName": "Pelupessy",
        "playerTeamCode": "",
        "playerPosition": "MID",
        "playerPrice": null,
        "safety": "green"
      },
      {
        "positionId": "LW",
        "role": "LW",
        "broadPosition": "FWD",
        "xPercent": 16,
        "yPercent": 18,
        "playerName": "Reyners",
        "playerTeamCode": "LOM",
        "playerPosition": "MID",
        "playerPrice": 5.5,
        "safety": "green"
      },
      {
        "positionId": "ST",
        "role": "ST",
        "broadPosition": "FWD",
        "xPercent": 50,
        "yPercent": 5,
        "playerName": "Seuntjens",
        "playerTeamCode": "LOM",
        "playerPosition": "FWD",
        "playerPrice": 6.5,
        "safety": "green"
      },
      {
        "positionId": "RW",
        "role": "RW",
        "broadPosition": "FWD",
        "xPercent": 84,
        "yPercent": 18,
        "playerName": "Salah",
        "playerTeamCode": "LOM",
        "playerPosition": "MID",
        "playerPrice": 6.5,
        "safety": "red"
      },
      {
        "positionId": "_unassigned",
        "role": "MID",
        "broadPosition": "MID",
        "xPercent": 0,
        "yPercent": 0,
        "playerName": "Schoofs",
        "playerTeamCode": "LOM",
        "playerPosition": "MID",
        "playerPrice": 6.5,
        "safety": "green"
      },
      {
        "positionId": "_unassigned",
        "role": "MID",
        "broadPosition": "MID",
        "xPercent": 0,
        "yPercent": 0,
        "playerName": "Jasper",
        "playerTeamCode": "STA",
        "playerPosition": "MID",
        "playerPrice": 5,
        "safety": "green"
      },
      {
        "positionId": "_unassigned",
        "role": "MID",
        "broadPosition": "MID",
        "xPercent": 0,
        "yPercent": 0,
        "playerName": "Reyners",
        "playerTeamCode": "LOM",
        "playerPosition": "MID",
        "playerPrice": 5.5,
        "safety": "green"
      },
      {
        "positionId": "_unassigned",
        "role": "MID",
        "broadPosition": "MID",
        "xPercent": 0,
        "yPercent": 0,
        "playerName": "wo",
        "playerTeamCode": "",
        "playerPosition": "MID",
        "playerPrice": null,
        "safety": "green"
      }
    ],
    "notes": "",
    "label": "",
    "createdAt": 1785980417175,
    "updatedAt": 1786020363903
  },
  {
    "id": "cb78536f-39b0-479e-b6aa-b8d42065ea8b",
    "clubCode": "STV",
    "opponentCode": "LOM",
    "formationKey": "4-3-3",
    "lastUpdatedLabel": "donderdag 06 augustus 18:00",
    "slots": [
      {
        "positionId": "GK",
        "role": "GK",
        "broadPosition": "GK",
        "xPercent": 50,
        "yPercent": 92,
        "playerName": "Kokubo",
        "playerTeamCode": "STV",
        "playerPosition": "GK",
        "playerPrice": 6.5,
        "safety": "darkgreen"
      },
      {
        "positionId": "LWB",
        "role": "LWB",
        "broadPosition": "DEF",
        "xPercent": 16,
        "yPercent": 64,
        "playerName": "Pupe",
        "playerTeamCode": "STV",
        "playerPosition": "DEF",
        "playerPrice": 5.5,
        "safety": "red"
      },
      {
        "positionId": "LCB",
        "role": "LCB",
        "broadPosition": "DEF",
        "xPercent": 30,
        "yPercent": 79,
        "playerName": "Musliu",
        "playerTeamCode": "STV",
        "playerPosition": "DEF",
        "playerPrice": 6,
        "safety": "darkgreen"
      },
      {
        "positionId": "RCB",
        "role": "RCB",
        "broadPosition": "DEF",
        "xPercent": 70,
        "yPercent": 79,
        "playerName": "Mbe Soh",
        "playerTeamCode": "STV",
        "playerPosition": "DEF",
        "playerPrice": 5,
        "safety": "green"
      },
      {
        "positionId": "RWB",
        "role": "RWB",
        "broadPosition": "DEF",
        "xPercent": 84,
        "yPercent": 64,
        "playerName": "Vanwesemael",
        "playerTeamCode": "STV",
        "playerPosition": "DEF",
        "playerPrice": 5.5,
        "safety": "darkgreen"
      },
      {
        "positionId": "LCM",
        "role": "LCM",
        "broadPosition": "MID",
        "xPercent": 35,
        "yPercent": 47,
        "playerName": "Ishiwatari",
        "playerTeamCode": "STV",
        "playerPosition": "MID",
        "playerPrice": 4.5,
        "safety": "green"
      },
      {
        "positionId": "CAM",
        "role": "CAM",
        "broadPosition": "MID",
        "xPercent": 50,
        "yPercent": 28,
        "playerName": "Merlen",
        "playerTeamCode": "STV",
        "playerPosition": "MID",
        "playerPrice": 5.5,
        "safety": "darkgreen"
      },
      {
        "positionId": "RCM",
        "role": "RCM",
        "broadPosition": "MID",
        "xPercent": 65,
        "yPercent": 47,
        "playerName": "Sissako",
        "playerTeamCode": "STV",
        "playerPosition": "MID",
        "playerPrice": 6.5,
        "safety": "darkgreen"
      },
      {
        "positionId": "LW",
        "role": "LW",
        "broadPosition": "FWD",
        "xPercent": 16,
        "yPercent": 18,
        "playerName": "Sebaoui",
        "playerTeamCode": "STV",
        "playerPosition": "MID",
        "playerPrice": 8,
        "safety": "darkgreen"
      },
      {
        "positionId": "ST",
        "role": "ST",
        "broadPosition": "FWD",
        "xPercent": 50,
        "yPercent": 5,
        "playerName": "Diouf",
        "playerTeamCode": "STV",
        "playerPosition": "FWD",
        "playerPrice": 6,
        "safety": "orange"
      },
      {
        "positionId": "RW",
        "role": "RW",
        "broadPosition": "FWD",
        "xPercent": 84,
        "yPercent": 18,
        "playerName": "Matsuzawa",
        "playerTeamCode": "STV",
        "playerPosition": "MID",
        "playerPrice": 6,
        "safety": "green"
      }
    ],
    "notes": "",
    "label": "",
    "createdAt": 1786015252180,
    "updatedAt": 1786020316286
  },
  {
    "id": "70557fad-4070-4254-92e1-713f2fffcee8",
    "clubCode": "AND",
    "opponentCode": "LLV",
    "formationKey": "4-3-3",
    "lastUpdatedLabel": "vrijdag 07 augustus 12:00",
    "slots": [
      {
        "positionId": "GK",
        "role": "GK",
        "broadPosition": "GK",
        "xPercent": 50,
        "yPercent": 85,
        "playerName": "Coosemans",
        "playerTeamCode": "AND",
        "playerPosition": "GK",
        "playerPrice": 6.5,
        "safety": "darkgreen"
      },
      {
        "positionId": "LWB",
        "role": "LWB",
        "broadPosition": "DEF",
        "xPercent": 16,
        "yPercent": 61,
        "playerName": "Augustinsson",
        "playerTeamCode": "AND",
        "playerPosition": "DEF",
        "playerPrice": 6,
        "safety": "red"
      },
      {
        "positionId": "LCB",
        "role": "LCB",
        "broadPosition": "DEF",
        "xPercent": 33,
        "yPercent": 74,
        "playerName": "Petrot",
        "playerTeamCode": "AND",
        "playerPosition": "DEF",
        "playerPrice": 6,
        "safety": "green"
      },
      {
        "positionId": "RCB",
        "role": "RCB",
        "broadPosition": "DEF",
        "xPercent": 67,
        "yPercent": 74,
        "playerName": "Biancone",
        "playerTeamCode": "AND",
        "playerPosition": "DEF",
        "playerPrice": 6,
        "safety": "darkgreen"
      },
      {
        "positionId": "RWB",
        "role": "RWB",
        "broadPosition": "DEF",
        "xPercent": 84,
        "yPercent": 61,
        "playerName": "Maamar",
        "playerTeamCode": "AND",
        "playerPosition": "DEF",
        "playerPrice": 5,
        "safety": "green"
      },
      {
        "positionId": "LCM",
        "role": "LCM",
        "broadPosition": "MID",
        "xPercent": 33,
        "yPercent": 46,
        "playerName": "Saliba",
        "playerTeamCode": "AND",
        "playerPosition": "MID",
        "playerPrice": 8,
        "safety": "green"
      },
      {
        "positionId": "CAM",
        "role": "CAM",
        "broadPosition": "MID",
        "xPercent": 50,
        "yPercent": 30,
        "playerName": "Ambros",
        "playerTeamCode": "AND",
        "playerPosition": "MID",
        "playerPrice": 6,
        "safety": "green"
      },
      {
        "positionId": "RCM",
        "role": "RCM",
        "broadPosition": "MID",
        "xPercent": 67,
        "yPercent": 46,
        "playerName": "Llansana",
        "playerTeamCode": "AND",
        "playerPosition": "MID",
        "playerPrice": 7,
        "safety": "orange"
      },
      {
        "positionId": "LW",
        "role": "LW",
        "broadPosition": "FWD",
        "xPercent": 16,
        "yPercent": 21,
        "playerName": "Cvetkovic",
        "playerTeamCode": "AND",
        "playerPosition": "FWD",
        "playerPrice": 8.5,
        "safety": "orange"
      },
      {
        "positionId": "ST",
        "role": "ST",
        "broadPosition": "FWD",
        "xPercent": 50,
        "yPercent": 10,
        "playerName": "Sikan",
        "playerTeamCode": "AND",
        "playerPosition": "FWD",
        "playerPrice": 6.5,
        "safety": "red"
      },
      {
        "positionId": "RW",
        "role": "RW",
        "broadPosition": "FWD",
        "xPercent": 84,
        "yPercent": 21,
        "playerName": "Antman",
        "playerTeamCode": "AND",
        "playerPosition": "MID",
        "playerPrice": 6,
        "safety": "orange"
      }
    ],
    "notes": "",
    "label": "",
    "createdAt": 1786097247576,
    "updatedAt": 1786098037558
  },
  {
    "id": "0b13b947-6c92-4adf-afa6-f9a12170e160",
    "clubCode": "GNT",
    "opponentCode": "KVM",
    "formationKey": "5-3-2",
    "lastUpdatedLabel": "vrijdag 07 augustus 14:46",
    "slots": [
      {
        "positionId": "GK",
        "role": "GK",
        "broadPosition": "GK",
        "xPercent": 50,
        "yPercent": 85,
        "playerName": "Roef",
        "playerTeamCode": "GNT",
        "playerPosition": "GK",
        "playerPrice": 7,
        "safety": "darkgreen"
      },
      {
        "positionId": "LWB",
        "role": "LWB",
        "broadPosition": "DEF",
        "xPercent": 16,
        "yPercent": 61,
        "playerName": "Araujo",
        "playerTeamCode": "GNT",
        "playerPosition": "DEF",
        "playerPrice": 5.5,
        "safety": "darkgreen"
      },
      {
        "positionId": "LCB",
        "role": "LCB",
        "broadPosition": "DEF",
        "xPercent": 33,
        "yPercent": 74,
        "playerName": "Van der Heyden",
        "playerTeamCode": "GNT",
        "playerPosition": "DEF",
        "playerPrice": 5.5,
        "safety": "darkgreen"
      },
      {
        "positionId": "CCB",
        "role": "CCB",
        "broadPosition": "DEF",
        "xPercent": 50,
        "yPercent": 76,
        "playerName": "Burgess",
        "playerTeamCode": "GNT",
        "playerPosition": "DEF",
        "playerPrice": 7,
        "safety": "darkgreen"
      },
      {
        "positionId": "RCB",
        "role": "RCB",
        "broadPosition": "DEF",
        "xPercent": 67,
        "yPercent": 74,
        "playerName": "Ngom",
        "playerTeamCode": "GNT",
        "playerPosition": "DEF",
        "playerPrice": 5,
        "safety": "orange"
      },
      {
        "positionId": "RWB",
        "role": "RWB",
        "broadPosition": "DEF",
        "xPercent": 84,
        "yPercent": 61,
        "playerName": "Volckaert",
        "playerTeamCode": "GNT",
        "playerPosition": "DEF",
        "playerPrice": 5,
        "safety": "red"
      },
      {
        "positionId": "LCM",
        "role": "LCM",
        "broadPosition": "MID",
        "xPercent": 33,
        "yPercent": 46,
        "playerName": "Delorge",
        "playerTeamCode": "GNT",
        "playerPosition": "MID",
        "playerPrice": 7,
        "safety": "green"
      },
      {
        "positionId": "CAM",
        "role": "CAM",
        "broadPosition": "MID",
        "xPercent": 50,
        "yPercent": 30,
        "playerName": "Benes",
        "playerTeamCode": "GNT",
        "playerPosition": "MID",
        "playerPrice": 6,
        "safety": "red"
      },
      {
        "positionId": "RCM",
        "role": "RCM",
        "broadPosition": "MID",
        "xPercent": 67,
        "yPercent": 46,
        "playerName": "Lopes",
        "playerTeamCode": "GNT",
        "playerPosition": "MID",
        "playerPrice": 6.5,
        "safety": "red"
      },
      {
        "positionId": "LST",
        "role": "LST",
        "broadPosition": "FWD",
        "xPercent": 28,
        "yPercent": 15,
        "playerName": "Dean",
        "playerTeamCode": "GNT",
        "playerPosition": "FWD",
        "playerPrice": 7.5,
        "safety": "orange"
      },
      {
        "positionId": "RST",
        "role": "RST",
        "broadPosition": "FWD",
        "xPercent": 72,
        "yPercent": 15,
        "playerName": "Vergara",
        "playerTeamCode": "GNT",
        "playerPosition": "FWD",
        "playerPrice": 5.5,
        "safety": "red"
      }
    ],
    "notes": "",
    "label": "",
    "createdAt": 1786097520119,
    "updatedAt": 1786098091367
  }
];
